Repository narwhals-dev/narwhals, pull requests merged in 2024-06, with the labels that each got.

#265 feat: implement narwhals.maybe_convert_dtypes
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#270 docs: updated docstrings for class DataFrame
  narwhals/dataframe.py
Labels: documentation

#266 feat: add `narwhalify` decorator
  docs/api-reference/narwhals.md
  docs/basics/column.md
  docs/basics/complete_example.md
  docs/basics/dataframe.md
  narwhals/__init__.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
  narwhals/translate.py
  tests/narwhalify_test.py
  tpch/notebooks/q1/execute.ipynb
  tpch/notebooks/q2/execute.ipynb
  tpch/notebooks/q3/execute.ipynb
  tpch/notebooks/q4/execute.ipynb
  tpch/notebooks/q5/execute.ipynb
  tpch/notebooks/q6/execute.ipynb
  tpch/notebooks/q7/execute.ipynb
Labels: enhancement

#273 update docstrings for methods
  narwhals/dataframe.py
Labels: documentation

#275 perf: use copy=False in set_axis where possible
  narwhals/_pandas_like/utils.py
Labels: performance

#277 docs: added docstring for all()
  narwhals/expression.py
Labels: documentation

#276 docs: update docstrings for dataframe.schema
  narwhals/dataframe.py
Labels: documentation

#283 docs: add overhead section
  README.md
  docs/index.md
  docs/related.md
  mkdocs.yml
  tpch/notebooks/gpu/execute.ipynb
  tpch/notebooks/q1/execute.ipynb
  tpch/notebooks/q2/execute.ipynb
  tpch/notebooks/q3/execute.ipynb
  tpch/notebooks/q4/execute.ipynb
  tpch/notebooks/q5/execute.ipynb
  tpch/notebooks/q6/execute.ipynb
  tpch/notebooks/q7/execute.ipynb
  tpch/notebooks/q8/execute.ipynb
Labels: documentation

#288 feat: implement series arithmetic
  narwhals/series.py
  tests/series/arithmetic_test.py
Labels: enhancement

#289 feat: add DataFrame.write_parquet
  docs/api-reference/dataframe.md
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/write_parquet_test.py
Labels: enhancement

#291 feat: `strftime` for datetime namespace
  docs/api-reference/expressions_dt.md
  docs/api-reference/series_dt.md
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expression.py
  narwhals/series.py
  tests/test_dt.py
Labels: enhancement

#293 docs: Contributing steps update
  .github/release-drafter.yml
  CONTRIBUTING.md
Labels: documentation

#294 clean: format docstrings with ruff
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/selectors.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
Labels: documentation

#295 test: nox for local testing
  .gitignore
  CONTRIBUTING.md
  noxfile.py
  tests/test_common.py
  tests/test_str.py
Labels: internal

#296 enh: dataframe and series `.item()`
  docs/api-reference/dataframe.md
  docs/api-reference/series.md
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/series.py
  tests/test_common.py
  tests/test_series.py
  utils/check_api_reference.py
Labels: enhancement

#297 enh: `.head()` and `.tail()`
  docs/api-reference/dataframe.md
  docs/api-reference/expressions.md
  docs/api-reference/lazyframe.md
  docs/api-reference/series.md
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
  tests/test_common.py
  tests/test_series.py
Labels: enhancement

#298 ci: Removed conflicting github release
  .github/workflows/publish_to_pypi.yml
Labels: internal

#304 docs: Update docs for with_columns
  narwhals/dataframe.py
Labels: documentation

#303 ci: issue template correction
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: internal

#305 enh: `slice`, `starts_with`, `tail` methods for `str` namespace
  docs/api-reference/expressions_str.md
  docs/api-reference/series_str.md
  mkdocs.yml
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr/str/slice_test.py
  tests/expr/str/tail_test.py
  tests/test_str.py
Labels: enhancement

#306 enh: series and expr round method
  docs/api-reference/expressions.md
  docs/api-reference/series.md
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr/round_test.py
Labels: enhancement

#307 perf: use fastpath in with_columns
  narwhals/_pandas_like/dataframe.py
  requirements-dev.txt
  tests/test_common.py
  tests/test_invalid.py
  tests/utils_test.py
Labels: performance

#314 chore: polars 1.0 compat
  tests/frame/pipe_test.py
  tests/test_common.py
  tests/test_series.py
Labels: internal

#318 docs: Update docs for select
  narwhals/dataframe.py
Labels: documentation

#316 ci: Added Version
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  tests/test_common.py
Labels: internal

#321 feat: add `narwhals.lit`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_pandas_like/namespace.py
  narwhals/expression.py
  tests/test_common.py
Labels: enhancement

#323 enh: `Expr.len` and `Series.len`
  docs/api-reference/expressions.md
  docs/api-reference/series.md
  narwhals/_pandas_like/expr.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr/len_test.py
  tests/test_series.py
Labels: enhancement

#315 chore: simplify Series
  narwhals/_pandas_like/series.py
Labels: internal

#324 ci: Added show_versions() to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: internal

#327 ci: Updating github actions artifacts
  .github/workflows/publish_to_pypi.yml
Labels: internal

#317 feat: add DataFrame.rows
  docs/api-reference/dataframe.md
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/rows_test.py
Labels: enhancement

#329 feat: add cat.get_categories, make test numpy2.0 compatible
  mkdocs.yml
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
  narwhals/utils.py
  tests/cat/__init__.py
  tests/cat/get_categories_test.py
  tests/test_invalid.py
  utils/check_api_reference.py
Labels: enhancement

#330 fix: group-by(...).agg(nw.col(...).len()) was raising unnecessarily
  narwhals/_pandas_like/group_by.py
  tests/group_by_test.py
Labels: fix

#332 docs: Update documentation for group_by
  narwhals/dataframe.py
Labels: documentation

#335 refactor: rename `series_from_iterable`
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
Labels: internal

#336 refactor: Refactor and reorganise tests
  tests/expr/cat/__init__.py
  tests/expr/cat/get_categories_test.py
  tests/expr/str/starts_with_ends_with_test.py
  tests/expr/test_dt.py
  tests/frame/rows_test.py
  tests/frame/test_common.py
  tests/frame/test_invalid.py
  tests/group_by_test.py
  tests/series/test_common.py
  tests/test_group_by.py
  tests/test_selectors.py
  tests/test_utils.py
  tests/translate/__init__.py
  tests/translate/from_native_pandas_test.py
  tests/translate/get_native_namespace_test.py
  tests/translate/narwhalify_test.py
  tests/utils.py
Labels: internal

#341 feat: support Date dtype in Narwhals
  narwhals/__init__.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/dtypes.py
  tests/series/cast_test.py
Labels: enhancement

#345 feat: add Series.to_list
  docs/api-reference/series.md
  narwhals/_pandas_like/series.py
  narwhals/series.py
  tests/series/to_list_test.py
  utils/check_api_reference.py
Labels: enhancement

#351 feat: add DataFrame.rows
  docs/api-reference/dataframe.md
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/rows_test.py
Labels: enhancement

#354 refactor: remove `get_` functions from translate
  narwhals/translate.py
Labels: internal

#350 feat: start adding support Pyarrow table (not yet complete!)
  .github/workflows/extremes.yml
  .github/workflows/mkdocs.yml
  .github/workflows/pytest.yml
  docs/roadmap.md
  narwhals/_arrow/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/expression.py
  narwhals/series.py
  narwhals/translate.py
  pyproject.toml
  requirements-dev.txt
  tests/expr/cum_sum_test.py
  tests/expr/sample_test.py
  tests/expr/test_dt.py
  tests/frame/schema_test.py
  tests/frame/shape_test.py
  tests/frame/slice_test.py
  tests/frame/test_common.py
  tests/frame/test_invalid.py
  tests/series/shape_test.py
  tests/series/test_common.py
  tests/translate/get_native_namespace_test.py
  tests/utils.py
Labels: enhancement

#360 feat: add duration dtype
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/dtypes.py
  tests/frame/schema_test.py
  tests/series/test_common.py
Labels: enhancement

#358 refactor: always recommend `from_native`
  narwhals/dataframe.py
  narwhals/series.py
  tests/expr/str/starts_with_ends_with_test.py
  tests/frame/drop_nulls_test.py
  tests/frame/pipe_test.py
  tests/frame/test_common.py
  tests/frame/test_invalid.py
  tests/frame/with_row_index_test.py
  tests/hypothesis/test_concat.py
  tests/series/test_common.py
  tests/test_group_by.py
  tests/tpch_q1_test.py
Labels: internal

#361 feat: add is_pandas_dataframe
  docs/api-reference/dependencies.md
  narwhals/dependencies.py
  tests/dependencies/__init__.py
  tests/dependencies/is_pandas_dataframe_test.py
Labels: enhancement

#362 feat: add typeguard for is_pandas_dataframe
  .pre-commit-config.yaml
  narwhals/dependencies.py
Labels: enhancement

#364 fix: compatibility with old numpy versions
  .github/workflows/extremes.yml
  narwhals/_pandas_like/utils.py
  tests/series/test_common.py
Labels: fix
