Repository narwhals-dev/narwhals, pull requests merged in 2024-11, with the labels that each got.

#1292 Enh: adding automated inferencing of format `%Y-%m-%dT%H:%M` in pyarrow
  narwhals/_arrow/utils.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement

#1288 feat: add is_into_dataframe
  docs/api-reference/dependencies.md
  narwhals/dependencies.py
  tests/dependencies/is_into_dataframe_test.py
Labels: enhancement

#1304 fix: np.datetime64 scalar with ns resolution was become int instead of datetime in to_py_scalar
  narwhals/translate.py
  tests/translate/to_py_scalar_test.py
Labels: fix

#1305 fix: consistent to_numpy behaviour for tz-aware
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  tests/conftest.py
  tests/frame/to_numpy_test.py
  tests/series_only/to_numpy_test.py
Labels: fix

#1303 fix: fixed-offset datetime weren't being parsed
  narwhals/_pandas_like/utils.py
  tests/dtypes_test.py
Labels: fix

#1228 ci: add vegafusion in ci checks
  .github/workflows/downstream_tests.yml
  .github/workflows/publish_to_pypi.yml
Labels: internal

#1309 docs: document Stable API changes
  docs/backcompat.md
Labels: documentation

#1310 fix: consistent naming of positional arguments in from_native
  docs/backcompat.md
  narwhals/stable/v1/__init__.py
  tests/stable_api_test.py
Labels: fix

#1308 depr: deprecate `strict` in `from_native` / `to_native` in favour of `pass_through`
  docs/backcompat.md
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/utils.py
  tests/translate/from_native_test.py
  tests/translate/narwhalify_test.py
  tests/translate/to_native_test.py
Labels: deprecation

#1312 Revert "Revert "depr: deprecate strict in from_native / `to_native` in favour of `pass_through`
  .github/workflows/downstream_tests.yml
  docs/backcompat.md
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/utils.py
  tests/translate/from_native_test.py
  tests/translate/narwhalify_test.py
  tests/translate/to_native_test.py
Labels: internal

#1314 release: Bump version to 1.13.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1316 release: Bump version to 1.13.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1320 docs: add note about conversion as if from utc in convert_time_zone
  narwhals/expr.py
  narwhals/series.py
Labels: documentation

#1325 release: Bump version to 1.13.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1332 docs: update README with entry in Appears on section
  README.md
Labels: documentation

#1333 feat: add `maintain_order` to Expr.unique and Series.unique
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/unique_test.py
Labels: enhancement

#1331 docs: add "returns" documentation to functions.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1321 ci: trigger slow downstream libraries tests suites before release
  .github/workflows/downstream_tests.yml
  .github/workflows/downstream_tests_slow.yml
  .github/workflows/publish_to_pypi.yml
Labels: internal

#1334 perf: improve `ArrowGroupBy.__iter__` performances
  narwhals/_arrow/group_by.py
Labels: performance

#1335 feat: support to_list for cudf, note limitations
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
  pyproject.toml
Labels: enhancement

#1327 feat: add `replace` and `replace_strict`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/replace_strict_test.py
Labels: enhancement

#1098 test: Add a hypothesis test for __getitem__
  requirements-dev.txt
  tests/hypothesis/getitem_test.py
Labels: internal

#1339 docs: used by `tabmat`
  README.md
Labels: documentation

#1343 ci: pin websockets, fixup 3.13 doctests, remove unnecessary xfail
  .github/workflows/downstream_tests.yml
  narwhals/expr.py
  tests/selectors_test.py
Labels: internal

#1340 feat: allow mapping in `replace_strict` method
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/replace_strict_test.py
Labels: enhancement

#1212 feat: add support for `median`
  docs/api-reference/expr.md
  docs/api-reference/narwhals.md
  docs/api-reference/series.md
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_exceptions.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/median_test.py
  tests/expr_and_series/unary_test.py
  tests/group_by_test.py
Labels: enhancement

#1326 feat: pyarrow automated inference of format `%Y%m%d%H%M%S`
  narwhals/_arrow/utils.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement

#1347 fix: Fix `nw.lit` out names
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/frame/lit_test.py
Labels: fix

#1348 ci: remove dask from tpch tests
  tpch/execute/q1.py
  tpch/execute/q10.py
  tpch/execute/q11.py
  tpch/execute/q12.py
  tpch/execute/q13.py
  tpch/execute/q14.py
  tpch/execute/q15.py
  tpch/execute/q16.py
  tpch/execute/q17.py
  tpch/execute/q18.py
  tpch/execute/q19.py
  tpch/execute/q2.py
  tpch/execute/q20.py
  tpch/execute/q21.py
  tpch/execute/q22.py
  tpch/execute/q3.py
  tpch/execute/q4.py
  tpch/execute/q5.py
  tpch/execute/q6.py
  tpch/execute/q7.py
  tpch/execute/q8.py
  tpch/execute/q9.py
Labels: internal

#1269 feat: Adding support for Expr.map_batches
  docs/api-reference/expr.md
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/expr.py
  tests/expr_and_series/map_batches_test.py
  utils/check_api_reference.py
Labels: enhancement

#1351 chore: Rename some internals
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
Labels: internal

#1353 test: remove cuDF xfail for tests/series_only/to_list_test.py::test_to_list
  tests/series_only/to_list_test.py
Labels: internal

#1354 test: fix docstrings tests in CI
  .github/workflows/pytest.yml
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
Labels: internal

#1356 perf: replace loc with getitem in Dask
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
Labels: performance

#1355 perf: Prefer getitem instead of loc for selecting multiple columns in pandas-like
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/utils.py
  tests/frame/select_test.py
Labels: performance

#1319 feat: support passing index object directly into maybe_set_index
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#1040 fix: pandas and arrow `to_dummies` with nulls
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  tests/series_only/to_dummy_test.py
Labels: fix

#1359 chore: add issue_deprecation_warning to generate_unique_token function
  narwhals/utils.py
Labels: internal

#1358 chore: Improve typing in _polars/utils
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/functions.py
Labels: internal

#1364 test: unxfail `test_to_dummies_drop_first_na` for cudf
  tests/series_only/to_dummy_test.py
Labels: internal

#546 feat: add `DataFrame.pivot` for pandas like and Polars backend
  docs/api-reference/dataframe.md
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  pyproject.toml
  tests/frame/pivot_test.py
  utils/generate_backend_completeness.py
Labels: enhancement

#1375 docs: Avoid copying >>> and ... from clipboard
  docs/javascripts/extra.js
  mkdocs.yml
Labels: documentation

#1374 chore: cleanup tpch execute
  tpch/README.md
  tpch/execute.py
  tpch/execute/__init__.py
  tpch/execute/q1.py
  tpch/execute/q10.py
  tpch/execute/q11.py
  tpch/execute/q12.py
  tpch/execute/q13.py
  tpch/execute/q14.py
  tpch/execute/q15.py
  tpch/execute/q16.py
  tpch/execute/q17.py
  tpch/execute/q18.py
  tpch/execute/q19.py
  tpch/execute/q2.py
  tpch/execute/q20.py
  tpch/execute/q21.py
  tpch/execute/q22.py
  tpch/execute/q3.py
  tpch/execute/q4.py
  tpch/execute/q5.py
  tpch/execute/q6.py
  tpch/execute/q7.py
  tpch/execute/q8.py
  tpch/execute/q9.py
  tpch/tests/queries_test.py
Labels: internal

#1377 chore: More Polars typing, update 'used by', link to roadmap
  README.md
  docs/roadmap_and_related.md
  narwhals/_polars/expr.py
Labels: internal

#1378 chore: suggest to add issue number in pr template
  .github/pull_request_template.md
Labels: internal

#1381 docs: Document more return types
  docs/requirements-docs.txt
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/dtypes.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/schema.py
  narwhals/selectors.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/hypothesis/getitem_test.py
  utils/check_for_no_build_errors.py
Labels: documentation

#1380 feat: add `Series|Expr.cum_count` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/cum_count_test.py
  tests/expr_and_series/cum_sum_test.py
Labels: enhancement

#1121 docs : docstrings examples - dtypes
  narwhals/dtypes.py
Labels: documentation

#1382 feat: Improve error message when comparing Series with list literal, or when using multi-output expressions in unsupported context
  narwhals/_arrow/utils.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/expr.py
  narwhals/series.py
  tests/frame/reindex_test.py
  tests/frame/select_test.py
Labels: enhancement

#1384 feat: add `Series|Expr` `cum_min` and `cum_max` methods
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/cum_count_test.py
  tests/expr_and_series/cum_max_test.py
  tests/expr_and_series/cum_min_test.py
Labels: enhancement

#1388 docs: Show ExprT as return type for Expr namespaces
  narwhals/expr.py
  narwhals/series.py
  narwhals/utils.py
Labels: documentation

#1389 feat: consistently raise `ColumnNotFoundError` for missing columns in `select` and `drop`
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_exceptions.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/utils.py
  tests/frame/select_test.py
Labels: enhancement, internal

#1379 chore: Consistent invalid `IntoExpr` error
  narwhals/_dask/utils.py
  narwhals/_exceptions.py
  narwhals/_expression_parsing.py
  narwhals/_polars/dataframe.py
  tests/frame/select_test.py
Labels: internal

#1391 feat: make exceptions module public
  docs/api-reference/exceptions.md
  docs/api-reference/index.md
  mkdocs.yml
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_dask/utils.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/exceptions.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/expr_and_series/median_test.py
  tests/frame/drop_test.py
  tests/frame/select_test.py
Labels: enhancement

#1392 docs: Add page about pandas booleans
  .github/workflows/extremes.yml
  docs/pandas_like_concepts/boolean.md
  docs/pandas_like_concepts/column_names.md
  docs/pandas_like_concepts/pandas_index.md
  docs/pandas_like_concepts/user_warning.md
  mkdocs.yml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
Labels: documentation

#1394 docs: pandas boolean content tabs
  docs/backcompat.md
  docs/pandas_like_concepts/boolean.md
Labels: documentation

#1393 chore: update `InvalidIntoExprError` to mention `nw.lit`
  narwhals/exceptions.py
  tests/frame/select_test.py
Labels: internal

#1396 docs: add missing description for left join strategy
  narwhals/dataframe.py
Labels: documentation

#1341 feat: add `Series|Expr.is_finite` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/is_finite_test.py
Labels: enhancement

#1397 release: Bump version to 1.14.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1399 ci: prevent ibis from setting upper bounds (where possible)
  .github/workflows/pytest.yml
  noxfile.py
Labels: internal

#1395 feat: add `Series|Expr.rolling_sum` method
  docs/api-reference/exceptions.md
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/exceptions.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/rolling_sum_test.py
Labels: enhancement

#1376 ci: add plotly to downstream tests
  .github/workflows/downstream_tests.yml
Labels: internal

#1298 feat: Adding ewm_mean
  docs/api-reference/expr.md
  docs/api-reference/series.md
  docs/css/code_select.css
  docs/javascripts/katex.js
  mkdocs.yml
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/ewm_test.py
Labels: enhancement

#1402 release: Bump version to 1.14.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1406 docs: use from_native / to_native in series.py
  .pre-commit-config.yaml
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/stable_api_test.py
Labels: documentation

#1409 docs: add vegafusion to "used by" on readme
  README.md
Labels: documentation

#1408 docs: use type hints + from_native/to_native in series.py
  narwhals/series.py
Labels: documentation

#1411 docs: use type hints + from_native/to_native in dataframe.py
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1290 feat: add `Expr|Series.rolling_mean` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/expr_and_series/rolling_mean_test.py
Labels: enhancement

#1415 fix: correct minimum Polars version for ewm_mean
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  tests/expr_and_series/ewm_test.py
Labels: internal, fix

#1422 ci: temporarily pin olama
  .github/workflows/downstream_tests.yml
Labels: internal

#1423 docs: Add documentation for LazyGroupBy
  docs/api-reference/index.md
  docs/api-reference/lazy_group_by.md
  mkdocs.yml
  narwhals/group_by.py
Labels: documentation

#1421 docs: explain optional boolean args in from_native
  .github/workflows/check_docs_build.yml
  docs/requirements-docs.txt
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
Labels: documentation

#1417 feat: support `constraints` in `DataFrame.filter`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/expr.py
  tests/expr_and_series/filter_test.py
Labels: enhancement

#1425 docs: use type hints + from_native/to_native in dataframe.py
  narwhals/dataframe.py
Labels: documentation

#1430 feat: make sure `from narwhals.stable.v1.dependencies` import works
  narwhals/dependencies.py
  narwhals/stable/v1/dependencies.py
  tests/conftest.py
  tests/dependencies/is_into_dataframe_test.py
  tests/dependencies/is_into_series_test.py
  tests/dependencies/is_pandas_dataframe_test.py
  tests/dependencies/is_pandas_index_test.py
  tests/translate/to_py_scalar_test.py
Labels: enhancement

#1173 feat: add support for `Series|Expr.skew` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/skew_test.py
  tests/expr_and_series/unary_test.py
Labels: enhancement

#1429 feat: improve error message when casting to invalid type
  narwhals/_arrow/utils.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/utils.py
  tests/expr_and_series/cast_test.py
  tests/frame/invalid_test.py
Labels: enhancement

#1432 fix: return Python bool instead of pyarrow boolean scalar for Series reductions
  narwhals/_arrow/series.py
Labels: fix

#1433 release: Bump version to 1.14.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1435 feat: improve `concat` error message and `concat` docs
  narwhals/_arrow/utils.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/concat_test.py
Labels: enhancement

#1438 docs: Add docstrings with examples to types
  .github/workflows/downstream_tests.yml
  docs/api-reference/typing.md
  narwhals/stable/v1/typing.py
  narwhals/typing.py
Labels: documentation

#1439 feat: silently support Fireducks and cudf.pandas
  .github/workflows/downstream_tests.yml
  narwhals/dependencies.py
Labels: enhancement

#1440 docs: fixup copy button
  .github/workflows/downstream_tests.yml
  mkdocs.yml
Labels: documentation

#1441 chore: add `backend_version` parameter to polars dtype translation utility
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal

#1446 ci: get cudf tests passing again
  pyproject.toml
  tests/expr_and_series/ewm_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/frame/pivot_test.py
Labels: internal

#1449 feat: raise `NotImplementedError` for not supported parameters in `ewm_mean` for cuDF
  narwhals/_pandas_like/series.py
  tests/expr_and_series/ewm_test.py
Labels: enhancement

#1452 docs: fixup typing in docstrings
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1453 ci: Check docstrings don't have unused imports in docstring examples
  .github/workflows/downstream_tests.yml
  .pre-commit-config.yaml
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  utils/check_docstrings.py
Labels: internal

#1458 fix: Preseve dtypes modules in from dict
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/stable/v1/__init__.py
  tests/from_dict_test.py
  tests/translate/from_native_test.py
Labels: fix

#1459 feat: allow for "import narwhals.stable.v1.selectors as cs"
  narwhals/__init__.py
  narwhals/selectors.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/selectors.py
  tests/selectors_test.py
Labels: enhancement

#1460 ci: add hierarchicalforecast
  .github/workflows/downstream_tests.yml
  README.md
Labels: internal

#1455 feat: diagonal concat
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/concat_test.py
Labels: enhancement

#1456 feat: create dataframe from 2D numpy array and column names
  .github/workflows/downstream_tests.yml
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/from_numpy_test.py
Labels: enhancement

#1412 feat: make `Series` generic
  docs/backcompat.md
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/typing.py
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#1465 chore: PyArrow type hinting
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/expr.py
  narwhals/series.py
  requirements-dev.txt
Labels: internal

#1461 docs: add `from/to_native` in documentation examples
  docs/backcompat.md
  docs/basics/complete_example.md
  docs/basics/dataframe.md
  docs/basics/series.md
  docs/extending.md
Labels: documentation

#1424 fix: address `lit` broadcasting and output name of right arithmetic ops
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/series.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/operators_test.py
  tests/frame/lit_test.py
  tests/utils.py
Labels: fix

#1470 ci: Remove vegafusion from blocking releases, assert current branch in bump_version
  .github/workflows/publish_to_pypi.yml
  utils/bump_version.py
Labels: internal

#1466 docs: clean lazyframe docstrings
  narwhals/dataframe.py
Labels: documentation

#1471 feat: consistently return Python scalars from Series reductions for PyArrow
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_expression_parsing.py
  narwhals/dependencies.py
  narwhals/selectors.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/stable/v1/dependencies.py
  narwhals/stable/v1/dtypes.py
  narwhals/stable/v1/selectors.py
  narwhals/stable/v1/typing.py
  narwhals/translate.py
  narwhals/typing.py
  tests/translate/to_py_scalar_test.py
  tests/utils.py
Labels: enhancement

#1472 release: Bump version to 1.15.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1475 fix: follow left-hand-rule in index alignment in from_dict
  .github/workflows/extremes.yml
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/from_dict_test.py
Labels: fix
