Repository narwhals-dev/narwhals, pull requests merged in 2024-12, with the labels that each got.

#1467 chore: polars type hinting
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/group_by.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal

#1476 release: Bump version to 1.15.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1477 chore: rename validate_column_comparand utility functions, add pep740 badge
  README.md
  docs/index.md
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
  utils/generate_zen_content.py
Labels: internal

#1478 fix: Set level correctly for lazy-only implementations
  docs/extending.md
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/translate.py
Labels: fix

#1488 fix: nw.Series could not be pickled
  .pre-commit-config.yaml
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_interchange/dataframe.py
  narwhals/_interchange/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/utils.py
  tests/pickle_test.py
  tests/translate/from_native_test.py
Labels: fix

#1490 chore: rename _change_dtypes to _change_version
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/stable/v1/__init__.py
  tests/translate/from_native_test.py
Labels: internal

#1491 feat: improve invalid concat error message
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/frame/invalid_test.py
Labels: enhancement

#1480 feat: add `Series.__contains__`
  narwhals/__init__.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  narwhals/stable/v1/selectors.py
  pyproject.toml
  tests/selectors_test.py
  tests/series_only/__contains___test.py
  utils/check_api_reference.py
Labels: enhancement

#1497 test: fix nox dependencies
  noxfile.py
Labels: internal

#908 feat: Add minimal PySpark support
  .github/workflows/extremes.yml
  narwhals/_expression_parsing.py
  narwhals/_spark_like/__init__.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/typing.py
  narwhals/_spark_like/utils.py
  narwhals/dependencies.py
  narwhals/translate.py
  narwhals/utils.py
  noxfile.py
  pyproject.toml
  requirements-dev.txt
  tests/conftest.py
  tests/no_imports_test.py
  tests/spark_like_test.py
  tests/utils.py
Labels: enhancement

#1509 docs: update contributing guide by adding upstream remote
  CONTRIBUTING.md
Labels: documentation

#1513 docs: add return description for `Series.to_list`
  narwhals/series.py
Labels: documentation

#1514 docs: add `Enum` dtype docstring example
  narwhals/dtypes.py
Labels: documentation

#1517 chore: in _series renamed _pandas_series to _compliant_series
  narwhals/_pandas_like/series.py
Labels: internal

#1516 docs: add Duration dtype docstring example
  narwhals/dtypes.py
  narwhals/stable/v1/_dtypes.py
Labels: documentation

#1518 chore: rename _call to _to_compliant_expr in narwhals/expr.py
  docs/how_it_works.md
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
Labels: internal

#1519 chore: overload parse_into_expr
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
Labels: internal

#1528 docs: Add `narwhals.dtypes.Date` docstring example
  narwhals/dtypes.py
Labels: documentation

#1527 chore: rename `_expr` to `_compliant_expr` in `PandasLikeExpr`
  narwhals/_pandas_like/expr.py
Labels: internal

#1530 docs: add link to "Generating a new SSH key"
  CONTRIBUTING.md
Labels: documentation

#1532 chore: remove many false positives from "ignore banned import" check
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/translate.py
  utils/import_check.py
Labels: internal

#1531 feat: Expose nw.Implementation, along with `Implementation.is_pandas`, `Implementation.is_pandas_like`, and more
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  docs/api-reference/series.md
  narwhals/__init__.py
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/implementation_test.py
  utils/check_api_reference.py
Labels: enhancement

#1534 release: Bump version to 1.16.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1537 chore: rename `series` and `expr` to `_compliant` for Arrow, Polars, and Dask
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
Labels: internal

#1536 feat: `ListNamespace.len()` for `Expr` and `Series`
  docs/api-reference/expr_list.md
  docs/api-reference/series_list.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/list/__init__.py
  tests/expr_and_series/list/len_test.py
  utils/check_api_reference.py
Labels: enhancement

#1539 ci: try using "unrelease" version-template for release drafter
  .github/release-drafter.yml
Labels: internal

#1543 chore: avoid unnecessary branching on pl version in `pln.mean`
  narwhals/_polars/namespace.py
Labels: internal

#1547 ci: actually test against pandas nightly, don't filter "copy is deprecated" warnings
  .github/workflows/extremes.yml
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  pyproject.toml
Labels: internal, deprecation

#1550 enh: nw.dependencies.is_narwhals_dataframe / nw.dependencies.is_narwhals_lazyframe / nw.dependencies.is_narwhals_series
  narwhals/dependencies.py
  narwhals/stable/v1/dependencies.py
  tests/dependencies/is_narwhals_dataframe_test.py
  tests/dependencies/is_narwhals_lazyframe_test.py
  tests/dependencies/is_narwhals_series_test.py
Labels: enhancement

#1544 docs: Add a docstring example in narwhals.dtypes for Datetime
  narwhals/dtypes.py
  narwhals/stable/v1/_dtypes.py
Labels: documentation

#1552 ci: temporary pins to get CI green
  .github/workflows/downstream_tests.yml
Labels: internal

#1554 fix: return Python scalar for Series.__getitem__ when pyarrow-backed (like Polars does)
  narwhals/_arrow/series.py
  tests/series_only/slice_test.py
Labels: fix

#1549 feat: Adding dataframe estimated size
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/typing.py
  narwhals/utils.py
  tests/frame/estimated_size_test.py
Labels: enhancement

#1551 feat: `read_csv`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_csv_test.py
Labels: enhancement

#1555 feat: `scan_csv`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/scan_csv_test.py
Labels: enhancement

#1558 docs: add `nw.Expr.list`, `nw.Series.list` to `api-reference`
  docs/api-reference/index.md
  mkdocs.yml
  utils/check_api_reference.py
Labels: documentation

#1560 feat: add `**kwargs` to `read_csv` and `scan_csv`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_csv_test.py
  tests/scan_csv_test.py
Labels: enhancement

#1567 ci: remove pull_request_target, sanitise github.ref_name
  .github/release-drafter.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
Labels: ci, internal

#1568 docs: add security page to docs, try removing some temporary CI pins
  .github/workflows/downstream_tests.yml
  docs/assets/image.png
  docs/index.md
  docs/security.md
  mkdocs.yml
  tests/data/customer.csv
  tests/data/customer.parquet
  tests/data/lineitem.csv
  tests/data/lineitem.parquet
  tests/data/nation.csv
  tests/data/nation.parquet
  tests/data/orders.csv
  tests/data/orders.parquet
  tests/data/part.csv
  tests/data/part.parquet
  tests/data/partsupp.csv
  tests/data/partsupp.parquet
  tests/data/region.csv
  tests/data/region.parquet
  tests/data/supplier.csv
  tests/data/supplier.parquet
  tests/tpch_q1_test.py
Labels: documentation

#1564 perf: use lru_cache for native_to_narwhals_dtype
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
Labels: performance

#1573 docs: Restore image in docs
  docs/assets/image.png
  docs/index.md
Labels: documentation

#1559 docs:add docstring series getitem
  narwhals/series.py
Labels: documentation

#1577 enh: add `read_parquet` / `scan_parquet`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_csv_test.py
  tests/read_scan_test.py
  tests/scan_csv_test.py
Labels: enhancement

#1574 feat: Preserve null values in old Polars versions for ewm_mean
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  tests/expr_and_series/ewm_test.py
Labels: enhancement

#1571 feat: add Decimal dtype
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/stable/v1/dtypes.py
  narwhals/typing.py
  tests/dtypes_test.py
Labels: enhancement

#1578 refactor: use `nw.scan_parquet` in tpch benchmarks
  tpch/execute.py
Labels: internal

#1584 feat: Improve error message when trying to do unsupported group-by aggregation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/dependabot.yml
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
  docs/css/extra.css
  docs/javascripts/extra.js
  docs/javascripts/katex.js
  mkdocs.yml
  narwhals/_arrow/group_by.py
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/group_by.py
  narwhals/_spark_like/group_by.py
  tests/group_by_test.py
Labels: enhancement

#1591 docs: Correct small error in IntoDataFrameT and IntoSeriesT
  narwhals/stable/v1/typing.py
  narwhals/typing.py
Labels: documentation

#1522 chore: Add some Compliant Protocols
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/typing.py
Labels: internal

#1595 test: xfail test_group_by_shift_raises for cudf
  tests/group_by_test.py
Labels: tests

#1594 docs: document arguments and returns in DataFrame class
  narwhals/dataframe.py
Labels: documentation

#1529 feat: add `Series` and `Expr` `arg_min` & `arg_max`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/arg_max_test.py
  tests/expr_and_series/arg_min_test.py
Labels: enhancement

#1599 test: xfail cudf argmin / argmax
  tests/expr_and_series/arg_max_test.py
  tests/expr_and_series/arg_min_test.py
Labels: tests

#1565 fix: Add support for pandas cumulative operations with over
  narwhals/_pandas_like/expr.py
  narwhals/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#1451 feat: add `Series|Expr.rolling_var` and `Series|Expr.rolling_std`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_var_test.py
Labels: enhancement

#1613 fix: pandas and pyarrow were raising for repeated aggregations involving the same root name and the same aggregation function
  .github/workflows/extremes.yml
  narwhals/_arrow/group_by.py
  narwhals/_pandas_like/group_by.py
  pyproject.toml
  tests/group_by_test.py
Labels: fix

#1617 test: minimum versions
  .github/workflows/extremes.yml
Labels: ci

#1621 perf: streamline pyarrow and pandas group by agg
  narwhals/_arrow/group_by.py
  narwhals/_pandas_like/group_by.py
Labels: performance

#1600 docs: more args and returns documentation in DataFrame class
  narwhals/dataframe.py
Labels: documentation

#1623 release: Bump version to 1.19.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1626 test: not-so-old-versions, pretty-old-versions, nightlies
  .github/workflows/extremes.yml
Labels: internal, tests

#1624 docs: null handling
  docs/pandas_like_concepts/null_handling.md
  mkdocs.yml
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
Labels: documentation

#1635 fix: exclude protocols in api completeness script
  noxfile.py
  utils/generate_backend_completeness.py
Labels: internal

#1636 docs: Use relative paths
  docs/extending.md
  docs/index.md
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
Labels: documentation

#1642 chore: Update pyproject.toml
  docs/requirements-docs.txt
  pyproject.toml
Labels: internal

#1640 fix: Make compatible with latest cuDF release
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  pyproject.toml
  tests/expr_and_series/over_test.py
  tests/frame/pivot_test.py
  tests/frame/unpivot_test.py
  tests/group_by_test.py
Labels: fix, tests

#1542 feat: add `DataFrame` and `LazyFrame` `explode` method
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/exceptions.py
  tests/frame/explode_test.py
Labels: enhancement

#1645 feat: support std and var with ddof !=1 in pandas-like group by
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/utils.py
  tests/group_by_test.py
Labels: enhancement

#1643 docs: Note that `maintains_order` has no effect (but keep around for backwards-compatibility)
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  tests/frame/pivot_test.py
Labels: documentation

#1648 release: Bump version to 1.19.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1653 docs: Add return descriptions to Series's `abs`, `alias`, `all`, `any` methods for clarity
  narwhals/series.py
Labels: documentation

#1655 ci: split `dev` from `extra`
  .github/workflows/check_tpch_queries.yml
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: internal

#1658 chore: use `__narwhals_namespace__` more
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/dataframe.py
  tests/dtypes_test.py
  tests/frame/concat_test.py
Labels: internal

#1652 ci: improve publish ci to use env vars
  .github/workflows/publish_to_pypi.yml
Labels: internal

#1668 test: check keys are in the same order in assert_equal_data
  tests/hypothesis/concat_test.py
  tests/utils.py
Labels: internal

#1665 fix: pyspark group by with kwargs
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/utils.py
  narwhals/typing.py
  tests/spark_like_test.py
Labels: fix

#1670 test: add test for `nw.Expr|Series.str.contains` with `literal=True`
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/str/contains_test.py
Labels: internal, tests

#1673 docs: add return type descriptions for `cum_count`, `cum_max`, `cum_min`, `cum_prod`, `cum_sum` in Series
  narwhals/series.py
Labels: documentation

#1671 chore: flatten `subset` in `unique` one level up
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
Labels: internal

#1674 docs: Add more return type descriptions for Series
  narwhals/series.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1672 feat: expressify `lower_bound` and `upper_bound` in `is_between`
  docs/how_it_works.md
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/namespace.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/is_between_test.py
Labels: enhancement

#1675 docs: Add return type description for more series namespace
  narwhals/series.py
Labels: documentation

#1663 chore, perf: arrow cat namespace
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
Labels: performance

#1662 chore: pyarrow do not combine chunks
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
Labels: internal

#1677 feat: raise informative error message when grouping by expressions
  narwhals/dataframe.py
  tests/group_by_test.py
Labels: enhancement

#1664 docs: use `IntoDataFrameT`/`IntoFrameT` in docs
  docs/pandas_like_concepts/boolean.md
  docs/pandas_like_concepts/column_names.md
  docs/pandas_like_concepts/pandas_index.md
  docs/pandas_like_concepts/user_warning.md
Labels: documentation

#1679 fix: `is_duplicated` was returning wrong-length result for PyArrow and Dask
  narwhals/_arrow/dataframe.py
  narwhals/_dask/expr.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
Labels: fix, high priority

#1681 release: Bump version to 1.20.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1682 release: Bump version to 1.20.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1686 fix: casting to List for cudf
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/max_horizontal_test.py
  tests/expr_and_series/min_horizontal_test.py
  tests/group_by_test.py
Labels: fix

#1633 feat: add some `SparkLikeLazyFrame` methods
  narwhals/_spark_like/dataframe.py
  tests/spark_like_test.py
Labels: enhancement

#1684 fix: Dask was raising for scalar vs Series binary operations
  narwhals/_dask/expr.py
  narwhals/_dask/utils.py
  tests/frame/select_test.py
  tests/utils.py
Labels: fix

#1688 docs: `DataFrame` method' docstrings
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
Labels: documentation
