Repository narwhals-dev/narwhals, pull requests merged in 2024-10, with the labels that each got.

#1104 feat: allow inspecting the inner type of List
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  tests/dtypes_test.py
Labels: enhancement

#1105 test: update check for cuDF series
  tests/utils.py
Labels: internal

#1106 test: xfail __iter___test for cuDF
  tests/series_only/__iter___test.py
Labels: internal

#1102 chore: Refactor validate_column_comparand
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
Labels: internal

#1030 fix: Specialize typing in `dataframe` between `Frame` and `DataFrame`
  narwhals/dataframe.py
  narwhals/typing.py
Labels: fix

#1109 docs: assorted docs updates
  README.md
  docs/css/mkdocstrings.css
  docs/extending.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#1110 release: Bump version to 1.9.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1114 docs: fix some docs issues
  docs/installation.md
  narwhals/stable/v1/__init__.py
Labels: documentation

#1113 test: xfail empty string test in `test_unpivot`
  tests/frame/unpivot_test.py
Labels: internal

#1115 docs: correct python bytes description
  README.md
Labels: documentation

#1123 fix: Fix `DataFrame.__getitem__` when slicing with tuple and null slice
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  tests/frame/getitem_test.py
Labels: fix

#1124 feat: add `nulls_last` kw in dataframe sort
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/sort_test.py
Labels: enhancement

#1118 test: xfail tz_aware test for cuDF
  tests/expr_and_series/cast_test.py
  tests/frame/unpivot_test.py
Labels: internal

#1129 test: xfail test_actual_object for cuDF
  tests/frame/schema_test.py
Labels: internal

#1126 docs: add Ibis to "related projects"
  docs/roadmap_and_related.md
Labels: documentation

#1132 ci: add py-shiny to downstream tests
  .github/workflows/downstream_tests.yml
Labels: internal

#1134 release: Bump version to 1.9.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1082 fix: fixing unnesscary raise of mean_horizontal
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/namespace.py
  tests/expr_and_series/mean_horizontal_test.py
Labels: fix

#1141 docs: fix small docs typo
  docs/backcompat.md
Labels: documentation

#1138 fix: update no_agg to work with cuDF
  narwhals/_pandas_like/group_by.py
Labels: fix

#1140 fix: pyarrow unpivot upcast numeric
  narwhals/_arrow/dataframe.py
  tests/frame/unpivot_test.py
Labels: fix, pyarrow

#1137 fix: when-then-otherwise lit string for arrow backend
  narwhals/_arrow/namespace.py
  tests/expr_and_series/when_test.py
Labels: fix, pyarrow

#1136 feat: allow inspecting the inner type / length of nw.Array
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  tests/dtypes_test.py
  tests/frame/schema_test.py
Labels: enhancement

#1128 feat: `concat_str`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/namespace.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/concat_str_test.py
Labels: enhancement, high priority

#993 perf: Impove `pandas`-backend indexing
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
Labels: performance

#1143 docs: add missing Series str methods in api reference
  docs/api-reference/series_str.md
  utils/check_api_reference.py
Labels: documentation

#1144 docs: add missing methods in api reference
  utils/check_api_reference.py
Labels: documentation

#1145 feat: allow `format=None` in `str.to_datetime`
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement

#1150 docs: apply further changes to api reference
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  utils/check_api_reference.py
Labels: documentation

#1153 test: xfail test_unpivot_mixed_types for cuDF
  tests/frame/unpivot_test.py
Labels: internal

#1142 feat: add dt.replace_time_zone
  .github/workflows/pytest.yml
  docs/api-reference/expr_dt.md
  docs/api-reference/series_dt.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/convert_time_zone_test.py
  tests/expr_and_series/replace_time_zone_test.py
Labels: enhancement

#1156 release: Bump version to 1.9.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
  tests/expr_and_series/convert_time_zone_test.py
Labels: release

#1157 docs: separate out DataFrame and LazyFrame in api-completeness
  mkdocs.yml
  utils/generate_backend_completeness.py
Labels: documentation

#1159 fix: make Series.scatter always return new series
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  tests/series_only/scatter_test.py
Labels: fix

#1155 enh: Add `.rows(named=False)` support for pyarrow
  narwhals/_arrow/dataframe.py
  tests/frame/rows_test.py
Labels: enhancement

#1164 release: Bump version to 1.9.3
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1161 chore: Use shiny's Makefile to allow for test commands to change over time
  .github/workflows/downstream_tests.yml
Labels: internal

#1148 feat: add `<min|max>_horizontal`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/max_horizontal_test.py
  tests/expr_and_series/min_horizontal_test.py
Labels: enhancement

#1168 feat: add The Zen of Narwhals
  narwhals/this.py
  pyproject.toml
Labels: enhancement

#1171 ci: try fixup bump-version.yml
  .github/workflows/bump-version.yml
Labels: internal

#1172 fix: add `__native_namespace__` for interchange support dataframes
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_interchange/dataframe.py
  narwhals/_interchange/series.py
  tests/frame/interchange_native_namespace_test.py
Labels: fix

#1174 test: unxfail test_unary for dask
  tests/expr_and_series/unary_test.py
Labels: internal

#1166 ci: add downstream tests for `marimo`
  .github/workflows/downstream_tests.yml
Labels: internal

#1189 ci: only check doctests on Python3.12
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/schema.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
Labels: internal

#1196 test: update cuDF tests
  tests/expr_and_series/convert_time_zone_test.py
  tests/expr_and_series/replace_time_zone_test.py
  tests/series_only/to_dummy_test.py
Labels: internal

#1192 feat: Adding allow inspecting inner fields of nw.Struct
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/stable/v1/dtypes.py
  narwhals/stable/v1/typing.py
  narwhals/typing.py
  tests/dtypes_test.py
  tests/frame/schema_test.py
  utils/check_api_reference.py
Labels: enhancement

#1197 docs: Update CONTRIBUTING.md with Python 3.12
  CONTRIBUTING.md
Labels: documentation

#991 feat: Add 'IntoSeries'
  .github/workflows/extremes.yml
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/typing.py
  narwhals/translate.py
  narwhals/typing.py
Labels: enhancement

#1181 feat: add from_arrow (which uses the PyCapsule Interface)
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/from_pycapsule_test.py
Labels: enhancement

#1201 fix: preserve dtypes when using with_columns and length-1 pandas df
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  tests/frame/with_columns_test.py
Labels: fix

#1203 release: Bump version to 1.9.4
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1208 docs: add 'commotion' to Zen
  narwhals/this.py
Labels: documentation

#1186 fix: Add df`.rows(named=False)` support for cuDF data frames
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/rows_test.py
Labels: fix

#1209 test: xfail iter_rows tests for cudf
  tests/frame/rows_test.py
Labels: internal

#1207 docs: Add Pyarrow example to Expr.mean
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1169 doc: Add uv to quick start
  docs/installation.md
Labels: documentation

#1213 docs: move index to start of API reference
  mkdocs.yml
Labels: documentation

#1217 perf: move `maybe_evaluate_expr` out of for loop in `reuse_series_implementation`
  narwhals/_expression_parsing.py
Labels: performance

#1210 chore: use constructors
  tests/expr_and_series/str/contains_test.py
  tests/series_only/cast_test.py
Labels: internal

#1221 docs: update installation.md
  docs/installation.md
Labels: documentation

#1222 chore: nox doctests only in Python 3.12
  narwhals/dataframe.py
  noxfile.py
Labels: internal

#1194 feat: add to_py_scalar
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/dependencies.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  tests/translate/to_py_scalar_test.py
Labels: enhancement

#1227 doc: add note about cuDF tests in contributing guide
  CONTRIBUTING.md
Labels: documentation

#1231 fix: flaky test on polars==0.20.30
  narwhals/_polars/dataframe.py
  narwhals/_polars/utils.py
Labels: fix

#1232 chore: series and expr namespaces typing with generics
  narwhals/expr.py
  narwhals/series.py
Labels: internal

#1218 docs: Pyarrow example docstrings for `Expr` and stable v1 API
  narwhals/expr.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1220 enh: add dt.timestamp
  docs/api-reference/expr_dt.md
  docs/api-reference/series_dt.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/dt/datetime_attributes_test.py
  tests/expr_and_series/dt/timestamp_test.py
Labels: enhancement

#1234 release: Bump version to 1.10.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1235 chore: make module versions as constants for use in tests
  tests/conftest.py
  tests/dtypes_test.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/cat/get_categories_test.py
  tests/expr_and_series/convert_time_zone_test.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/dt/datetime_duration_test.py
  tests/expr_and_series/dt/ordinal_day_test.py
  tests/expr_and_series/dt/timestamp_test.py
  tests/expr_and_series/dt/total_minutes_test.py
  tests/expr_and_series/mode_test.py
  tests/expr_and_series/nth_test.py
  tests/expr_and_series/replace_time_zone_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/frame/array_dunder_test.py
  tests/frame/arrow_c_stream_test.py
  tests/frame/drop_test.py
  tests/frame/interchange_schema_test.py
  tests/frame/interchange_to_pandas_test.py
  tests/frame/invalid_test.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
  tests/frame/to_arrow_test.py
  tests/frame/to_pandas_test.py
  tests/frame/unpivot_test.py
  tests/frame/with_columns_test.py
  tests/frame/write_parquet_test.py
  tests/from_pycapsule_test.py
  tests/group_by_test.py
  tests/hypothesis/join_test.py
  tests/selectors_test.py
  tests/series_only/array_dunder_test.py
  tests/series_only/arrow_c_stream_test.py
  tests/series_only/cast_test.py
  tests/series_only/is_ordered_categorical_test.py
  tests/series_only/to_pandas_test.py
  tests/series_only/value_counts_test.py
  tests/tpch_q1_test.py
  tests/utils.py
  tests/utils_test.py
Labels: internal

#1211 ci: add tubular in ci checks
  .github/workflows/downstream_tests.yml
  README.md
Labels: internal

#1242 docs: Wimsey added to project list in Readme
  README.md
Labels: documentation

#1243 docs: zen dedicated doc page
  .gitignore
  mkdocs.yml
  utils/generate_zen_content.py
Labels: documentation

#1246 perf: pandas-like fastpath in maybe_reset_index
  narwhals/utils.py
  tests/utils_test.py
Labels: performance

#1247 perf: always use copy=False when doing rename for pandas
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
Labels: performance

#1248 test: only test dask with partitions=2 for now
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  tests/conftest.py
Labels: internal

#1251 docs: fix parameters table rendering in `quantile` docs
  narwhals/expr.py
  narwhals/series.py
Labels: documentation

#1253 test: get groupby tests passing for pandas 1.0.x
  narwhals/_pandas_like/group_by.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/schema_test.py
  tests/group_by_test.py
Labels: internal

#1252 perf: avoid redundant copies when resetting index for pandas
  narwhals/_pandas_like/group_by.py
Labels: performance

#1257 feat: add drop_null_keys argument to group_by
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/group_by.py
  narwhals/dataframe.py
  narwhals/group_by.py
  tests/group_by_test.py
Labels: enhancement

#1188 feat: Add total seconds implementation for cuDF
  narwhals/_pandas_like/series.py
  tests/expr_and_series/dt/datetime_duration_test.py
Labels: enhancement

#1255 perf: improve performance of Series.dtype and DataFrame.schema for pandas-like
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/series.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/unpivot_test.py
Labels: performance

#1259 test: xfail cudf failures
  tests/frame/unpivot_test.py
  tests/group_by_test.py
Labels: internal

#1261 docs: add duckdb to docs
  docs/requirements-docs.txt
Labels: documentation

#1262 release: Bump version to 1.11.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1264 feat: expose `generate_temporary_column_name`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#1265 fix: Cudf groupby iter
  narwhals/_pandas_like/group_by.py
  tests/group_by_test.py
Labels: fix

#1268 fix: remove _dtype_cache for pandas-like so that inplace modification…
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  tests/dtypes_test.py
Labels: fix

#1270 feat: better error message for duplicate column names in pandas
  narwhals/_pandas_like/dataframe.py
  tests/translate/from_native_test.py
Labels: enhancement

#1271 release: Bump version to 1.11.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1094 ci: test with python3.13
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
Labels: internal

#1272 feat: add is_pandas_index, is_modin_index, is_cudf_index, is_pandas_like_index utility functions
  docs/api-reference/dependencies.md
  narwhals/dependencies.py
  tests/dependencies/is_pandas_index_test.py
Labels: enhancement

#1275 docs: Render table of contents members ordered & removed css reference
  mkdocs.yml
Labels: documentation

#1195 RFC, feat: infer datetime format for pyarrow backend
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement, high priority

#1283 feat: support `columns` and `select` for InterchangeFrame if `_df` is present
  narwhals/_interchange/dataframe.py
  tests/frame/interchange_schema_test.py
  tests/frame/interchange_select_test.py
Labels: enhancement

#1284 release: Bump version to 1.12.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1281 ci: set pre-commit autoupdate to run monthly instead of weekly
  .github/dependabot.yml
  .pre-commit-config.yaml
Labels: internal

#1286 ci: add marimo tests back
  .github/workflows/downstream_tests.yml
Labels: internal
