Repository narwhals-dev/narwhals, pull requests merged in 2024-09, with the labels that each got.

#808 docs: docstring for `concat`
  narwhals/functions.py
  narwhals/stable/v1.py
Labels: documentation

#894 feat: Add q6 of tpch
  tpch/execute/q6.py
  tpch/queries/q6.py
Labels: enhancement

#895 docs: fix error in `write_csv` docstring
  narwhals/dataframe.py
Labels: documentation

#900 chore: clean up gitignore
  .gitignore
Labels: internal

#901 feat: Better ibis interchange
  .github/workflows/pytest.yml
  docs/api-reference/dependencies.md
  narwhals/_ibis/__init__.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_interchange/dataframe.py
  narwhals/dependencies.py
  narwhals/translate.py
  pyproject.toml
  tests/frame/interchange_schema_test.py
  tests/no_imports_test.py
Labels: enhancement

#902 feat: Duckdb interchange
  narwhals/_duckdb/__init__.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/dependencies.py
  narwhals/translate.py
  requirements-dev.txt
  tests/frame/interchange_schema_test.py
Labels: enhancement

#903 release: Bump version to 1.6.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#904 fix: use nw.Unknown for unknown dtypes
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  tests/frame/interchange_schema_test.py
Labels: fix

#906 fix: compatiblity with Python3.8 for Ibis
  .github/workflows/pytest.yml
  narwhals/dependencies.py
  tests/frame/arrow_c_stream_test.py
  tests/frame/interchange_schema_test.py
  tests/series_only/arrow_c_stream_test.py
Labels: fix

#907 release: Bump version to 1.6.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#899 ci: add tests for the queries of TPC-H
  .github/workflows/check_tpch_queries.yml
  pyproject.toml
  requirements-dev.txt
  tpch/tests/__init__.py
  tpch/tests/test_queries.py
Labels: internal, full-test

#909 feat: dask lit with dtype
  narwhals/_dask/namespace.py
  tests/frame/lit_test.py
Labels: enhancement

#912 test: xfail `dt.date` tests for cuDF
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: internal

#911 feat: Add join_asof support for pandas and dask
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement

#916 feat: enable `on` key in `join_asof`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement

#918 test: fixup tpch tests
  .github/workflows/check_tpch_queries.yml
  tpch/__init__.py
  tpch/execute/q10.py
  tpch/execute/q11.py
  tpch/execute/q15.py
  tpch/execute/q17.py
  tpch/execute/q18.py
  tpch/execute/q3.py
  tpch/execute/q4.py
  tpch/execute/q5.py
  tpch/execute/q6.py
  tpch/execute/q7.py
  tpch/execute/q9.py
  tpch/generate_data.py
  tpch/tests/test_queries.py
Labels: internal, full-test

#910 feat: Add q12, q13, q14, q16, q22
  tpch/execute/q12.py
  tpch/execute/q13.py
  tpch/execute/q14.py
  tpch/execute/q16.py
  tpch/execute/q22.py
  tpch/queries/q12.py
  tpch/queries/q13.py
  tpch/queries/q14.py
  tpch/queries/q16.py
  tpch/queries/q22.py
Labels: enhancement, full-test

#873 docs: Recommend `uv` in contributing guide
  CONTRIBUTING.md
Labels: documentation

#921 feat: enable `by` argument in `join_asof`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement

#922 feat: add q8 of tpch
  tpch/execute/q8.py
  tpch/queries/q8.py
Labels: enhancement, full-test

#925 docs: fix a typo
  docs/why.md
Labels: documentation

#923 fix: Fixes arrow support for df[:, list[int|str]]
  narwhals/_arrow/dataframe.py
  narwhals/dataframe.py
  narwhals/stable/v1.py
  tests/frame/slice_test.py
Labels: fix

#926 release: Bump version to 1.6.3
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#927 feat: add `on` key to `join`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement

#924 feat: implement `to_arrow` for cuDF
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
Labels: enhancement, internal

#928 doc: update drop_nulls for series documentation
  narwhals/series.py
Labels: documentation

#930 fix: fix join when using string literals
  narwhals/_pandas_like/dataframe.py
  tests/frame/join_test.py
Labels: fix, full-test

#931 chore: pyarrow group by refactor
  narwhals/_arrow/group_by.py
Labels: internal

#932 release: Bump version to 1.6.4
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#933 test: always run tpch tests
  .github/workflows/check_tpch_queries.yml
  tpch/execute/q10.py
  tpch/execute/q11.py
  tpch/execute/q12.py
  tpch/execute/q13.py
  tpch/execute/q14.py
  tpch/execute/q15.py
  tpch/execute/q16.py
  tpch/execute/q17.py
  tpch/execute/q18.py
  tpch/execute/q19.py
  tpch/execute/q20.py
  tpch/execute/q21.py
  tpch/execute/q22.py
  tpch/execute/q3.py
  tpch/execute/q4.py
  tpch/execute/q5.py
  tpch/execute/q6.py
  tpch/execute/q7.py
  tpch/execute/q8.py
  tpch/execute/q9.py
  tpch/queries/q17.py
  tpch/queries/q8.py
Labels: internal

#934 feat: join suffix parameter
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement

#938 docs: fix docstring formatting on `maybe_align_index`
  narwhals/stable/v1.py
  narwhals/utils.py
Labels: documentation

#937 fix: Update `copy` param on `to_numpy` to default to `True` for cuDF
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
Labels: fix

#939 chore: ban dask filtering with boolean mask
  narwhals/_dask/dataframe.py
  tests/frame/filter_test.py
Labels: internal

#941 docs: add `appears on` section with links to relevant podcasts/blogs
  README.md
Labels: documentation

#946 doc: update docstrings to fix rendering in generated docs
  narwhals/expr.py
  narwhals/series.py
Labels: documentation

#945 test: xfail `to_dummies` with `drop_first` test for cuDF
  tests/series_only/to_dummy_test.py
Labels: internal

#944 fix: group by no aggregation
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/group_by.py
  tests/test_group_by.py
Labels: fix

#942 feat: add `mode` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/mode_test.py
Labels: enhancement

#948 feat: add Series.Scatter
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
  tests/series_only/scatter_test.py
  utils/check_api_reference.py
Labels: enhancement

#950 release: Bump version to 1.7.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#952 docs: update docstring to fix rendering in generated docs
  narwhals/dataframe.py
Labels: documentation

#951 test: xfail cuDF tests that use `total_seconds`
  tests/expr_and_series/dt/datetime_duration_test.py
Labels: internal

#953 test: xfail polars>1.7.0 `Expr.mode` with broadcast
  tests/expr_and_series/mode_test.py
Labels: internal

#954 ci: unxfail some modin tests
  .github/workflows/check_tpch_queries.yml
  narwhals/dataframe.py
  narwhals/expr.py
  pyproject.toml
  tests/expr_and_series/dt/to_string_test.py
Labels: internal

#959 test: xfail cuDF tests for `join_asof`
  tests/frame/join_test.py
Labels: internal

#961 test: replace `Any` type with `pytest.FixtureRequest` for `request` inputs in all tests
  tests/conftest.py
  tests/expr_and_series/arg_true_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/cat/get_categories_test.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/drop_nulls_test.py
  tests/expr_and_series/dt/datetime_attributes_test.py
  tests/expr_and_series/dt/datetime_duration_test.py
  tests/expr_and_series/filter_test.py
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/head_test.py
  tests/expr_and_series/len_test.py
  tests/expr_and_series/mode_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/quantile_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/expr_and_series/tail_test.py
  tests/expr_and_series/unary_test.py
  tests/expr_and_series/unique_test.py
  tests/expr_and_series/when_test.py
  tests/frame/array_dunder_test.py
  tests/frame/clone_test.py
  tests/frame/drop_test.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
  tests/frame/slice_test.py
  tests/frame/to_arrow_test.py
  tests/frame/to_pandas_test.py
  tests/frame/with_columns_sequence_test.py
  tests/from_dict_test.py
  tests/selectors_test.py
  tests/series_only/array_dunder_test.py
  tests/series_only/to_arrow_test.py
  tests/series_only/to_dummy_test.py
  tests/series_only/to_list_test.py
  tests/series_only/to_numpy_test.py
  tests/series_only/to_pandas_test.py
  tests/series_only/value_counts_test.py
  tests/test_group_by.py
  tests/tpch_q1_test.py
Labels: internal

#963 release: Bump version to 1.8.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#956 ci: enable uv cache, use astral-sh official action
  .github/workflows/check_docs_build.yml
  .github/workflows/check_tpch_queries.yml
  .github/workflows/downstream_tests.yml
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
Labels: internal

#965 ci: only run nightlies on pushes to main
  .github/workflows/extremes.yml
Labels: internal

#966 ci: fixup nightlies
  .github/workflows/extremes.yml
Labels: internal

#967 test: xfail cuDF tests that use iteration
  narwhals/dataframe.py
  tests/frame/row_test.py
  tests/frame/rows_test.py
Labels: internal

#970 chore: some TODO's cleanup
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/translate.py
Labels: internal

#974 feat: add seed to `Expr|Series.sample`
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/sample_test.py
Labels: enhancement

#975 feat: add `DataFrame.sample` method
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/sample_test.py
Labels: enhancement

#976 test: remove xfail for cudf_constructor on `str_to_uppercase` test
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
Labels: internal

#979 release: Bump version to 1.8.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#986 test: add tests to check case sensitive regex for str.contains
  tests/expr_and_series/str/contains_test.py
Labels: internal

#987 test: convert cuDF numpy types to python types in tests
  tests/utils.py
Labels: internal

#996 docs: Fix link to how Narwhals works
  CONTRIBUTING.md
Labels: documentation

#1007 docs: Restructure docs a bit
  docs/api-reference/index.md
  docs/extending.md
  docs/installation.md
  docs/levels.md
  docs/quick_start.md
  docs/related.md
  docs/roadmap.md
  docs/roadmap_and_related.md
  mkdocs.yml
Labels: documentation

#1009 release: Bump version to 1.8.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1012 chore: removing docs/generate_members.py
  docs/generate_members.py
Labels: internal

#1017 docs: add pycapsule interface to related projects #1011
  docs/roadmap_and_related.md
Labels: documentation

#1023 docs: Add pyarrow example to Installation guide
  docs/installation.md
Labels: documentation

#1018 docstrings pyarrow support for dataframe.to_pandas()
  narwhals/dataframe.py
Labels: documentation

#1020 feat: adding to_native to Series
  docs/api-reference/series.md
  narwhals/series.py
  narwhals/stable/v1.py
  tests/series_only/to_native_test.py
  utils/check_api_reference.py
Labels: enhancement

#1016 docs: include PyArrow in Tutorial/DataFrame
  docs/basics/dataframe.md
Labels: documentation

#1029 fix: package dependency added pyarrow in docs
  .github/workflows/mkdocs.yml
Labels: fix

#1031 docs: Update contributing guidelines
  .gitignore
  CONTRIBUTING.md
Labels: documentation

#1021 docs: Add DataFrame.pipe to API completeness table
  utils/generate_backend_completeness.py
Labels: documentation

#995 test: add specific check for cuDF for test_to_datetime
  tests/expr_and_series/str/to_datetime_test.py
Labels: internal

#983 docs: add dtypes check in `utils/check_api_reference.py`
  docs/api-reference/dtypes.md
  utils/check_api_reference.py
Labels: documentation

#1033 docs: add pyarrow example for dataframe getitem and to_dict
  narwhals/dataframe.py
  narwhals/stable/v1.py
Labels: documentation

#1014 feat: adding to_native to dataframe
  docs/api-reference/dataframe.md
  narwhals/dataframe.py
  tests/frame/to_native_test.py
Labels: enhancement

#1034 perf: low-hanging overhead
  narwhals/_arrow/selectors.py
  narwhals/_arrow/utils.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/utils.py
  narwhals/translate.py
  narwhals/utils.py
Labels: performance

#1035 fix: generate backend table
  utils/generate_backend_completeness.py
Labels: fix

#1019 test: use pytest-randomly, recommend pytest-xdist in docs
  CONTRIBUTING.md
  requirements-dev.txt
Labels: performance, internal

#1026 fix: tuple supported for getitem for Pandas dataframes
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  tests/frame/getitem_test.py
Labels: fix

#1036 feat: add `str.len_chars`
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/str/len_chars_test.py
Labels: enhancement

#1038 feat: improve Series repr
  narwhals/series.py
Labels: enhancement

#1039 test: xfail `test_group_by_n_unique_w_missing` for cuDF
  tests/test_group_by.py
Labels: internal

#1041 fix: add cuDF specific implementation for join how="anti"
  narwhals/_pandas_like/dataframe.py
Labels: internal, fix

#1049 feat: add `Series.dtype` return annotation
  narwhals/_arrow/series.py
  narwhals/_interchange/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
Labels: enhancement

#1053 fix: move `__len__` to `DataFrame` only
  narwhals/dataframe.py
  tests/frame/len_test.py
Labels: fix

#1057 feat: add `Series.__iter__`
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
  tests/series_only/__iter___test.py
  utils/check_api_reference.py
Labels: enhancement

#1058 release: Bump version to 1.9.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1059 release: Bump version to 1.9.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1060 ci: improve release process so it fails early
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
  utils/bump_version.py
Labels: internal

#1061 release: Bump version to 1.8.3
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1062 ci: delete all local tags before making release
  utils/bump_version.py
Labels: internal

#1069 build: Added PR labels so the Release Drafter ignores evil bots
  .github/release-drafter.yml
Labels: build

#1056 fix: add cuDF specific implementation for join how="anti"
  narwhals/_pandas_like/dataframe.py
Labels: fix

#1044 feat: Adding nth() for selecting columns
  docs/api-reference/narwhals.md
  docs/requirements-docs.txt
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/namespace.py
  narwhals/expr.py
  narwhals/stable/v1.py
  tests/expr_and_series/nth_test.py
Labels: enhancement

#1073 feat: add `series.rename`
  docs/api-reference/series.md
  narwhals/series.py
  tests/series_only/alias_rename_test.py
  utils/check_api_reference.py
Labels: enhancement

#1079 fix: pandas and dask group by `observed=True`
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/group_by.py
  tests/test_group_by.py
Labels: fix

#1075 fix: fixing `nw.all()` doesn't work in sum_horizontal
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
  narwhals/expr.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/any_horizontal_test.py
  tests/expr_and_series/sum_horizontal_test.py
Labels: fix

#1074 chore: `get_<dependency>` cleanup
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/series.py
  narwhals/utils.py
Labels: internal

#1066 feat: add `to_pandas` and `to_arrow` for interchange level of support
  .github/workflows/pytest.yml
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  noxfile.py
  tests/frame/interchange_to_arrow_test.py
  tests/frame/interchange_to_pandas_test.py
Labels: enhancement

#1043 feat: add `DataFrame|LazyFrame.unpivot` method
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  tests/frame/unpivot_test.py
Labels: enhancement, high priority

#1083 feat: Initial support for nested dtypes (List, Array, Struct)
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/stable/v1.py
  tests/frame/schema_test.py
Labels: enhancement

#1084 release: Bump version to 1.8.4
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1055 docs: add pyarrow to dataframe lazy docstring
  narwhals/dataframe.py
  narwhals/stable/v1.py
Labels: documentation

#1086 fix: make `narwhalify` part of stable api
  narwhals/_dask/dataframe.py
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/frame/lazy_test.py
  tests/stable_api_test.py
Labels: fix

#1089 chore: rename translate_dtype to native_to_narwhals_dtype
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal

#1090 fix: `drop_nulls` with subset of length>1
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
  tests/frame/drop_nulls_test.py
Labels: fix

#1085 docs: Added new logo
  docs/assets/logo.svg
  docs/css/mkdocstrings.css
  mkdocs.yml
Labels: documentation

#1092 test: `xfail` test using None on `to_numpy` for cuDF
  tests/series_only/to_numpy_test.py
Labels: internal

#1087 feat: add dtypes to stable api
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_interchange/dataframe.py
  narwhals/_interchange/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/dtypes.py
  narwhals/translate.py
  narwhals/typing.py
  narwhals/utils.py
  tests/from_dict_test.py
  tests/new_series_test.py
  tests/stable_api_test.py
Labels: enhancement

#960 feat: `Datetime(time_unit, time_zone)` and `Duration(time_unit)` types
  .github/workflows/extremes.yml
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/functions.py
  narwhals/stable/v1/dtypes.py
  tests/dtypes_test.py
  tests/expr_and_series/cast_test.py
  tests/series_only/cast_test.py
  tests/stable_api_test.py
  utils/check_api_reference.py
Labels: enhancement

#1097 doc: add pyarrow to DataFrame docstring
  narwhals/dataframe.py
Labels: documentation

#1099 fix: `PandasLikeSeries.zip_with` scalar value and `DaskNamespace.when`
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/series.py
  tests/expr_and_series/when_test.py
  tests/series_only/zip_with_test.py
Labels: fix

#1095 feat: add `maybe_reset_index` for pandas-like dataframe or series
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#1100 test: allow cuDF series in compare_dicts
  tests/utils.py
Labels: internal
