Repository narwhals-dev/narwhals, pull requests merged in 2024-08, with the labels that each got.

#687 docs: fix todo, avoid lazyframe collect_schema warning
  docs/basics/complete_example.md
  docs/basics/dataframe.md
Labels: documentation

#688 feat: dask `schema` and `collect_schema`
  narwhals/_dask/dataframe.py
  tests/dask_test.py
Labels: enhancement

#703 chore: moving most dask tests over to the main test suite
  narwhals/_dask/expr.py
  tests/dask_test.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/is_between_test.py
  tests/expr_and_series/str/contains_test.py
  tests/frame/select_test.py
Labels: internal

#705 chore: remove dask_test completely
  tests/dask_test.py
  tests/expr_and_series/str/head_test.py
  tests/expr_and_series/str/slice_test.py
  tests/expr_and_series/str/starts_with_ends_with_test.py
  tests/expr_and_series/str/tail_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
Labels: internal

#693 feat: dask `any_horizontal` and generalize `all_horizontal`
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/any_horizontal_test.py
  tests/expr_and_series/operators_test.py
Labels: enhancement

#706 docs: Contributing guide correction
  CONTRIBUTING.md
Labels: documentation

#707 docs: correction of `how_it_works.md`
  docs/how_it_works.md
Labels: documentation

#696 feat: add `round` to Arrow
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/round_test.py
Labels: enhancement

#710 docs: Fix how-it-works, add favicon+logo
  docs/how_it_works.md
  mkdocs.yml
Labels: documentation

#708 feat: dask equality and inequality operators
  narwhals/_dask/expr.py
  tests/expr_and_series/operators_test.py
Labels: enhancement

#720 chore: Factor all remaining tests out of `test_common.py`
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/null_test.py
  tests/frame/columns_test.py
  tests/frame/invalid_test.py
  tests/frame/lazy_test.py
  tests/frame/reindex_test.py
  tests/frame/test_common.py
  tests/frame/with_columns_test.py
Labels: internal

#719 docs: how it works bulletpoint indentation
  docs/how_it_works.md
Labels: documentation

#692 feat: dask `with_row_index` and `rename`
  narwhals/_dask/dataframe.py
  tests/frame/rename_test.py
  tests/frame/with_row_index_test.py
Labels: enhancement

#721 feat: arrow expr `over` method
  narwhals/_arrow/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#717 feat: `ArrowGroupBy.__iter__` method
  narwhals/_arrow/group_by.py
  tests/test_group_by.py
Labels: enhancement

#715 feat: add `strip_chars` to string namespace
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/str/strip_chars_test.py
Labels: enhancement

#716 patch: pandas-like and pyarrow scalar reduction fix
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/reduction_test.py
Labels: fix

#724 perf: only use as_py for pyarrow when necessary (before pyarrow 13)
  narwhals/_arrow/utils.py
Labels: performance

#709 feat: Add `Expr.round` to Dask
  narwhals/_dask/expr.py
  tests/expr_and_series/round_test.py
Labels: enhancement

#701 feat: add series and expr `clip` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/clip_test.py
Labels: enhancement

#718 feat: add `group_by` to dask
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  pyproject.toml
  tests/test_group_by.py
Labels: enhancement

#725 feat: DaskLazyFrame `join` and `sort`, DaskNamespace `all`
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  tests/expr_and_series/double_selected_test.py
  tests/expr_and_series/double_test.py
  tests/frame/double_test.py
  tests/frame/join_test.py
  tests/frame/sort_test.py
Labels: enhancement

#726 feat: DaskLazyFrame `unique` method
  narwhals/_dask/dataframe.py
  tests/frame/unique_test.py
Labels: enhancement

#723 feat: support reductions in lazyframe.select for Dask
  .pre-commit-config.yaml
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  pyproject.toml
  tests/expr_and_series/max_test.py
  tests/expr_and_series/mean_test.py
  tests/expr_and_series/min_test.py
  tests/expr_and_series/reduction_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/expr_and_series/sum_all_test.py
  tests/expr_and_series/sum_test.py
  tests/frame/series_sum_test.py
  tests/test_group_by.py
Labels: enhancement

#733 test: improve coverage for `from_native` (dask)
  narwhals/translate.py
  tests/translate/from_native_test.py
Labels: internal

#736 ci: fix ci from pytest importerror
  tests/translate/from_native_test.py
Labels: internal

#734 feat: add dask `Expr.std`
  narwhals/_dask/expr.py
  tests/expr_and_series/std_test.py
Labels: enhancement

#729 feat: arrow and dask expr `clip` method
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/clip_test.py
Labels: enhancement

#738 release: Bump version to 1.2.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#740 feat: dask expr dunder methods
  narwhals/_dask/expr.py
  tests/expr_and_series/arithmetic_test.py
Labels: enhancement

#713 feat: add `date` to datetime namespace
  docs/api-reference/expr_dt.md
  docs/api-reference/series_dt.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: enhancement

#735 feat: dask expr name namespace
  narwhals/_dask/expr.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
Labels: enhancement

#731 feat: add Dask `Expr.count`
  narwhals/_dask/expr.py
  tests/expr_and_series/count_test.py
Labels: enhancement

#728 feat: Added `Expr.abs` to Dask
  narwhals/_dask/expr.py
  tests/expr_and_series/abs_test.py
Labels: enhancement

#744 feat: add NotImplementedError error for index changing methods Dask
  narwhals/_dask/expr.py
Labels: enhancement

#747 feat: allow tpc-h q1 to be run with Dask as backend
  .pre-commit-config.yaml
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  tests/tpch_q1_test.py
Labels: enhancement

#618 feat: arrow `__mod__` method
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/arithmetic_test.py
  tests/series_only/arithmetic_test.py
Labels: enhancement

#748 feat: Added `Expr.any` and `Expr.all` to Dask
  narwhals/_dask/expr.py
  tests/expr_and_series/any_all_test.py
Labels: enhancement

#749 perf: keep `nw.len` totally lazy for dask
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  tests/expr_and_series/len_test.py
  tests/stable_api_test.py
Labels: performance

#751 release: Bump version to 1.3.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#755 docs: patch `Series.cat` page
  docs/api-reference/series_cat.md
Labels: documentation

#758 docs: use animals instead of cars in example
  narwhals/dataframe.py
  narwhals/stable/v1.py
Labels: documentation

#582 feat: `Series.pipe` and `Expr.pipe`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/pipe_test.py
Labels: enhancement

#759 docs: run tpch q1 with more libraries
  tpch/notebooks/q1/execute.ipynb
Labels: documentation

#762 feat: dask expr `len` method
  narwhals/_dask/expr.py
  tests/expr_and_series/len_test.py
  tests/test_group_by.py
Labels: enhancement

#763 feat: dask expr `__invert__`, `is_null`, `n_unique` methods
  narwhals/_dask/expr.py
  tests/expr_and_series/is_null_test.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/null_test.py
Labels: enhancement

#764 feat: dask expr `is_first|last_distinct` methods
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/utils.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
Labels: enhancement

#765 perf: remove some lambdas from _dask backend
  narwhals/_dask/dataframe.py
Labels: performance

#757 fix: empty with_columns not working for pandas backend
  narwhals/_pandas_like/dataframe.py
  tests/frame/with_columns_test.py
Labels: fix

#766 chore: tests series_only refactor
  tests/expr_and_series/arg_true_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/drop_nulls_test.py
  tests/expr_and_series/is_in_test.py
  tests/expr_and_series/len_test.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  tests/expr_and_series/null_count_test.py
  tests/expr_and_series/operators_test.py
  tests/expr_and_series/pipe_test.py
  tests/expr_and_series/unary_test.py
  tests/frame/get_column_test.py
  tests/series_only/arithmetic_test.py
  tests/series_only/dtype_test.py
  tests/series_only/head_test.py
  tests/series_only/is_between_test.py
  tests/series_only/item_test.py
  tests/series_only/null_count_test.py
  tests/series_only/operators_test.py
  tests/series_only/tail_test.py
  tests/series_only/test_common.py
  tests/series_only/to_numpy_test.py
  tests/series_only/to_pandas_test.py
  tests/series_only/zip_with_test.py
Labels: internal

#769 feat: series `to_arrow` method
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
  tests/series_only/to_arrow_test.py
  utils/check_api_reference.py
Labels: enhancement

#770 feat: dataframe `to_arrow` method
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/to_arrow_test.py
Labels: enhancement

#771 feat: `DaskSelectorNamespace`
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  tests/test_selectors.py
Labels: enhancement

#772 feat: dask namespace `lit` method
  narwhals/_dask/namespace.py
  tests/frame/lit_test.py
Labels: enhancement

#774 docs: include "downloads per month" in readme
  README.md
Labels: documentation

#776 docs: add Altair to "used by" section
  README.md
Labels: documentation

#777 chore: simplify Expr.clip
  narwhals/expr.py
Labels: internal

#775 feat: dask `sum_horizontal`
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/test_selectors.py
Labels: enhancement

#778 feat: dask lazyframe remaining methods
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  tests/expr_and_series/tail_test.py
  tests/frame/gather_every_test.py
  tests/frame/tail_test.py
  tests/series_only/tail_test.py
Labels: enhancement

#750 feat: add `str.replace` and `str.replace_all`
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/str/replace_test.py
Labels: enhancement

#768 feat: implement LazyFrame.head for Dask (plus: run tpc-h q2 query with Dask present)
  .github/workflows/extremes.yml
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  pyproject.toml
  tests/expr_and_series/head_test.py
  tests/frame/head_test.py
  tests/series_only/head_test.py
  tpch/notebooks/gpu/execute.ipynb
  tpch/notebooks/q10/execute.ipynb
  tpch/notebooks/q11/execute.ipynb
  tpch/notebooks/q15/execute.ipynb
  tpch/notebooks/q17/execute.ipynb
  tpch/notebooks/q18/execute.ipynb
  tpch/notebooks/q19/execute.ipynb
  tpch/notebooks/q2/execute.ipynb
  tpch/notebooks/q20/execute.ipynb
  tpch/notebooks/q21/execute.ipynb
  tpch/notebooks/q3/execute.ipynb
  tpch/notebooks/q4/execute.ipynb
  tpch/notebooks/q5/execute.ipynb
  tpch/notebooks/q6/execute.ipynb
  tpch/notebooks/q7/execute.ipynb
  tpch/notebooks/q8/execute.ipynb
  tpch/notebooks/q9/execute.ipynb
Labels: enhancement

#779 feat: extend dataframe `drop_nulls` method
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/drop_nulls_test.py
Labels: enhancement

#760 feat: allow `from_dict` to not have native_namespace arg if all inputs are already narwhals Series
  narwhals/functions.py
  narwhals/stable/v1.py
  tests/from_dict_test.py
Labels: enhancement

#781 release: Bump version to 1.4.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#780 chore: rename internal dtype functions
  .github/workflows/publish_to_pypi.yml
  docs/extending.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/selectors.py
  narwhals/series.py
Labels: internal

#785 chore: rename _native_dataframe to _native_frame
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/group_by.py
  narwhals/_polars/namespace.py
  narwhals/_polars/utils.py
  narwhals/translate.py
  narwhals/utils.py
Labels: internal

#773 feat: extend dataframe `drop` method
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_exceptions.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/utils.py
  tests/frame/drop_test.py
Labels: enhancement

#783 feat: improve typing for `to_pandas` / `to_numpy` / `to_arrow`
  .pre-commit-config.yaml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/translate.py
  pyproject.toml
  utils/import_check.py
Labels: enhancement

#786 feat: Support Arrow PyCapsule Interface for export
  docs/api-reference/dataframe.md
  docs/api-reference/series.md
  narwhals/dataframe.py
  narwhals/series.py
  tests/frame/arrow_c_stream_test.py
  tests/series_only/arrow_c_stream_test.py
  utils/check_api_reference.py
Labels: enhancement

#788 chore: import overhaul
  CONTRIBUTING.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  tests/no_imports_test.py
Labels: internal

#787 feat: add narwhals.new_series
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_dask/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1.py
  narwhals/utils.py
  tests/frame/drop_test.py
  tests/new_series_test.py
Labels: enhancement

#790 release: Bump version to 1.4.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#792 feat: add dask `Expr.null_count`
  narwhals/_dask/expr.py
  tests/expr_and_series/null_count_test.py
Labels: enhancement

#793 feat: add `diff()` method to Dask backend
  narwhals/_dask/expr.py
  tests/expr_and_series/diff_test.py
Labels: enhancement

#791 docs: add Narwhals.dependencies to API reference
  docs/api-reference/dependencies.md
  narwhals/dependencies.py
Labels: documentation

#794 fix: cuDF compat
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  tests/frame/schema_test.py
Labels: fix

#795 release: Bump version to 1.4.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#797 test: Add `cudf_constructor` to conftest
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/expr.py
  narwhals/series.py
  requirements-dev.txt
  tests/conftest.py
Labels: internal

#799 chore: stable api `narwhalify` de-duplication
  narwhals/functions.py
  narwhals/stable/v1.py
  narwhals/translate.py
Labels: internal

#798 test: Improve `duration_attribute_tests`
  tests/expr_and_series/dt/datetime_duration_test.py
Labels: internal

#802 feat: add `is_in` to `DaskExpr` and mark `is_duplicated` and `is_unique` as not implemented
  narwhals/_dask/expr.py
  tests/expr_and_series/is_in_test.py
Labels: enhancement

#801 chore: use compare_dict in series tests
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/pipe_test.py
  tests/expr_and_series/round_test.py
  tests/expr_and_series/str/replace_test.py
  tests/expr_and_series/str/slice_test.py
  tests/expr_and_series/str/strip_chars_test.py
  tests/expr_and_series/str/tail_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/frame/get_column_test.py
  tests/frame/slice_test.py
  tests/series_only/to_list_test.py
  tests/series_only/zip_with_test.py
Labels: internal

#803 feat: dask expr `is_unique` & `is_duplicated`
  narwhals/_dask/expr.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
Labels: enhancement

#807 ci: Modified drafter's labeller regex to match titles with uppercase
  .github/release-drafter.yml
Labels: internal

#809 test: Use compare dicts in is_duplicated_test
  tests/expr_and_series/is_duplicated_test.py
Labels: internal

#812 test: Remove some `to_list()`
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/cat/get_categories_test.py
  tests/expr_and_series/is_in_test.py
  tests/frame/to_dict_test.py
Labels: internal

#811 feat: add `DaskExpr.total_minutes`, `total_seconds`, `total_milliseconds`, `total_microseconds`, `total_nanoseconds`
  narwhals/_dask/expr.py
  tests/expr_and_series/dt/datetime_duration_test.py
Labels: enhancement, internal

#796 feat: add `dt.to_string` to `DaskExpr`
  narwhals/_dask/expr.py
  tests/expr_and_series/dt/to_string_test.py
Labels: enhancement, internal

#816 build: Add cudf and modin to deps
  .github/workflows/extremes.yml
  pyproject.toml
  tests/selectors_test.py
Labels: internal, build

#820 test: Remove some `to_numpy`
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/is_unique_test.py
  tests/expr_and_series/unique_test.py
  tests/frame/is_duplicated_test.py
  tests/frame/is_unique_test.py
Labels: internal

#828 feat: allow for non-string columns in `select` for pandas backend
  docs/other/column_names.md
  docs/roadmap.md
  mkdocs.yml
  narwhals/_expression_parsing.py
  tests/frame/select_test.py
Labels: enhancement, internal

#829 fix: improve validate columns
  narwhals/_pandas_like/dataframe.py
  tests/frame/schema_test.py
  tests/test_schema.py
Labels: internal, fix

#826 feat: support dtype and copy in DataFrame.__array__
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  tests/frame/array_dunder_test.py
  tests/frame/to_numpy_test.py
  tests/series_only/array_dunder_test.py
Labels: enhancement, internal

#832 feat: write_csv
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/write_csv_test.py
Labels: enhancement, internal

#810 feat: `DaskExpr.over` method
  narwhals/_dask/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#834 release: Bump version to 1.5.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: internal, release

#837 fix: __array__ for pandas (pyarrow dtypes) was raising for old versions of PyArrow
  narwhals/_pandas_like/dataframe.py
Labels: internal, fix

#838 release: Bump version to 1.5.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: internal, release

#842 test: remove `to_numpy` and `to_list` in tests
  tests/expr_and_series/dt/to_string_test.py
  tests/frame/slice_test.py
  tests/series_only/to_list_test.py
Labels: internal

#839 feat: support `__getitem__` with slices for columns
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/stable/v1.py
  tests/frame/slice_test.py
Labels: enhancement, internal

#843 feat: `mean_horizontal`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/namespace.py
  narwhals/_polars/typing.py
  narwhals/expr.py
  narwhals/stable/v1.py
  tests/expr_and_series/mean_horizontal_test.py
Labels: enhancement, internal

#844 docs: Fix indentation for __getitem__
  narwhals/dataframe.py
Labels: documentation, internal

#741 feat: dask in api-completeness table
  .gitignore
  docs/api-completeness/index.md
  docs/extending.md
  mkdocs.yml
  utils/api-completeness.md.jinja
  utils/generate_backend_completeness.py
Labels: enhancement, internal

#845 narwhals-gif README.md
  README.md
Labels: internal

#846 ci: changed release-drafter regex
  .github/release-drafter.yml
Labels: internal

#849 release: Bump version to 1.5.3
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#847 feat: Support more indexing: boolean lists to DataFrame.filter and Series.filter, add DataFrame.row,
  docs/api-reference/dataframe.md
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expr.py
  tests/expr_and_series/filter_test.py
  tests/frame/filter_test.py
  tests/frame/get_column_test.py
  tests/frame/row_test.py
  tests/frame/slice_test.py
Labels: enhancement

#848 feat: Add is_pandas_like_dataframe and is_pandas_like_series
  docs/api-reference/dependencies.md
  narwhals/__init__.py
  narwhals/dependencies.py
  narwhals/stable/v1.py
  narwhals/utils.py
  tests/test_utils.py
Labels: enhancement

#850 chore: nox revamp and coverage threshold change
  .github/workflows/pytest.yml
  .gitignore
  noxfile.py
  pyproject.toml
Labels: internal

#856 release: Bump version to 1.5.4
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#855 feat: make DataFrame.select stricter: non-string columns can only be selected using `nw.col`
  docs/other/column_names.md
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  tests/frame/select_test.py
Labels: enhancement

#857 feat: use validate_column_comparand in zip_with
  narwhals/_pandas_like/series.py
Labels: enhancement

#588 feat: add when-then-otherwise expression
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_pandas_like/namespace.py
  narwhals/expr.py
  narwhals/stable/v1.py
  narwhals/utils.py
  pyproject.toml
  tests/expr_and_series/when_test.py
Labels: enhancement

#859 feat: implement when/then/otherwise for PyArrow
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  tests/expr_and_series/when_test.py
Labels: enhancement

#860 chore: simplify arrow
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  tests/expr_and_series/when_test.py
Labels: internal

#861 release: Bump version to 1.5.5
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#851 docs: add codespace steps and fork steps to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#865 patch: Fix inconsistent between tying and comments in `from_native` when 'strict=True'
  narwhals/stable/v1.py
Labels: fix

#866 docs: fix relative links in contributing.md
  CONTRIBUTING.md
Labels: documentation

#867 feat: add `maybe_get_index`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/stable/v1.py
  narwhals/utils.py
  tests/test_utils.py
Labels: enhancement

#821 feat: dask expr `cast`
  narwhals/_dask/expr.py
  narwhals/_dask/utils.py
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/cast_test.py
  tests/selectors_test.py
  tests/test_group_by.py
Labels: enhancement

#870 test: Unxfail 2 modin tests
  narwhals/_pandas_like/series.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
Labels: internal

#871 test: unxfail more modin tests
  narwhals/_pandas_like/series.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
Labels: internal

#840 feat: dask namespace `concat` method
  narwhals/_dask/namespace.py
  tests/frame/concat_test.py
Labels: enhancement

#874 chore: improve (internal) Dask typing
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
Labels: internal

#879 chore: Exclude `utils/` from build
  pyproject.toml
Labels: internal

#880 chore: move tpc-h queries to scripts
  .gitignore
  pyproject.toml
  tpch/README.md
  tpch/execute/__init__.py
  tpch/execute/q1.py
  tpch/execute/q2.py
  tpch/generate_data.py
  tpch/notebooks/gpu/execute.ipynb
  tpch/notebooks/gpu/kernel-metadata.json
  tpch/notebooks/q8/execute.ipynb
  tpch/notebooks/q8/kernel-metadata.json
  tpch/queries/__init__.py
  tpch/queries/q1.py
  tpch/queries/q2.py
Labels: internal

#882 build: exclude more files (plus some drive-by typing)
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  pyproject.toml
Labels: build

#885 chore: run mypy only on `narwhals/` and `tests/`
  .pre-commit-config.yaml
  tests/test_utils.py
Labels: internal

#877 Test dask wih npartitions
  narwhals/dataframe.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
  tests/frame/join_test.py
Labels: internal

#887 feat: query 11 implementation
  tpch/execute/q11.py
  tpch/queries/q11.py
Labels: enhancement

#888 docs: Example correction
  narwhals/functions.py
  narwhals/stable/v1.py
Labels: documentation

#889 feat: Add q3 of tpch
  tpch/execute/q3.py
  tpch/queries/q3.py
Labels: enhancement

#891 feat: add q4 implementation
  tpch/execute/q4.py
  tpch/queries/q4.py
Labels: enhancement

#892 feat: add q5 implementation
  tpch/execute/q5.py
  tpch/queries/q5.py
Labels: enhancement
