Repository narwhals-dev/narwhals, pull requests merged in 2024-07, with the labels that each got.

#365 feat: add IntoDataframe type hint
  narwhals/translate.py
  narwhals/typing.py
  pyproject.toml
  tests/expr/str/starts_with_ends_with_test.py
Labels: enhancement

#369 feat: add Unknown dtype
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/dtypes.py
  tests/frame/schema_test.py
  tests/series/cast_test.py
Labels: enhancement

#371 chore: add Missing pyarrow methods script
  .pre-commit-config.yaml
  utils/check_backend_completeness.py
Labels: internal

#373 chore: add `constructor` fixture for tests
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
  tests/conftest.py
  tests/expr/any_all_test.py
  tests/expr/cat/get_categories_test.py
  tests/expr/cum_sum_test.py
  tests/expr/diff_test.py
  tests/expr/fill_null_test.py
  tests/expr/filter_test.py
  tests/expr/is_between_test.py
  tests/expr/is_duplicated_test.py
  tests/expr/is_first_distinct_test.py
  tests/expr/is_last_distinct_test.py
  tests/expr/is_unique_test.py
  tests/expr/len_test.py
  tests/expr/n_unique_test.py
  tests/expr/null_count_test.py
  tests/expr/over_test.py
  tests/expr/round_test.py
  tests/expr/sample_test.py
  tests/expr/shift_test.py
  tests/expr/str/head_test.py
  tests/expr/str/slice_test.py
  tests/expr/str/tail_test.py
  tests/expr/test_dt.py
  tests/frame/drop_nulls_test.py
  tests/frame/len_test.py
  tests/frame/pipe_test.py
  tests/frame/schema_test.py
  tests/frame/shape_test.py
  tests/frame/slice_test.py
  tests/frame/test_common.py
  tests/frame/with_columns_sequence_test.py
  tests/frame/with_row_index_test.py
  tests/frame/write_parquet_test.py
  tests/series/arithmetic_test.py
  tests/test_group_by.py
  tests/test_selectors.py
Labels: internal

#375 chore: make constructor_series in conftest
  tests/conftest.py
  tests/series/arithmetic_test.py
  tests/series/eq_ne_test.py
  tests/series/to_frame_test.py
  tests/series/to_list_test.py
Labels: internal

#347 feat: cross join
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/test_common.py
  tests/hypothesis/test_join.py
Labels: enhancement

#379 chore: increase local test coverage to 100
  tests/frame/test_common.py
Labels: internal

#383 docs: Add contributing guide link to README.md
  README.md
Labels: documentation

#382 feat: add .cat.get_categories to pyarrow
  narwhals/_arrow/series.py
  tests/expr/cat/get_categories_test.py
Labels: enhancement

#385 feat: add Series.is_empty
  narwhals/_arrow/series.py
  tests/series/is_empty_test.py
  tests/series/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#389 feat: add Expr.cast and Series.cast for PyArrow backend
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/expr/cast_test.py
  tests/series/cast_test.py
  tests/series/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#378 feat: anti join
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  tests/conftest.py
  tests/frame/test_common.py
  tests/utils.py
Labels: enhancement

#391 docs: Change expression of merge example in `Why`
  docs/why.md
Labels: documentation

#397 fix: raise if complex pandas aggregation would return empty results
  narwhals/_pandas_like/group_by.py
  tests/conftest.py
  tests/test_group_by.py
Labels: fix

#400 chore: factor `sort_test` out of `test_common`
  tests/frame/sort_test.py
  tests/frame/test_common.py
Labels: internal

#399 chore: make from_iterable private
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
Labels: internal

#395 docs: dataframe docstring via template
  narwhals/dataframe.py
Labels: documentation

#403 fix: `dtype` could not be passed to Series.__array__
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/series.py
  pyproject.toml
  tests/conftest.py
  tests/series/array_dunder_test.py
Labels: fix

#405 build: try reducing wheel size
  pyproject.toml
Labels: build

#404 feat: some pyarrow dataframe methods
  narwhals/_arrow/dataframe.py
  noxfile.py
  tests/frame/drop_nulls_test.py
  tests/frame/sort_test.py
  tests/frame/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#406 feat: add `clone` for dataframes
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/conftest.py
  tests/frame/clone_test.py
Labels: enhancement

#408 chore: return Self more
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
Labels: internal

#409 feat: Expr.Abs and Series.abs
  docs/api-reference/expressions.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr/abs_test.py
Labels: enhancement

#412 feat: add DataFrame.lazy and LazyFrame.lazy
  narwhals/dataframe.py
  narwhals/group_by.py
Labels: enhancement

#414 chore: factor out to_dict test
  tests/frame/test_common.py
  tests/frame/to_dict_test.py
Labels: internal

#415 chore: add nbstripout
  .pre-commit-config.yaml
  tpch/notebooks/gpu/execute.ipynb
  tpch/notebooks/q1/execute.ipynb
  tpch/notebooks/q2/execute.ipynb
  tpch/notebooks/q21/execute.ipynb
  tpch/notebooks/q3/execute.ipynb
  tpch/notebooks/q4/execute.ipynb
  tpch/notebooks/q5/execute.ipynb
  tpch/notebooks/q6/execute.ipynb
  tpch/notebooks/q7/execute.ipynb
  tpch/notebooks/q8/execute.ipynb
Labels: internal

#423 feat: distinguish IntoDataFrame and IntoFrame
  narwhals/functions.py
  narwhals/translate.py
  narwhals/typing.py
  tests/frame/test_common.py
  tests/hypothesis/test_concat.py
Labels: enhancement

#426 docs: add page on type hints
  README.md
  docs/api-reference/narwhals.md
  docs/api-reference/typing.md
  docs/basics/column.md
  docs/basics/complete_example.md
  docs/basics/dataframe.md
  docs/index.md
  docs/quick_start.md
  mkdocs.yml
  narwhals/typing.py
Labels: documentation

#430 perf: push down `parse_version`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/group_by.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  tests/frame/test_common.py
  utils/check_api_reference.py
  utils/check_backend_completeness.py
Labels: performance

#429 feat: implement DataFrame.with_columns for arrow backend
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/utils.py
  tests/expr/diff_test.py
  tests/expr/double_test.py
  tests/frame/add_test.py
  tests/frame/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#431 perf: simplify pyarrow diff
  narwhals/_arrow/series.py
  tests/expr/diff_test.py
Labels: performance, internal

#433 chore: simplify instantiation of top-level Narwhals objects
  narwhals/_pandas_like/group_by.py
  narwhals/dataframe.py
  narwhals/translate.py
  tests/frame/instantiation_test.py
  tests/frame/test_common.py
Labels: internal

#434 chore: simplify Series instantiation
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
  utils/check_api_reference.py
Labels: internal

#435 docs: fix `typing` link
  README.md
  docs/index.md
Labels: documentation

#436 feat: allow dt.microsecond and dt.millisecond in old pyarrow-backed p…
  narwhals/_pandas_like/series.py
  tests/expr/test_dt.py
Labels: enhancement

#438 chore: Factor out expression parsing
  .github/workflows/random_ci_pytest.yml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
  narwhals/expression.py
  narwhals/typing.py
Labels: internal

#456 ci: pin Numpy version in random CI versions job
  .github/workflows/random_ci_pytest.yml
  tests/expr/cast_test.py
  utils/generate_random_versions.py
Labels: internal

#439 enh: pandas-like semi join
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
  tests/frame/test_common.py
Labels: enhancement

#459 chore: rename some internal attributes for clarity
  docs/how_it_works.md
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/series.py
  narwhals/stable/v1.py
  narwhals/translate.py
  narwhals/utils.py
  tests/frame/clone_test.py
  tests/frame/join_test.py
Labels: internal

#460 chore: Rename pandas objects
  docs/extending.md
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
  narwhals/translate.py
  narwhals/utils.py
  utils/check_backend_completeness.py
Labels: internal

#478 docs: add dark-mode switch
  mkdocs.yml
Labels: documentation

#479 feat: add DataFrame.get_column
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  pyproject.toml
  tests/frame/get_column_test.py
  utils/check_api_reference.py
Labels: enhancement

#481 perf: avoid unnecessary reset_index in join
  narwhals/_pandas_like/dataframe.py
Labels: performance

#487 feat: pyarrow `to_numpy`, `to_dict`, `with_row_index`
  narwhals/_arrow/dataframe.py
  tests/frame/pipe_test.py
  tests/frame/to_dict_test.py
  tests/frame/to_numpy_test.py
  tests/frame/with_row_index_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#488 feat: Arrow `head`, `tail`, `null_count`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  tests/expr/null_count_test.py
  tests/frame/head_test.py
  tests/frame/null_count_test.py
  tests/frame/tail_test.py
  tests/series/head_test.py
  tests/series/null_count_test.py
  tests/series/tail_test.py
  tests/series/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#494 ci: try improving release flow
  .github/release-drafter.yml
  utils/bump_version.py
Labels: internal

#457 feat: implement min and max for pyarrow
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr/min_max_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#489 feat: Added Expr and Series Count method
  docs/api-reference/expressions.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr/count_test.py
  tests/series/test_common.py
Labels: enhancement

#491 feat: pyarrow `filter`, comparand and logic operators
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  tests/expr/arithmetic_test.py
  tests/expr/filter_test.py
  tests/expr/operators_test.py
  tests/frame/filter_test.py
  tests/series/arithmetic_test.py
  tests/series/eq_ne_test.py
  tests/series/filter_test.py
  tests/series/operators_test.py
  tests/series/test_common.py
  tests/series/to_frame_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#503 feat: pyarrow `sum_horizontal`
  narwhals/_arrow/namespace.py
  tests/expr/sum_horizontal_test.py
Labels: enhancement

#502 feat: expose `all_horizontal`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/series.py
  narwhals/expression.py
  narwhals/stable/v1.py
  tests/expr/all_horizontal_test.py
Labels: enhancement

#501 feat: `translate` module coverage
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/series.py
  narwhals/translate.py
  tests/translate/from_native_pandas_test.py
  tests/translate/from_native_test.py
  tests/translate/to_native_test.py
Labels: enhancement

#506 chore: increase local coverage for join
  tests/frame/join_test.py
  tests/utils.py
Labels: internal

#507 feat: implement inner join for arrow
  narwhals/_arrow/dataframe.py
  tests/frame/join_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#510 feat: add some right-hand operations for Arrow
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/series.py
  tests/expr/arithmetic_test.py
  tests/series/arithmetic_test.py
Labels: enhancement

#511 test: increase test coverage
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/translate.py
  tests/expr/all_horizontal_test.py
  tests/frame/instantiation_test.py
  tests/frame/test_common.py
  tests/translate/from_native_test.py
Labels: enhancement

#514 ci: run autolabeler also after PR title has been edited
  .github/workflows/release-drafter.yml
Labels: internal

#518 chore: rename `native_dataframe` in `from_native`
  narwhals/stable/v1.py
  narwhals/translate.py
  tests/stable_api_test.py
Labels: internal

#519 feat: `from_native` raise invalid comb
  narwhals/translate.py
  tests/translate/from_native_test.py
Labels: enhancement

#517 feat: add "interchange"-level support for libraries which implement the interchange protocol
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_interchange/__init__.py
  narwhals/_interchange/dataframe.py
  narwhals/_interchange/series.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1.py
  narwhals/translate.py
  narwhals/typing.py
  narwhals/utils.py
  requirements-dev.txt
  tests/frame/get_column_test.py
  tests/frame/interchange_schema_test.py
  tests/frame/join_test.py
  tests/frame/test_invalid.py
  tests/series/is_ordered_categorical_test.py
  tests/translate/from_native_test.py
  utils/check_api_reference.py
  utils/check_backend_completeness.py
  utils/generate_random_versions.py
Labels: enhancement

#516 feat: `collect_schema` method
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  docs/api-reference/schema.md
  mkdocs.yml
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/schema.py
  narwhals/stable/v1.py
  tests/frame/schema_test.py
  tests/frame/test_common.py
  tests/test_schema.py
Labels: enhancement

#513 feat: add dataframe.group_by for Arrow
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/utils.py
  tests/test_group_by.py
  tests/tpch_q1_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#522 docs: rework README, remove ibis comparison
  README.md
  docs/levels.md
  mkdocs.yml
  pyproject.toml
  tests/series/cast_test.py
Labels: documentation

#520 feat: pyarrow `item`, `is_empty`, `rename`, `write_parquet`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/dependencies.py
  tests/frame/is_empty_test.py
  tests/frame/rename_test.py
  tests/frame/rows_test.py
  tests/frame/test_common.py
  tests/frame/write_parquet_test.py
  tests/series/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#524 feat: pyarrow `lit`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/frame/lit_test.py
Labels: enhancement

#525 feat: pyarrow `concat`
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  tests/frame/test_common.py
Labels: enhancement

#495 feat: Series.sum test case
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr/sum_all_test.py
  tests/frame/series_sum_test.py
  tests/stable_api_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#526 enh: ruff S rule fix
  narwhals/_arrow/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/group_by.py
  pyproject.toml
Labels: enhancement

#532 ci: fix exception in code snippet, add check to CI
  .github/workflows/check_docs_build.yml
  docs/levels.md
  tests/frame/join_test.py
  utils/check_for_no_build_errors.py
Labels: documentation, internal

#533 ci: add downstream tests for altair + scikit-lego
  .github/workflows/downstream_tests.yml
Labels: internal

#534 feat: add `is_null` and `__invert__` to pyarrow series
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/frame/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#527 chore: ruff rules
  narwhals/_arrow/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/expression.py
  narwhals/functions.py
  narwhals/utils.py
  pyproject.toml
  tests/frame/write_parquet_test.py
Labels: internal

#535 ci: remove [dev] from sklego install
  .github/workflows/downstream_tests.yml
Labels: internal

#536 feat: `ArrowExprCatNamespace`
  narwhals/_arrow/expr.py
  tests/expr/cat/get_categories_test.py
Labels: enhancement

#538 feat: add len to pyarrow series and expr
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr/len_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#539 ci: actually use pandas nightly in pandas-nightly build
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  tests/frame/test_invalid.py
Labels: internal

#540 feat: allow nw.len in groupby for arrow
  .github/workflows/extremes.yml
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/group_by.py
  tests/test_group_by.py
  tests/tpch_q1_test.py
  tpch/notebooks/q1/execute.ipynb
  tpch/notebooks/q2/execute.ipynb
  tpch/notebooks/q3/execute.ipynb
  tpch/notebooks/q4/execute.ipynb
  tpch/notebooks/q5/execute.ipynb
  tpch/notebooks/q6/execute.ipynb
  tpch/notebooks/q7/execute.ipynb
Labels: enhancement

#548 feat: arrow series `zip_with`
  narwhals/_arrow/series.py
  narwhals/series.py
  tests/series_only/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#549 chore: refactor agg_arrow
  narwhals/_arrow/group_by.py
Labels: internal

#550 feat: arrow series `sample`
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/sample_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#553 docs: fix link for community cal
  CONTRIBUTING.md
  README.md
Labels: documentation

#554 docs: add note about funding to readme
  README.md
Labels: documentation

#560 chore: rename internal extract_native function
  narwhals/expression.py
Labels: internal

#561 chore: Factor out _polars from top-level Narwhals modules (i.e.: the mother of all refactors!)
  .github/workflows/downstream_tests.yml
  docs/how_it_works.md
  narwhals/_polars/__init__.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/group_by.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/dataframe.py
  narwhals/dtypes.py
  narwhals/expression.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1.py
  narwhals/translate.py
  narwhals/utils.py
  tests/expr_and_series/test_dt.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
  tests/frame/test_common.py
  tests/translate/from_native_test.py
  utils/check_api_reference.py
  utils/check_backend_completeness.py
Labels: internal

#558 feat: arrow join methods
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/utils.py
  tests/expr_and_series/fill_null_test.py
  tests/frame/join_test.py
  tests/hypothesis/test_join.py
  utils/check_backend_completeness.py
Labels: enhancement

#551 feat: arrow string namespace(s)
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/str/contains_test.py
  tests/expr_and_series/str/head_test.py
  tests/expr_and_series/str/slice_test.py
  tests/expr_and_series/str/starts_with_ends_with_test.py
  tests/expr_and_series/str/tail_test.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement

#562 feat: arrow selectors
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  tests/test_selectors.py
Labels: enhancement

#563 docs: reword "related projects" section, remove all Ibis comparisons
  docs/related.md
Labels: documentation

#559 docs: docstrings narwhalify-cation
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/group_by.py
  narwhals/selectors.py
  narwhals/series.py
  narwhals/stable/v1.py
  narwhals/translate.py
  narwhals/utils.py
Labels: documentation

#544 feat: add `__floordiv__` and `__rfloordiv__` for pyarrow
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/expr_and_series/arithmetic_test.py
  tests/series_only/arithmetic_test.py
Labels: enhancement

#564 feat: implement truediv for pyarrow
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/expr_and_series/arithmetic_test.py
  tests/series_only/arithmetic_test.py
Labels: enhancement

#565 feat: arrow `unique`, `is_duplicated`, `is_unique`
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/is_duplicated_test.py
  tests/frame/is_unique_test.py
  tests/frame/unique_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#552 feat: `ExprNameNamespace`
  docs/api-reference/expressions_name.md
  mkdocs.yml
  narwhals/_arrow/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/expression.py
  tests/expr_and_series/name/__init__.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  utils/check_api_reference.py
Labels: enhancement

#568 feat: add DataFrame__contains__, Expr.arg_true, and Series.arg_true
  docs/api-reference/expressions.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expression.py
  narwhals/series.py
  tests/expr_and_series/arg_true_test.py
Labels: enhancement

#570 feat: pyarrow series descriptive methods
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/is_unique_test.py
  tests/series_only/is_sorted_test.py
  tests/series_only/test_common.py
  tests/series_only/to_frame_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#530 docs: api completeness
  .gitignore
  .pre-commit-config.yaml
  docs/api-reference/expr.md
  docs/api-reference/expr_cat.md
  docs/api-reference/expr_dt.md
  docs/api-reference/expr_name.md
  docs/api-reference/expr_str.md
  docs/extending.md
  docs/requirements-docs.txt
  mkdocs.yml
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/selectors.py
  narwhals/stable/v1.py
  narwhals/typing.py
  utils/api-completeness.md.jinja
  utils/check_api_reference.py
  utils/generate_backend_completeness.py
Labels: documentation

#576 feat: add arrow value_counts
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  tests/series_only/test_common.py
  tests/series_only/value_counts_test.py
  utils/check_backend_completeness.py
Labels: enhancement

#577 feat: `Series.to_dummies`, arrow `sort` and `unique`
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  tests/expr_and_series/sort_test.py
  tests/expr_and_series/unary_test.py
  tests/expr_and_series/unique_test.py
  tests/series_only/to_dummy_test.py
  utils/check_api_reference.py
  utils/check_backend_completeness.py
Labels: enhancement

#592 ci: fix hypothesis failure, remove ibis from tests
  narwhals/_pandas_like/group_by.py
  requirements-dev.txt
  tests/frame/interchange_schema_test.py
  tests/hypothesis/test_join.py
  tests/series_only/arithmetic_test.py
  tests/test_group_by.py
Labels: internal

#587 perf: fastpath for simple select in pandas-like
  narwhals/_pandas_like/dataframe.py
Labels: performance

#584 chore: factor `item_test` out of `test_common`
  tests/frame/item_test.py
  tests/frame/test_common.py
Labels: internal

#585 chore: factor `concat_test` out of `test_common`
  tests/frame/concat_test.py
  tests/frame/test_common.py
Labels: internal

#580 feat: add `nulls_last` argument in `Series/Expr.sort`
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/sort_test.py
Labels: enhancement

#595 feat: allow non-string columns names more for pandas
  narwhals/_pandas_like/dataframe.py
  tests/frame/with_columns_test.py
  tests/series_only/value_counts_test.py
Labels: enhancement

#583 feat: `Series.value_count` spec enhancement
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  narwhals/stable/v1.py
  pyproject.toml
  tests/series_only/value_counts_test.py
Labels: enhancement

#597 perf: remove as_py from _arrow implementation wherever possible
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/frame/item_test.py
  tests/series_only/is_sorted_test.py
  tests/series_only/test_common.py
Labels: performance

#598 chore: reoder definitions in from_native
  narwhals/translate.py
Labels: internal

#596 feat: pyarrow dataframe `iter_rows`
  narwhals/_arrow/dataframe.py
  tests/frame/rows_test.py
Labels: enhancement

#599 chore: remove some unnecessary flattens
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/group_by.py
Labels: internal

#600 feat: arrow `quantile` method
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/quantile_test.py
  tests/series_only/test_common.py
  utils/check_backend_completeness.py
Labels: enhancement

#601 feat: arrow namespace reduction functions
  narwhals/_arrow/namespace.py
  narwhals/_polars/namespace.py
  tests/expr_and_series/max_test.py
  tests/expr_and_series/mean_test.py
  tests/expr_and_series/min_max_test.py
  tests/expr_and_series/min_test.py
  tests/expr_and_series/sum_all_test.py
  tests/expr_and_series/sum_test.py
  tests/frame/test_common.py
Labels: enhancement

#602 feat: add from_dict
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/series.py
  narwhals/functions.py
  narwhals/stable/v1.py
  tests/from_dict_test.py
Labels: enhancement

#605 feat: `any_horizontal` function
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/expr.py
  narwhals/stable/v1.py
  tests/expr_and_series/any_horizontal_test.py
Labels: enhancement

#604 docs: document PyArrow as "full" support
  README.md
  docs/extending.md
  docs/levels.md
Labels: documentation

#607 fix: correct Polars version check for pl.len function
  narwhals/_polars/namespace.py
Labels: fix

#606 feat: add `schema` argument to `from_dict` function
  narwhals/functions.py
  narwhals/stable/v1.py
  tests/from_dict_test.py
Labels: enhancement

#608 chore: extend `Implementation` for all backends
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/functions.py
  narwhals/translate.py
  narwhals/utils.py
  tests/frame/join_test.py
Labels: internal

#609 feat : added arrow `is_between` and `is_between_test.py`
  narwhals/_arrow/series.py
  tests/series_only/is_between_test.py
Labels: enhancement

#613 docs: fix typo in README, update roadmap + related projects
  README.md
  docs/related.md
  docs/roadmap.md
Labels: documentation

#614 release: Bump version to 1.1.6
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#615 ci: improve release process
  .github/release-drafter.yml
  utils/bump_version.py
Labels: internal

#617 chore: factor `test_empty_select` out of `test_common` (to existing `select_test.py`)
  tests/frame/select_test.py
  tests/frame/test_common.py
Labels: internal

#616 feat: arrow datetime namespace
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  tests/expr_and_series/dt/__init__.py
  tests/expr_and_series/dt/datetime_attributes_test.py
  tests/expr_and_series/dt/datetime_duration_test.py
  tests/expr_and_series/dt/ordinal_day_test.py
  tests/expr_and_series/dt/to_string_test.py
  tests/expr_and_series/dt/total_minutes_test.py
  tests/expr_and_series/test_dt.py
Labels: enhancement

#621 docs: replace `df_any`/`s_any` with `df`/`s`
  docs/api-reference/typing.md
  docs/basics/complete_example.md
  docs/levels.md
  docs/other/pandas_index.md
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/group_by.py
  narwhals/selectors.py
  narwhals/series.py
  narwhals/stable/v1.py
  narwhals/translate.py
  narwhals/utils.py
Labels: documentation

#622 feat: allow slicing by tuple of sequences of ints
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/stable/v1.py
  tests/frame/slice_test.py
Labels: enhancement

#624 feat: raise informative error if getitem is used in unsupported manner
  narwhals/dataframe.py
  tests/frame/slice_test.py
Labels: enhancement

#619 feat: `gather_every` methods
  docs/api-reference/dataframe.md
  docs/api-reference/expr.md
  docs/api-reference/lazyframe.md
  docs/api-reference/series.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/gather_every_test.py
  tests/frame/gather_every_test.py
Labels: enhancement

#625 release: Bump version to 1.1.7
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#627 perf: optimizing arrow to_dummies
  narwhals/_arrow/series.py
Labels: performance

#626 chore: allow unknown/extension namespaces for `from_dict` function
  narwhals/functions.py
  narwhals/stable/v1.py
  narwhals/utils.py
Labels: internal

#632 ci: Add dependabot
  .github/dependabot.yml
Labels: internal

#635 feat: Add initial (and very minimal) support for Dask.DataFrame
  .github/workflows/extremes.yml
  narwhals/_dask/__init__.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/dependencies.py
  narwhals/translate.py
  requirements-dev.txt
  tests/dask_test.py
Labels: enhancement

#638 feat: add shift for Dask Dataframe
  narwhals/_dask/expr.py
  tests/dask_test.py
Labels: enhancement

#639 fix dask typo
  narwhals/translate.py
Labels: fix

#640 fix: fix dask version in dask backend
  narwhals/dependencies.py
  narwhals/translate.py
Labels: fix

#641 feat: add cum_sum for dask
  narwhals/_dask/expr.py
  tests/dask_test.py
Labels: enhancement

#644 feat: added dask `Expr.__mul__` and test cases
  narwhals/_dask/expr.py
  tests/dask_test.py
Labels: enhancement

#642 feat: add `is_between` for dask
  narwhals/_dask/expr.py
  tests/dask_test.py
Labels: enhancement

#646 chore: replace constructor_with_series with constructor in gather_every_test
  narwhals/dependencies.py
  tests/dask_test.py
  tests/expr_and_series/gather_every_test.py
Labels: internal

#648 feat: add `starts_with` for dask
  narwhals/_dask/expr.py
  tests/dask_test.py
Labels: enhancement

#643 feat: added dask `Expr.__sub__`
  narwhals/_dask/expr.py
  narwhals/dependencies.py
  tests/dask_test.py
  tests/expr_and_series/gather_every_test.py
Labels: enhancement

#649 chore: replace constructor_series with constructor
  narwhals/dependencies.py
  tests/expr_and_series/is_in_test.py
  tests/expr_and_series/sort_test.py
  tests/series_only/arithmetic_test.py
  tests/series_only/filter_test.py
  tests/series_only/is_between_test.py
  tests/series_only/is_sorted_test.py
  tests/series_only/null_count_test.py
  tests/series_only/operators_test.py
  tests/series_only/test_common.py
  tests/series_only/to_dummy_test.py
  tests/series_only/to_frame_test.py
  tests/series_only/to_list_test.py
  tests/series_only/value_counts_test.py
Labels: internal

#650 chore: use constructor instead of constructor_series in tests more
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/is_unique_test.py
  tests/expr_and_series/max_test.py
  tests/expr_and_series/mean_test.py
  tests/expr_and_series/min_test.py
  tests/expr_and_series/sum_test.py
  tests/expr_and_series/unique_test.py
Labels: internal

#651 feat: add collect for dask
  narwhals/_dask/dataframe.py
  tests/conftest.py
  tests/dask_test.py
  tests/expr_and_series/quantile_test.py
  tests/series_only/arithmetic_test.py
  tests/series_only/array_dunder_test.py
  tests/series_only/head_test.py
  tests/series_only/is_empty_test.py
  tests/series_only/is_ordered_categorical_test.py
  tests/series_only/shape_test.py
  tests/series_only/tail_test.py
Labels: enhancement

#652 chore: split eager-only and eager+lazy tests a bit
  .github/workflows/pytest.yml
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  pyproject.toml
  tests/conftest.py
  tests/expr_and_series/abs_test.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/any_all_test.py
  tests/expr_and_series/any_horizontal_test.py
  tests/expr_and_series/arg_true_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/count_test.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/double_selected_test.py
  tests/expr_and_series/double_test.py
  tests/expr_and_series/drop_nulls_test.py
  tests/expr_and_series/dt/to_string_test.py
  tests/expr_and_series/fill_null_test.py
  tests/expr_and_series/filter_test.py
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/is_unique_test.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  tests/expr_and_series/str/starts_with_ends_with_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/expr_and_series/unary_test.py
  tests/expr_and_series/unique_test.py
  tests/frame/clone_test.py
  tests/frame/concat_test.py
  tests/frame/gather_every_test.py
  tests/frame/lit_test.py
  tests/frame/test_common.py
  tests/frame/to_dict_test.py
  tests/frame/to_pandas_test.py
  tests/frame/unique_test.py
  tests/series_only/arithmetic_test.py
  tests/series_only/test_common.py
  tests/test_group_by.py
Labels: internal

#653 chore: More lazy vs eager separation
  narwhals/_arrow/expr.py
  tests/expr_and_series/is_between_test.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_in_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/is_unique_test.py
  tests/expr_and_series/len_test.py
  tests/expr_and_series/max_test.py
  tests/expr_and_series/mean_test.py
  tests/expr_and_series/min_test.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/null_count_test.py
  tests/expr_and_series/operators_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/quantile_test.py
  tests/expr_and_series/round_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/shift_test.py
  tests/expr_and_series/sum_all_test.py
  tests/expr_and_series/sum_test.py
  tests/frame/test_common.py
  tests/series_only/filter_test.py
  tests/series_only/is_between_test.py
Labels: internal

#655 chore: factor `test_schema` and `test_collect_schema` out of `test_common`
  tests/frame/schema_test.py
  tests/frame/test_common.py
Labels: internal

#656 chore: enable more lazy tests
  narwhals/_arrow/group_by.py
  pyproject.toml
  tests/frame/drop_nulls_test.py
  tests/frame/drop_test.py
  tests/frame/filter_test.py
  tests/frame/head_test.py
  tests/frame/pipe_test.py
  tests/frame/rename_test.py
  tests/frame/select_test.py
  tests/frame/sort_test.py
  tests/frame/tail_test.py
  tests/frame/with_row_index_test.py
  tests/from_dict_test.py
  tests/stable_api_test.py
  tests/test_group_by.py
  tests/test_selectors.py
Labels: internal

#657 chore: factor `test_std` outside `test_common`
  pyproject.toml
  tests/frame/std_test.py
  tests/frame/test_common.py
Labels: internal

#658 chore: enable more lazy tests
  tests/test_group_by.py
Labels: internal
