Repository narwhals-dev/narwhals, pull requests merged in 2025-02, with the labels that each got.

#1906 feat: add `dtype.is_<x>` methods
  docs/api-reference/dtypes.md
  narwhals/dtypes.py
  narwhals/stable/v1/_dtypes.py
  narwhals/stable/v1/dtypes.py
  tests/dtypes_test.py
  tests/series_only/dtype_test.py
Labels: enhancement

#1895 feat: Add `backend` argument to `lazy`
  narwhals/_arrow/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/frame/lazy_test.py
Labels: enhancement

#1908 fix: pandas was raising when index name and column names overlapped in groupby
  README.md
  docs/pandas_like_concepts/pandas_index.md
  narwhals/_pandas_like/group_by.py
  narwhals/typing.py
  tests/conftest.py
  tests/group_by_test.py
Labels: fix

#1913 feat: spark date and datetimedata types, allow for `dtype` in `nw.lit` for pyspark
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/lit_test.py
Labels: enhancement

#1734 feat: `LazyFrame.collect` with backend and **kwargs
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr_str.py
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  pyproject.toml
  tests/expr_and_series/str/to_datetime_test.py
  tests/frame/collect_test.py
  tests/utils.py
Labels: enhancement, high priority

#1890 feat: add `LazyFrame.unpivot` for spark and duckdb
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/conftest.py
  tests/frame/unpivot_test.py
Labels: enhancement, pyspark, duckdb

#1911 chore: simplify duckdb group-by
  narwhals/_duckdb/group_by.py
Labels: internal

#1914 feat: enable `ModuleType` and `str` for backend in `.lazy()` method
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/frame/lazy_test.py
Labels: enhancement

#1916 feat: add duckdb `.str.to_datetime`
  narwhals/_duckdb/expr_str.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement, duckdb

#1915 docs: shorten docstring examples in narwhals/expr.py
  narwhals/expr.py
Labels: documentation

#1891 feat: add `LazyFrame.explode` for duckdb
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/explode_test.py
  tests/utils.py
Labels: enhancement, duckdb

#1919 docs: Minor rendering fixups, inherit all exceptions from NarwhalsError
  docs/backcompat.md
  narwhals/dataframe.py
  narwhals/exceptions.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1922 release: Bump version to 1.25.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1925 refactor: refactoring following refurb and perflint suggestions
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series_str.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr_name.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/namespace.py
  narwhals/dtypes.py
  narwhals/utils.py
Labels: internal

#1930 fix(typing): Ensure `LazyFrame` has a unique `TypeVar`
  narwhals/dataframe.py
Labels: internal

#1934 fix: Always collect `Iterator[IntoExpr]` in `utils.flatten`
  narwhals/utils.py
  tests/expr_and_series/all_horizontal_test.py
Labels: fix

#1935 fix(typing): Use correct `TypeVar`/`Union` pairs in `from_native`
  narwhals/translate.py
Labels: internal, typing

#1936 fix(typing): Use `IntoDataFrameT` in `to_native`
  narwhals/translate.py
Labels: internal, typing

#1815 feat: validate duplicate column names in pyarrow and duckdb
  .github/workflows/extremes.yml
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/exceptions.py
  narwhals/translate.py
  narwhals/utils.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
Labels: enhancement

#1938 ci: fix plotly downstream test
  .github/workflows/downstream_tests.yml
Labels: internal

#1931 enh: Deprecate `native_namespace` in favour of `backend` in `from_dict`
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/frame/lazy_test.py
  tests/from_dict_test.py
Labels: enhancement

#1929 perf: use fastpath in `DataFrame.to_numpy` for pandas, improve performance for `DataFrame.schema` for pandas, use fewer values to sniff dtype for pandas objects
  .github/workflows/downstream_tests.yml
  docs/backcompat.md
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
  tests/frame/schema_test.py
  tests/frame/to_numpy_test.py
Labels: performance

#1939 docs: Make DataFrame and LazyFrame docstrings shorter and more concise
  narwhals/dataframe.py
Labels: documentation

#1941 release: Bump version to 1.25.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1948 fix: raise NotImplementedError for DataFramte.is_duplicated for PyArrow when there is more than one column
  narwhals/_arrow/dataframe.py
  tests/frame/is_duplicated_test.py
Labels: fix

#1949 fix: cuDF to_numpy tests were failing
  narwhals/_pandas_like/dataframe.py
Labels: fix

#1951 feat: restore support of `is_duplicated` for pyarrow
  narwhals/_arrow/dataframe.py
  tests/frame/is_duplicated_test.py
  tests/frame/is_unique_test.py
Labels: enhancement

#1952 release: Bump version to 1.25.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1954 fix(typing): Backport use `IntoDataFrameT` in `to_native` to `v1`
  narwhals/stable/v1/__init__.py
Labels: fix, typing

#1960 chore: reduce duplication, implement more methods at the Narwhals level rather than at the compliant level, fix CI from Ibis release
  .github/workflows/extremes.yml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/frame/unpivot_test.py
  tests/utils.py
Labels: internal

#1965 ci: fix plotly tests location
  .github/workflows/downstream_tests.yml
Labels: ci

#1967 fix(typing): add missing `Series._level` annotation
  narwhals/series.py
Labels: typing

#1957 docs: add docstring guidelines to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1955 chore(typing): add guards `is_compliant_*` (+ friends)
  narwhals/_expression_parsing.py
  narwhals/translate.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal, typing

#1963 fix: missing `__getitem__` type fixes
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/frame/get_column_test.py
  tests/frame/getitem_test.py
Labels: internal, typing

#1898 test: Add new_streaming
  .github/workflows/pytest.yml
  tests/utils.py
Labels: tests

#1968 fix(typing): resolve remaining `utils.py` warnings
  narwhals/utils.py
Labels: typing

#1924 feat: add `Schema.to_(arrow|pandas|polars)`
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
  narwhals/schema.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  tests/frame/schema_test.py
Labels: enhancement

#1969 chore(typing): fix `_from_compliant_dataframe` type ignore
  narwhals/dataframe.py
Labels: typing

#1973 ci: add Validoopsie to downstream tests
  .github/workflows/downstream_tests.yml
Labels: ci

#1974 chore: shrink `functions` module docstrings
  narwhals/functions.py
Labels: documentation, internal

#1976 RFC, chore: shrink `series` module docstrings
  narwhals/series.py
Labels: documentation, internal

#1975 chore: widen `parse_version` to accept packages
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/schema.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  tests/utils_test.py
Labels: internal

#1956 ci: add pointblank in downstream test
  .github/workflows/downstream_tests.yml
Labels: ci

#1971 ci: validate tpch query results
  tpch/execute.py
  tpch/generate_data.py
  tpch/queries/q1.py
  tpch/queries/q10.py
  tpch/queries/q11.py
  tpch/queries/q12.py
  tpch/queries/q13.py
  tpch/queries/q14.py
  tpch/queries/q15.py
  tpch/queries/q16.py
  tpch/queries/q17.py
  tpch/queries/q18.py
  tpch/queries/q19.py
  tpch/queries/q2.py
  tpch/queries/q20.py
  tpch/queries/q21.py
  tpch/queries/q22.py
  tpch/queries/q3.py
  tpch/queries/q4.py
  tpch/queries/q5.py
  tpch/queries/q6.py
  tpch/queries/q7.py
  tpch/queries/q8.py
  tpch/queries/q9.py
Labels: ci

#1977 chore(typing): add `np.ndarray` aliases
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal, typing

#1822 feat: add `datetime` selector
  docs/api-reference/selectors.md
  docs/api-reference/typing.md
  narwhals/_arrow/expr_dt.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series_dt.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/selectors.py
  narwhals/_pandas_like/expr_dt.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/selectors.py
  narwhals/dtypes.py
  narwhals/expr_dt.py
  narwhals/selectors.py
  narwhals/series_dt.py
  narwhals/stable/v1/selectors.py
  narwhals/typing.py
  narwhals/utils.py
  tests/selectors_test.py
Labels: enhancement

#1983 chore(typing): resolve `_arrow.dataframe` warnings
  narwhals/_arrow/dataframe.py
Labels: internal, typing

#1865 feat: improving array casting
  narwhals/_arrow/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
  narwhals/functions.py
  narwhals/schema.py
  tests/dtypes_test.py
Labels: enhancement

#1918 feat: catch Polars exceptions, unify exception raising more
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  tests/expr_and_series/is_nan_test.py
  tests/expr_and_series/median_test.py
  tests/expr_and_series/replace_strict_test.py
  tests/frame/drop_test.py
  tests/frame/explode_test.py
  tests/frame/filter_test.py
  tests/frame/pivot_test.py
  tests/frame/select_test.py
Labels: enhancement

#1982 chore: minor series.py fixes, dedupe a little
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/series.py
Labels: internal

#1984 fix: implement casting to Int128
  narwhals/_arrow/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  tests/dtypes_test.py
Labels: fix

#1859 feat: Series.hist
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/exceptions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/series_only/hist_test.py
  utils/check_api_reference.py
Labels: enhancement

#1985 release: Bump version to 1.26.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1988 tests: skip cudf hist tests
  tests/series_only/hist_test.py
Labels: internal

#1987 chore: use toArrow in PySpark 4.0+
  narwhals/_spark_like/dataframe.py
Labels: internal

#1986 chore: Expr metadata refactor
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/selectors.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/order_dependent_lazy_test.py
  tests/expr_and_series/unique_test.py
  utils/check_api_reference.py
Labels: internal

#1990 chore: alias named expressions at narwhals level
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
  narwhals/dataframe.py
Labels: internal

#1992 chore: Refactor filter
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/filter_test.py
Labels: internal

#1993 chore: determine whether to use compliant_frame.aggregate at narwhals level
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/group_by.py
  narwhals/typing.py
Labels: internal

#1995 chore: clean up flatten and extract
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
Labels: internal

#1979 chore(typing): remove unused ignores
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_duckdb/dataframe.py
  narwhals/utils.py
Labels: typing

#1997 chore(typing): add overloads to `isinstance_or_issubclass`
  narwhals/_duckdb/utils.py
  narwhals/utils.py
Labels: internal, typing

#2003 chore: simplify when implementation
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal

#1998 ci: remove `pyspark` from Windows CI
  .github/workflows/pytest.yml
  tests/conftest.py
Labels: ci, tests

#2009 test: add test for `sum_horizontal` with column transformation
  tests/expr_and_series/sum_horizontal_test.py
Labels: internal, tests

#2015 ci: update pointblank deps to test downstream in ci
  .github/workflows/downstream_tests.yml
Labels: ci

#2014 perf: avoid try/except in _hasattr_static
  narwhals/utils.py
Labels: performance

#2013 feat: Add support for `series[other_series]`
  narwhals/_arrow/series.py
  narwhals/_polars/series.py
  narwhals/series.py
  tests/series_only/__getitem___test.py
Labels: enhancement, high priority

#2012 chore(typing): resolve time unit/zone `set` invariance
  narwhals/utils.py
Labels: typing

#2018 ci(typing): use `tool.mypy.pretty = true`
  pyproject.toml
Labels: internal, typing

#2019 tests: Allow to run pytest narwhals --doctest-modules without ibis
  pyproject.toml
Labels: internal

#2021 fix: adjust duckdb population skewness by correction factor to get sample skewness
  narwhals/_duckdb/expr.py
  tests/expr_and_series/unary_test.py
Labels: bug: incorrect result, duckdb

#2022 chore(typing): relax `from_dict` to use `Mapping`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal, typing

#2023 chore(typing): relax `from_numpy` to use `Mapping`, `Sequence`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal, typing

#1991 feat: support casting to and from spark-like structs
  narwhals/_spark_like/utils.py
  tests/expr_and_series/cast_test.py
Labels: enhancement

#2024 refactor: reuse `Schema.to_<backend>()` in `from_numpy`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal

#2028 perf: Avoid evaluating expr twice in mean_horizontal
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
Labels: performance

#2027 chore(typing): Upgrade `TypeGuard` -> `TypeIs`
  narwhals/dependencies.py
Labels: internal, typing

#2030 release: Bump version to 1.27.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2007 fix(typing): Resolve all `mypy` & `pyright` errors for `_arrow`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_cat.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_list.py
  narwhals/_arrow/series_str.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/dependencies.py
  narwhals/dtypes.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/expr_and_series/is_nan_test.py
  tests/expr_and_series/rolling_var_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/series_only/is_ordered_categorical_test.py
  tests/translate/get_native_namespace_test.py
Labels: internal, typing

#2031 fix: `is_in` was raising when used with empty list
  .github/workflows/downstream_tests.yml
  narwhals/_arrow/series.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/is_in_test.py
Labels: fix

#2008 chore: fix pandas-stubs issues
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/series.py
  narwhals/utils.py
  pyproject.toml
  tests/conftest.py
  tests/dependencies/is_into_dataframe_test.py
  tests/dtypes_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/nth_test.py
  tests/frame/getitem_test.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/interchange_select_test.py
  tests/frame/interchange_to_arrow_test.py
  tests/frame/invalid_test.py
  tests/frame/schema_test.py
  tests/frame/to_arrow_test.py
  tests/frame/to_pandas_test.py
  tests/frame/to_polars_test.py
  tests/group_by_test.py
  tests/hypothesis/basic_arithmetic_test.py
  tests/hypothesis/getitem_test.py
  tests/hypothesis/join_test.py
  tests/pickle_test.py
  tests/read_scan_test.py
  tests/series_only/cast_test.py
  tests/tpch_q1_test.py
  tests/translate/from_native_test.py
  tests/translate/get_native_namespace_test.py
  tests/utils.py
  tests/utils_test.py
Labels: internal, typing

#2032 fix: PySpark was raising during `collect` when it contained no rows and a void dtype column
  .github/workflows/downstream_tests.yml
  narwhals/_duckdb/expr.py
  narwhals/_spark_like/dataframe.py
  tests/frame/collect_test.py
Labels: fix

#2033 release: Bump version to 1.27.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2034 chore: refactor right-hand-side arithmetic to not use lit
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
Labels: internal

#2039 perf: Avoid double-parsing in concat_str
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/namespace.py
Labels: performance

#2040 chore(perf): move `combine_evaluate_output_names` check
  narwhals/_expression_parsing.py
Labels: performance, internal

#2043 chore: add colors in CI and run `marimo` only in selected python version
  .github/workflows/check_tpch_queries.yml
  .github/workflows/downstream_tests.yml
  .github/workflows/downstream_tests_slow.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
  .github/workflows/typing.yml
Labels: ci

#2046 ci: dont pass filenames to mypy in pre-commit
  .pre-commit-config.yaml
Labels: internal

#2025 fix(RFC): Use metaclass for safe `DType` attr access
  narwhals/_arrow/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
Labels: dtypes, fix, needs discussion

#2035 ci(typing): add `pyright` to ci
  .github/workflows/typing.yml
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/group_by.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  pyproject.toml
  tests/frame/with_columns_sequence_test.py
  tests/from_numpy_test.py
  tests/ibis_test.py
  tests/translate/to_py_scalar_test.py
Labels: ci, typing

#2057 refactor: deduplicate `*.selectors`
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/utils.py
Labels: internal

#2060 chore(typing): add `CompliantExpr._version`
  narwhals/typing.py
Labels: internal, typing

#2059 chore: remove more `kwargs` from dask, dont treat `ddof` as expressifiable arg
  narwhals/_dask/expr.py
  narwhals/_dask/expr_name.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
Labels: internal

#2062 fix: disallow non-elementary operations in .over for pandas
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  tests/expr_and_series/over_test.py
  tests/group_by_test.py
Labels: fix

#2049 refactor(typing): Avoid more `ignore[attr-defined]` on `Datetime`
  narwhals/_arrow/series_dt.py
  narwhals/_dask/expr_dt.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_dt.py
  narwhals/utils.py
  tests/expr_and_series/dt/convert_time_zone_test.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: internal, typing

#2053 refactor(typing): make `_evaluate_output_names` generic
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal, typing

#2066 chore(typing): add `CompliantSeries.dtype`
  narwhals/typing.py
Labels: internal, typing

#2067 chore: use `change_metadata_kind`
  narwhals/_expression_parsing.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/stable/v1/__init__.py
Labels: internal

#2069 chore: remove unused kwargs in `_pandas_like` and `_arrow`
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_name.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_spark_like/utils.py
  narwhals/group_by.py
  tests/group_by_test.py
Labels: documentation, internal, fix

#2070 chore: use Expr._from_callable
  .github/workflows/downstream_tests.yml
  narwhals/expr.py
Labels: internal

#2073 chore: use combine_metadata more
  narwhals/_expression_parsing.py
  narwhals/expr.py
Labels: internal

#2074 refactor: Use real class for `ExprMetadata`
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/functions.py
  narwhals/selectors.py
  narwhals/stable/v1/__init__.py
  utils/check_api_reference.py
Labels: internal

#2077 chore(typing): Re-enable `mypy` strict
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_str.py
  narwhals/_arrow/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/conftest.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/from_dict_test.py
  tests/from_numpy_test.py
  tests/series_only/hist_test.py
  tests/translate/from_native_test.py
  tests/utils_test.py
Labels: internal, typing

#2076 chore(typing): Remove unused `pyright` ignores
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
Labels: internal

#2079 perf: avoid repeating constant iteration
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  narwhals/selectors.py
Labels: performance

#2080 docs: remove griffe fork to build docs
  .github/workflows/mkdocs.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: documentation

#2042 refactor(ruff): enable some preview rules
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_dask/group_by.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/group_by.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/dataframe.py
  narwhals/dtypes.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/series.py
  narwhals/utils.py
  pyproject.toml
  tests/conftest.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/is_nan_test.py
  tests/expr_and_series/operators_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/stable_api_test.py
  tests/utils.py
Labels: internal

#2089 chore(typing): Fix `(Pandas|Arrow)(When|Then)`
  narwhals/_arrow/namespace.py
  narwhals/_pandas_like/namespace.py
Labels: internal, typing

#2088 refactor(typing): Use a forward ref for `IntoCompliantExpr`
  narwhals/typing.py
Labels: internal, typing

#2090 fix: `pyspark` unpivot with index `None`
  narwhals/_spark_like/dataframe.py
  tests/frame/unpivot_test.py
Labels: fix, pyspark

#2038 chore: Finalize support for SQLFrame
  .github/workflows/pytest.yml
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/conftest.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/expr_and_series/unary_test.py
  tests/frame/join_test.py
  tests/frame/select_test.py
  tests/frame/unique_test.py
  tests/frame/unpivot_test.py
  tests/selectors_test.py
Labels: enhancement

#2087 chore(typing): Resolve `_dask` errors
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  pyproject.toml
Labels: internal, typing

#2078 chore: add `has_open_windows` to `ExprMetadata` instead of `is_order_dependent`
  narwhals/_arrow/expr.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/over_test.py
  tests/expression_parsing_test.py
  tests/frame/select_test.py
Labels: internal

#2086 chore: concise_docstrings (#2068)
  narwhals/expr_str.py
  narwhals/series_str.py
Labels: documentation

#2094 chore: rename changes_length to filtration
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/stable/v1/__init__.py
  tests/frame/select_test.py
Labels: internal

#2092 perf: only validate duplicate column names when collecting for duckdb/pyspark/dask
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/over_test.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
  tests/frame/select_test.py
Labels: performance

#2093 perf: use cached property for schema/columns lazy frames
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
Labels: performance

#2098 perf: avoid full broadcast for otherwise_value in when/then/otherwise
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/utils.py
Labels: performance

#2102 perf: Avoid redefining `lambda` in `*Namespace.all`
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/typing.py
  narwhals/utils.py
Labels: performance, internal

#2107 docs: add `Implementation` page
  docs/api-reference/implementation.md
  docs/api-reference/index.md
  mkdocs.yml
Labels: documentation

#2105 chore(typing): fix `group_by`
  narwhals/group_by.py
Labels: internal, typing

#2108 chore(typing): remove unused, ignored `TypeVar`
  narwhals/functions.py
Labels: internal

#2110 feat(typing): Backport generic `Series` to `v1`
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/typing.py
  tests/expr_and_series/dt/timestamp_test.py
  tests/translate/from_native_test.py
Labels: enhancement, typing

#2054 feat: str.split (#1932)
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/expr_str.py
  narwhals/_arrow/series_str.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr_str.py
  narwhals/_pandas_like/expr_str.py
  narwhals/_pandas_like/series_str.py
  narwhals/_spark_like/expr_str.py
  narwhals/expr_str.py
  narwhals/series_str.py
  tests/expr_and_series/str/split_test.py
  tests/utils.py
Labels: enhancement

#2051 chore(typing): enable typing checks for `pyspark`
  .github/workflows/typing.yml
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  narwhals/dependencies.py
  pyproject.toml
  tests/conftest.py
Labels: internal, typing

#2104 feat: Adds `DataFrame.iter_columns`
  docs/api-reference/dataframe.md
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  tests/frame/columns_test.py
Labels: enhancement
