Repository narwhals-dev/narwhals, pull requests merged in 2025-10, with the labels that each got.

#3143 feat(expr-ir): Support `group_by`, utilize `pyarrow.acero`
  narwhals/_plan/_expansion.py
  narwhals/_plan/_expr_ir.py
  narwhals/_plan/_rewrites.py
  narwhals/_plan/arrow/acero.py
  narwhals/_plan/arrow/dataframe.py
  narwhals/_plan/arrow/expr.py
  narwhals/_plan/arrow/functions.py
  narwhals/_plan/arrow/group_by.py
  narwhals/_plan/arrow/options.py
  narwhals/_plan/arrow/typing.py
  narwhals/_plan/common.py
  narwhals/_plan/dataframe.py
  narwhals/_plan/expr.py
  narwhals/_plan/expressions/__init__.py
  narwhals/_plan/expressions/aggregation.py
  narwhals/_plan/group_by.py
  narwhals/_plan/options.py
  narwhals/_plan/protocols.py
  narwhals/_plan/schema.py
  narwhals/_plan/typing.py
  tests/plan/compliant_test.py
  tests/plan/expr_expansion_test.py
  tests/plan/expr_rewrites_test.py
  tests/plan/group_by_test.py
  tests/plan/temp_test.py
  tests/plan/utils.py
Labels: enhancement, internal, tests, pyarrow

#3166 refactor(expr-ir): Split up and refine `protocols.py`
  narwhals/_plan/_expr_ir.py
  narwhals/_plan/_guards.py
  narwhals/_plan/arrow/dataframe.py
  narwhals/_plan/arrow/expr.py
  narwhals/_plan/arrow/group_by.py
  narwhals/_plan/arrow/namespace.py
  narwhals/_plan/arrow/series.py
  narwhals/_plan/arrow/typing.py
  narwhals/_plan/compliant/__init__.py
  narwhals/_plan/compliant/column.py
  narwhals/_plan/compliant/dataframe.py
  narwhals/_plan/compliant/expr.py
  narwhals/_plan/compliant/group_by.py
  narwhals/_plan/compliant/namespace.py
  narwhals/_plan/compliant/scalar.py
  narwhals/_plan/compliant/series.py
  narwhals/_plan/compliant/typing.py
  narwhals/_plan/dataframe.py
  narwhals/_plan/expressions/expr.py
  narwhals/_plan/group_by.py
  narwhals/_plan/protocols.py
  narwhals/_plan/series.py
  narwhals/_plan/typing.py
  tests/plan/compliant_test.py
Labels: internal

#3147 feat: Add `prefix` argument to `generate_temporary_column_name`
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_utils.py
  tests/utils_test.py
Labels: enhancement

#3138 feat: Support `polars.UInt128`
  narwhals/_polars/dataframe.py
  narwhals/_polars/utils.py
  pyproject.toml
  tests/dtypes_test.py
Labels: enhancement, ci, dtypes, polars

#3133 chore: Make `Implementation.UNKNOWN._backend_version()` safe
  narwhals/_utils.py
  tests/dependencies/imports_test.py
Labels: internal, fix, extensibility
