Repository narwhals-dev/narwhals, pull requests merged in 2025-05, with the labels that each got.

#2466 ci: switch from pdm to uv in tea-tasting downstream tests
  .github/workflows/downstream_tests.yml
Labels: ci

#2461 chore: Add `Compliant*.to_narwhals`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_spark_like/dataframe.py
  narwhals/_translate.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/translate.py
  narwhals/utils.py
Labels: api design, internal

#2470 ci: Fix TPCH test data generation in CI
  tests/expr_and_series/is_finite_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/selectors_test.py
  tpch/generate_data.py
Labels: internal

#2473 chore: Remove name-preserving Dask operations
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
Labels: internal

#2432 refactor: remove `Implementation._alias` in favor of non-auto values
  narwhals/_arrow/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_enum.py
  narwhals/_interchange/dataframe.py
  narwhals/_namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/translate.py
  narwhals/utils.py
  tests/dtypes_test.py
  tests/enum_test.py
  tests/expr_and_series/nth_test.py
  tests/implementation_test.py
  tests/utils_test.py
Labels: internal

#2476 patch: Filter `is_sparse` DeprecationWarning in test suite
  pyproject.toml
Labels: fix

#2477 chore: Use `_with_callable` for narwhals expr namespaces
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/expr_struct.py
Labels: internal

#2391 perf: Avoid module-level `importlib.util.find_spec`
  narwhals/_translate.py
  tests/no_imports_test.py
Labels: performance

#2465 feat: add `dt.truncate`
  docs/api-reference/expr_dt.md
  docs/api-reference/series_dt.md
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/utils.py
  narwhals/_duration.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/utils.py
  narwhals/expr_dt.py
  narwhals/series_dt.py
  tests/expr_and_series/dt/truncate_test.py
Labels: enhancement, high priority

#2475 docs: Use Google-Style admonition
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#2460 chore: Adopting more `ruff` complexity rules
  narwhals/_arrow/series.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dataframe.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  utils/check_docstrings.py
Labels: internal

#2480 perf: Dont export `stable` in ``narwhals/__init__.py``, instead require ``import narwhals.stable``
  narwhals/__init__.py
Labels: performance

#2496 test: cudf fixup, address pandas deprecationwarning
  narwhals/_dask/expr_dt.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/dt/truncate_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
Labels: internal

#2501 test: make `polars` optional in `truncate_test`
  tests/expr_and_series/dt/truncate_test.py
Labels: tests

#2494 chore: Simplify `PandasLikeDataFrame.pivot`
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
Labels: internal, pandas-like

#2504 chore: Ensure (`join|join_asof`) predicate lengths match
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: internal

#2503 chore: Simplify `to_py_scalar`
  narwhals/dependencies.py
  narwhals/translate.py
  tests/translate/to_py_scalar_test.py
Labels: internal

#2506 refactor: Add `LazyExpr.alias`
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_spark_like/expr.py
Labels: internal

#2507 test: Fix `pyspark` truncate in ci
  narwhals/_spark_like/expr_dt.py
  tests/expr_and_series/dt/truncate_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
Labels: tests, pyspark, pyspark-connect

#2508 test: Ensure `from_native(...).to_native()` returns original object
  tests/translate/from_native_test.py
Labels: tests

#2512 patch: Fix `is_pyspark_connect_dataframe`
  narwhals/dependencies.py
Labels: fix, pyspark-connect

#2513 release: Bump version to 1.38.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2519 docs: adding Validoopsie to used by
  README.md
  docs/ecosystem.md
Labels: documentation

#2518 fix: Catch ``ImportError`` when checking for PySparkConnect
  narwhals/dependencies.py
  tests/translate/from_native_test.py
  tests/translate/narwhalify_test.py
Labels: pyspark, pyspark-connect

#2520 release: Bump version to 1.38.2
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2505 chore: Simplify `SparkLike` window
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/typing.py
Labels: internal, pyspark, spark-like, pyspark-connect

#2524 docs: Improve API reference search so it doesnt lead to api-completeness, remove outdated parts of Extending page
  docs/api-completeness/index.md
  docs/extending.md
  mkdocs.yml
  tests/expr_and_series/str/to_datetime_test.py
  utils/api-completeness.md.jinja
Labels: documentation

#2483 chore: Refactor expression parsing again (yes, again)
  docs/how_it_works.md
  narwhals/_arrow/expr.py
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/expr_struct.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/arg_min_test.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/expression_parsing_test.py
  tests/group_by_test.py
Labels: internal

#2531 ci: SQLFrame compat
  docs/basics/order_dependence.md
  tests/expr_and_series/unary_test.py
Labels: internal

#2530 chore: Simplify PySpark std and var
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/utils.py
Labels: internal, pyspark

#2514 chore: Bump version manually only in pyproject.toml
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
  tests/version_test.py
  utils/bump_version.py
  utils/check_api_reference.py
Labels: ci

#2535 fix: Add `new_version.strip()` in `bump_version.py`, otherwise the tag will be invalid
  utils/bump_version.py
Labels: fix, build

#2536 feat: Generate nicer-looking SQL when grouping by expressions
  narwhals/_compliant/group_by.py
  tests/group_by_test.py
Labels: enhancement, duckdb

#2539 chore: Use `not_implemented` some more
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_str.py
Labels: internal

#2285 build: Include tests in source distributions
  .github/workflows/publish_to_pypi.yml
  pyproject.toml
  utils/check_dist_content.py
Labels: build

#2541 release: Bump version to 1.39.0
  pyproject.toml
Labels: release

#2542 TYP: Make `FrameT` more precise
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/typing.py
  narwhals/typing.py
  tpch/__init__.py
  tpch/_typing.py
  tpch/queries/q1.py
  tpch/queries/q10.py
  tpch/queries/q11.py
  tpch/queries/q12.py
  tpch/queries/q13.py
  tpch/queries/q14.py
  tpch/queries/q15.py
  tpch/queries/q16.py
  tpch/queries/q17.py
  tpch/queries/q18.py
  tpch/queries/q19.py
  tpch/queries/q2.py
  tpch/queries/q20.py
  tpch/queries/q21.py
  tpch/queries/q22.py
  tpch/queries/q3.py
  tpch/queries/q4.py
  tpch/queries/q5.py
  tpch/queries/q6.py
  tpch/queries/q7.py
  tpch/queries/q8.py
  tpch/queries/q9.py
Labels: typing

#2545 chore: Reuse SeriesT alias more, make more types TYPE_CHECKING-only
  narwhals/series.py
  narwhals/series_cat.py
  narwhals/series_dt.py
  narwhals/series_list.py
  narwhals/series_str.py
  narwhals/series_struct.py
  narwhals/typing.py
Labels: internal, typing

#2548 chore: type `left_on` / `right_on` tighter at compliant level
  narwhals/_compliant/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/expr.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/expr.py
Labels: internal

#2552 release: Bump version to 1.39.1
  pyproject.toml
Labels: release

#2553 docs: Update docs to reflect Ibis support
  .github/workflows/extremes.yml
  README.md
  docs/index.md
Labels: documentation

#2549 feat: Add support for `Series|Expr.log` method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/log_test.py
Labels: enhancement

#2558 docs: Minor rewording around Ibis commparison
  docs/ecosystem.md
Labels: documentation

#2363 fix: Preserve pandas column name attribute
  narwhals/_pandas_like/dataframe.py
  tests/frame/join_test.py
  tests/preserve_pandas_like_columns_name_attr_test.py
Labels: fix, pandas-like

#2557 test: add Expr.skew test
  tests/expr_and_series/skew_test.py
Labels: internal

#2559 perf: Set pandas attributes inplace when it is safe to do so
  CONTRIBUTING.md
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/utils.py
  tests/frame/group_by_test.py
Labels: performance

#2560 chore: remove redundant storing of `scalar_kwargs` in `EagerExpr`
  narwhals/_compliant/expr.py
Labels: internal

#2562 fix: PySpark like tests
  narwhals/_spark_like/expr.py
  narwhals/functions.py
  tests/expr_and_series/skew_test.py
Labels: fix, spark-like

#2563 chore: Cache ibis columns property
  narwhals/_ibis/dataframe.py
Labels: internal, ibis

#2564 TYP: Enforce 100% type completeness score (PyRight)
  .github/workflows/typing.yml
  narwhals/_expression_parsing.py
Labels: internal, typing

#2561 chore: Redo `CompliantExpr.from_column_indices`
  narwhals/_arrow/expr.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr.py
Labels: internal

#2566 docs: Rewrite overhead section
  docs/overhead.md
Labels: documentation

#2568 chore: Move `_is_naive_format` helper function into utils.py
  narwhals/_ibis/expr_str.py
  narwhals/_spark_like/expr_str.py
  narwhals/utils.py
Labels: internal, spark-like, ibis

#2567 chore: Remap '1q' to '3mo' in `IbisExpr.dt.truncate`
  narwhals/_ibis/expr_dt.py
  tests/expr_and_series/dt/truncate_test.py
Labels: enhancement, ibis

#2555 chore: Rename `call_kwargs` to `scalar_kwargs`
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/typing.py
  narwhals/_compliant/when_then.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
Labels: internal

#2569 docs: Update code of conduct to use organisational email
  .github/CODE_OF_CONDUCT.md
  pyproject.toml
Labels: documentation

#2570 docs: Add docs on how to use Narwhals to generate SQL
  .github/workflows/mkdocs.yml
  docs/concepts/order_dependence.md
  docs/generating_sql.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#2533 feat: modify `rank` so that it works with `over()` for lazy backends
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/typing.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/rank_test.py
Labels: enhancement, duckdb, spark-like

#2574 release: Bump version to 1.40.0
  pyproject.toml
Labels: release

#2579 chore: use `Expression` instead of `duckdb.Expression` for typing
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
Labels: internal

#2581 chore: rename `_input` to `expr` in `_spark_like`, `_ibis`, and `_dask`
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/expr_str.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/expr_list.py
  narwhals/_ibis/expr_str.py
  narwhals/_ibis/expr_struct.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/expr_struct.py
Labels: internal

#2578 chore: Add `_typing_compat` module
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/when_then.py
  narwhals/_translate.py
  narwhals/_typing_compat.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
Labels: internal, typing

#2576 enh: support replace_time_zone(None)
  narwhals/_duckdb/expr_dt.py
  narwhals/_ibis/expr_dt.py
  narwhals/_spark_like/expr_dt.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: enhancement, pyspark, duckdb, pyspark-connect, ibis

#2586 ci: Use Pyright-cov to enforce 100% type coverage
  .github/workflows/typing.yml
Labels: internal

#2587 chore: Use DuckDB 1.3 for typing, remove make typing from `pre-commit`, update `CONTRIBUTING`
  .github/workflows/downstream_tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  pyproject.toml
Labels: internal

#2594 ci: fix typing for pyspark 4.0
  tests/translate/from_native_test.py
Labels: internal

#2595 chore: simplify `broadcast` for spark-like and ibis
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_spark_like/expr.py
Labels: internal

#2601 fix: Fix CI for PySpark 4.0
  narwhals/_spark_like/namespace.py
Labels: pyspark

#2604 ci: pin modin for now
  .github/workflows/pytest.yml
  narwhals/_pandas_like/dataframe.py
Labels: internal

#2590 enh: reflect connection time zone in `Datetime` for DuckDB, support `convert_time_zone` and `replace_time_zone`
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/series.py
  narwhals/_duckdb/utils.py
  tests/conftest.py
  tests/dtypes_test.py
  tests/expr_and_series/dt/convert_time_zone_test.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: enhancement

#2608 fix: Include all backends in `get_native_namespace`
  narwhals/translate.py
  tests/translate/get_native_namespace_test.py
Labels: fix

#2606 fix: spark-like `pass_through=True, eager_only=True` interaction
  narwhals/translate.py
  tests/translate/from_native_test.py
Labels: fix, spark-like

#2610 chore(ruff): Add `tool.ruff.lint.typing-modules`
  pyproject.toml
Labels: internal, typing

#2611 ci: fix native namespace test
  tests/translate/get_native_namespace_test.py
Labels: spark-like

#1842 feat: add `to_string` method to `SparkLikeExprDateTimeNamespace`
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/dt/replace_time_zone_test.py
  tests/expr_and_series/dt/to_string_test.py
Labels: enhancement, spark-like

#2592 enh: reflect connection time zone in Datetime for pyspark, support convert_time_zone and replace_time_zone
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/utils.py
  tests/dtypes_test.py
  tests/expr_and_series/dt/convert_time_zone_test.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: enhancement, pyspark

#2612 ci: remove outdated cudf xfail
  tests/frame/getitem_test.py
Labels: internal, tests

#2615 chore: Remove outdated `_has_default_index` comment
  narwhals/utils.py
Labels: internal, typing, pandas-like

#2616 test: add extra `to_dict` test for v1
  narwhals/stable/v1/__init__.py
  tests/v1_test.py
Labels: internal
