Repository narwhals-dev/narwhals, pull requests merged in 2025-09, with the labels that each got.

#3070 fix: duckdb `Lazyframe.unique` was raising when column name was "group"
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  tests/frame/unique_test.py
Labels: fix

#3071 release: Bump version to 2.3.0
  pyproject.toml
Labels: release

#3073 refactor(expr-ir): Generate dispatch methods (wip)
  narwhals/_plan/arrow/dataframe.py
  narwhals/_plan/arrow/expr.py
  narwhals/_plan/common.py
  narwhals/_plan/protocols.py
Labels: internal

#3068 refactor(expr-ir): Generate dispatch methods
  narwhals/_plan/_immutable.py
  narwhals/_plan/arrow/dataframe.py
  narwhals/_plan/arrow/expr.py
  narwhals/_plan/arrow/namespace.py
  narwhals/_plan/boolean.py
  narwhals/_plan/categorical.py
  narwhals/_plan/common.py
  narwhals/_plan/demo.py
  narwhals/_plan/expr.py
  narwhals/_plan/expr_expansion.py
  narwhals/_plan/functions.py
  narwhals/_plan/literal.py
  narwhals/_plan/name.py
  narwhals/_plan/operators.py
  narwhals/_plan/options.py
  narwhals/_plan/protocols.py
  narwhals/_plan/ranges.py
  narwhals/_plan/schema.py
  narwhals/_plan/selectors.py
  narwhals/_plan/strings.py
  narwhals/_plan/struct.py
  narwhals/_plan/when_then.py
  narwhals/_plan/window.py
  tests/plan/immutable_test.py
Labels: internal

#3082 refactor(expr-ir): Generalize `__replace__`, `map_ir`
  narwhals/_plan/_immutable.py
  narwhals/_plan/aggregation.py
  narwhals/_plan/common.py
  narwhals/_plan/expr.py
  narwhals/_plan/expr_expansion.py
  narwhals/_plan/expr_rewrites.py
  narwhals/_plan/name.py
  narwhals/_plan/typing.py
Labels: internal

#3016 feat(typing): Make `Implementation` less opaque
  .github/workflows/typing.yml
  Makefile
  docs/api-reference/dataframe.md
  docs/api-reference/lazyframe.md
  narwhals/_namespace.py
  narwhals/_pandas_like/utils.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/is_close_test.py
  tests/implementation_test.py
  tests/namespace_test.py
  utils/check_api_reference.py
Labels: enhancement, fix, typing, tests

#3089 refactor(expr-ir): Shrink `expr_expansion`
  narwhals/_plan/expr_expansion.py
  narwhals/_plan/meta.py
Labels: internal

#3091 refactor(expr-ir): Make use of long lines
  narwhals/_plan/common.py
  narwhals/_plan/expr_rewrites.py
  narwhals/_plan/meta.py
  narwhals/_plan/operators.py
  narwhals/_plan/schema.py
  narwhals/_plan/selectors.py
  narwhals/_plan/when_then.py
Labels: internal

#3094 refactor(expr-ir): Shrink protocols
  narwhals/_plan/arrow/namespace.py
  narwhals/_plan/protocols.py
Labels: internal

#3090 chore: Rename `_typing.*Cudf*` aliases to `*CuDF*`
  narwhals/_typing.py
  narwhals/_utils.py
Labels: internal, typing

#3096 chore(typing): enable `reportIncompatibleMethodOverride` in pyright
  narwhals/_arrow/series.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_sql/expr.py
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v2/__init__.py
  pyproject.toml
Labels: internal, typing

#3007 feat: Warn on incompatible `TimeUnit` in `pandas<2`
  narwhals/_pandas_like/utils.py
  tests/dtypes_test.py
Labels: error reporting, pandas-like

#3105 fix: allow for `fill_null` with aggregate expression
  narwhals/expr.py
  tests/expr_and_series/fill_null_test.py
Labels: fix

#3106 chore: simplify parsing expressions in group-by
  narwhals/_compliant/series.py
  narwhals/_expression_parsing.py
  narwhals/_polars/series.py
  narwhals/dataframe.py
  narwhals/group_by.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/frame/group_by_test.py
Labels: internal

#3126 chore: Upgrade ruff to `v0.13.0` and fix related issues in `tests/`
  .pre-commit-config.yaml
  pyproject.toml
  tests/expr_and_series/bool_test.py
  tests/expr_and_series/is_in_test.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/median_test.py
  tests/expr_and_series/quantile_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/frame/concat_test.py
  tests/frame/estimated_size_test.py
  tests/frame/get_column_test.py
  tests/frame/getitem_test.py
  tests/frame/join_test.py
  tests/frame/select_test.py
  tests/series_only/from_iterable_test.py
  tests/translate/from_native_test.py
  tests/translate/narwhalify_test.py
  tests/v1_test.py
  tests/v2_test.py
Labels: internal

#3135 test(typing): fix `pickle_test` using `Sequence`
  tests/pickle_test.py
Labels: typing, tests

#3127 chore: Support `@requires.backend_version` in namespaces
  narwhals/_arrow/series_cat.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_list.py
  narwhals/_arrow/series_str.py
  narwhals/_arrow/series_struct.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/typing.py
  narwhals/_polars/expr.py
  narwhals/_polars/typing.py
  narwhals/_polars/utils.py
  narwhals/_utils.py
  tests/utils_test.py
Labels: error reporting, developer tools

#3139 refactor(typing): Remove now-unused `isinstance_or_issubclass` overloads
  narwhals/_utils.py
Labels: dtypes, internal, typing

#3144 chore(typing): pyright ignore `pl.UInt128`
  narwhals/_polars/utils.py
Labels: typing

#3159 enh: support `n_unique` with `over` across all backends
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_sql/expr.py
  tests/expr_and_series/n_unique_test.py
Labels: enhancement

#3161 enh: support `skew` with `over`
  narwhals/_duckdb/expr.py
  tests/expr_and_series/skew_test.py
Labels: enhancement

#3162 release: Bump version to 2.6.0
  pyproject.toml
Labels: release

#3148 feat: Add `{nw,DataFrame}.from_dicts`
  docs/api-reference/dataframe.md
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/utils.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v2/__init__.py
  tests/frame/from_dicts_test.py
  tests/from_dicts_test.py
  tests/v1_test.py
  tests/v2_test.py
Labels: enhancement, eager-only
