Repository narwhals-dev/narwhals, pull requests merged in 2025-08, with the labels that each got.

#2914 refactor: Reduce returns in `Namespace.from_native_object`
  narwhals/_namespace.py
Labels: internal

#2919 fix: Use updated `from_arrow` import for `modin`
  narwhals/_pandas_like/dataframe.py
  tests/frame/from_arrow_test.py
Labels: fix, bug: it raises an error but shouldn't, pandas-like

#2929 refactor: Shrink `Polars*Namespace(s)`, but more
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal, polars

#2918 chore(typing): Fix `(Compliant|Polars)Series` namespaces
  narwhals/_compliant/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal, typing, polars

#2897 refactor: Shrink `Polars*Namespace`(s)
  narwhals/_compliant/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/typing.py
  narwhals/_polars/utils.py
  narwhals/_utils.py
Labels: internal, polars

#2931 docs: Enable darglint for dataframe and series modules
  .pre-commit-config.yaml
  narwhals/dataframe.py
  narwhals/series.py
Labels: documentation

#2935 feat: Add `is_boolean` method to `DType`.
  narwhals/dtypes.py
  tests/dtypes_test.py
Labels: enhancement

#2937 test: include nulls in `unique` test
  tests/expr_and_series/unique_test.py
Labels: internal

#2946 chore: Simplify polars `.list.unique`
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
Labels: internal, polars

#2954 test: unxfail `pandas[pyarrow]` series slice on nightly
  tests/expr_and_series/list/unique_test.py
  tests/frame/getitem_test.py
Labels: ci, tests, pandas-like

#2950 fix: Allow `modin[pyarrow]` to use more dtypes
  narwhals/_pandas_like/utils.py
  tests/dtypes_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/list/len_test.py
  tests/frame/explode_test.py
Labels: dtypes, bug: it raises an error but shouldn't, nested data, modin

#2920 chore: fixup operator type ignores for `SQLExpr`
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_sql/expr.py
Labels: internal

#2942 feat: add `list.contains`
  docs/api-reference/expr_list.md
  docs/api-reference/series_list.md
  narwhals/_arrow/series_list.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_duckdb/expr_list.py
  narwhals/_ibis/expr_list.py
  narwhals/_pandas_like/series_list.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr_list.py
  narwhals/expr_list.py
  narwhals/series_list.py
  tests/expr_and_series/list/contains_test.py
Labels: enhancement

#2945 feat(typing): Add `IntoSchema` alias
  docs/api-reference/typing.md
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/typing.py
Labels: documentation, enhancement, typing

#2951 chore: Refactor SQLExprDateTimeNamespace
  narwhals/_duckdb/expr_dt.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/utils.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_sql/expr.py
  narwhals/_sql/expr_dt.py
Labels: internal

#2953 fix: Support passing `nw.Object` to pandas-like
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/utils.py
  tests/frame/from_dict_test.py
Labels: dtypes, fix, pandas-like

#2966 ci: Fix hierarchicalforecast downstream test
  .github/workflows/downstream_tests.yml
Labels: ci

#2976 release: Bump version to 2.1.1
  pyproject.toml
Labels: release

#2962 feat: Add `{Expr,Series}.is_close`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/_compliant/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  pyproject.toml
  tests/expr_and_series/is_close_test.py
Labels: enhancement

#2982 docs: remove now-redundant "returns" sections from docstrings
  .pre-commit-config.yaml
  narwhals/_compliant/group_by.py
  narwhals/_namespace.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/dtypes.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/expr_struct.py
  narwhals/group_by.py
  narwhals/schema.py
  narwhals/series.py
  narwhals/series_cat.py
  narwhals/series_dt.py
  narwhals/series_list.py
  narwhals/series_str.py
  narwhals/series_struct.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#2969 feat: Add `DType.base_type`
  narwhals/_arrow/utils.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/utils.py
  narwhals/_ibis/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
  tests/dtypes_test.py
Labels: enhancement, dtypes, performance

#2967 refactor: Add `CompliantColumn`
  narwhals/_arrow/series.py
  narwhals/_compliant/column.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/_compliant/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
Labels: internal

#2996 Revert "fix: Use importlib for polars version (#2952)", xfail `map_batches` test for now
  .github/workflows/extremes.yml
  narwhals/_utils.py
  tests/expr_and_series/map_batches_test.py
  tests/utils.py
Labels: fix

#2997 release: Bump version to 2.1.2
  pyproject.toml
Labels: release

#2999 docs: Include `DType` methods, properties in API Reference
  docs/api-reference/dtypes.md
  narwhals/dtypes.py
  tests/dtypes_test.py
  utils/check_api_reference.py
Labels: documentation, dtypes

#2933 feat: Add `Series.from_iterable`
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v2/__init__.py
  tests/conftest.py
  tests/series_only/from_iterable_test.py
  tests/series_only/from_numpy_test.py
  tests/utils.py
  tests/v1_test.py
  tests/v2_test.py
  utils/check_api_reference.py
Labels: enhancement, fix, high priority

#3002 feat(typing): Make `IntoBackend` generic
  docs/api-reference/typing.md
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_typing.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v2/__init__.py
  narwhals/typing.py
  tests/conftest.py
  tests/frame/collect_test.py
  tests/frame/from_arrow_test.py
  tests/frame/from_dict_test.py
  tests/frame/from_numpy_test.py
  tests/frame/lazy_test.py
  tests/from_dict_test.py
  tests/namespace_test.py
  tests/read_scan_test.py
  tests/series_only/from_iterable_test.py
  tests/series_only/from_numpy_test.py
  tests/v1_test.py
  tests/v2_test.py
Labels: enhancement, typing

#2985 fix: expr & series bool ambiguity
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/bool_test.py
  tests/frame/columns_test.py
  tests/series_only/sort_test.py
Labels: fix

#3015 ci: Remove `duckdb` nightly from cov
  .github/workflows/pytest.yml
Labels: ci, fix, duckdb, sqlframe

#2944 fix(typing): Avoid overlapping `DataFrame`, `LazyFrame`
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/typing.py
  narwhals/_interchange/dataframe.py
  narwhals/_namespace.py
  narwhals/_sql/dataframe.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/typing.py
  narwhals/stable/v2/__init__.py
  narwhals/stable/v2/typing.py
  narwhals/translate.py
  narwhals/typing.py
  tests/conftest.py
  tests/expr_and_series/dt/datetime_attributes_test.py
  tests/expr_and_series/struct_/field_test.py
  tests/frame/join_test.py
  tests/frame/sample_test.py
  tests/frame/with_row_index_test.py
  tests/preserve_pandas_like_columns_name_attr_test.py
  tests/tpch_q1_test.py
  tests/translate/from_native_test.py
  tests/utils.py
  tests/v1_test.py
Labels: fix, high priority, typing

#3033 test(typing): Avoid masking fixed overloads
  tests/expr_and_series/rolling_var_test.py
  tests/frame/invalid_test.py
  tests/series_only/is_ordered_categorical_test.py
  tests/translate/get_native_namespace_test.py
  tests/utils.py
  tests/utils_test.py
Labels: fix, typing, tests

#3034 chore: xfail top k multiple in old polars
  tests/frame/top_k_test.py
Labels: internal

#3030 feat: Add `{Expr,Series}.fill_nan`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/series.py
  narwhals/_compliant/column.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_sql/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/fill_nan_test.py
Labels: enhancement

#3039 chore(typing): Ignore inferred type in `dask_expr.Series.mask`
  narwhals/_dask/expr.py
Labels: internal, typing, dask

#3036 release: Bump version to 2.2.0
  pyproject.toml
Labels: release

#3041 refactor(typing): Remove `CompliantDataFrame.collect`
  narwhals/_compliant/dataframe.py
Labels: internal, typing, extensibility

#3046 fix(ci): Disallow `sqlframe==3.39.3`
  pyproject.toml
Labels: ci, dependencies

#2886 feat: add multivalue replacement in `.str.replace[_all]`
  narwhals/_arrow/series_str.py
  narwhals/_dask/expr_str.py
  narwhals/_ibis/expr_str.py
  narwhals/_pandas_like/series_str.py
  narwhals/_sql/expr_str.py
  narwhals/expr_str.py
  narwhals/series_str.py
  tests/expr_and_series/str/replace_test.py
Labels: enhancement

#3049 docs: update image to include duck
  README.md
  docs/assets/image.png
Labels: documentation

#2957 feat: Add `Schema.from_{native,<backend>}`
  docs/api-reference/schema.md
  narwhals/_pandas_like/utils.py
  narwhals/dependencies.py
  narwhals/schema.py
  narwhals/typing.py
  tests/conftest.py
  tests/frame/schema_test.py
  tests/utils.py
  utils/check_api_reference.py
Labels: enhancement, dtypes, eager-only

#3050 chore: remove (internal) `ExprKind.NARY`
  narwhals/_expression_parsing.py
Labels: internal

#3056 refactor: Add `CompliantFrame` protocol
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/typing.py
  narwhals/_sql/group_by.py
  narwhals/_utils.py
Labels: internal, typing

#3054 refactor: Split up `BaseFrame._extract_compliant`
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_expression_parsing.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal, extensibility

#3053 refactor(expr-ir): Clearing out the cobwebs
  narwhals/_plan/aggregation.py
  narwhals/_plan/arrow/dataframe.py
  narwhals/_plan/arrow/functions.py
  narwhals/_plan/categorical.py
  narwhals/_plan/common.py
  narwhals/_plan/demo.py
  narwhals/_plan/dummy.py
  narwhals/_plan/expr.py
  narwhals/_plan/expr_expansion.py
  narwhals/_plan/functions.py
  narwhals/_plan/lists.py
  narwhals/_plan/literal.py
  narwhals/_plan/name.py
  narwhals/_plan/operators.py
  narwhals/_plan/options.py
  narwhals/_plan/protocols.py
  narwhals/_plan/ranges.py
  narwhals/_plan/strings.py
  narwhals/_plan/temporal.py
  narwhals/_plan/when_then.py
  narwhals/_plan/window.py
Labels: internal

#3045 refactor: Organizing `Compliant*` APIs
  narwhals/_arrow/expr.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/group_by.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/_sql/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal, extensibility

#3063 refactor(expr-ir): `copy.replace` most `with_*` methods
  narwhals/_plan/aggregation.py
  narwhals/_plan/common.py
  narwhals/_plan/expr.py
  narwhals/_plan/expr_expansion.py
  narwhals/_plan/name.py
Labels: internal
