Repository narwhals-dev/narwhals, pull requests merged in 2025-01, with the labels that each got.

#1694 test: Make constructors configurable when running tests
  .github/workflows/check_tpch_queries.yml
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
  CONTRIBUTING.md
  narwhals/_pandas_like/group_by.py
  noxfile.py
  pyproject.toml
  tests/conftest.py
  tests/dtypes_test.py
  tests/expr_and_series/over_test.py
  tests/frame/drop_test.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/interchange_schema_test.py
  tests/frame/interchange_select_test.py
  tests/frame/interchange_to_arrow_test.py
  tests/frame/interchange_to_pandas_test.py
  tests/frame/schema_test.py
  tests/group_by_test.py
  tests/hypothesis/getitem_test.py
  tpch/generate_data.py
Labels: internal

#1687 fix: remove `maintain_order` from LazyFrame.unique
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/unique_test.py
  tests/spark_like_test.py
Labels: fix

#1693 feat: add `sum` and `sum_horizontal` for `SparkLike`
  docs/installation.md
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  tests/spark_like_test.py
Labels: enhancement

#1698 test: allow to run tests for Polars[gpu]
  CONTRIBUTING.md
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/group_by_test.py
  tests/read_scan_test.py
  tests/tpch_q1_test.py
  tests/utils.py
Labels: internal

#1697 chore: use `None` instead of `float('nan')` to check for null values in tests
  tests/expr_and_series/fill_null_test.py
  tests/expr_and_series/max_horizontal_test.py
  tests/expr_and_series/mean_horizontal_test.py
  tests/expr_and_series/min_horizontal_test.py
  tests/expr_and_series/rolling_mean_test.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/rolling_var_test.py
  tests/expr_and_series/skew_test.py
  tests/expr_and_series/unary_test.py
  tests/expr_and_series/when_test.py
  tests/frame/drop_nulls_test.py
  tests/frame/join_test.py
  tests/frame/pivot_test.py
  tests/frame/sort_test.py
  tests/group_by_test.py
  tests/hypothesis/join_test.py
  tests/spark_like_test.py
  tests/utils.py
Labels: internal

#1699 docs: `Series` method' docstrings
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1625 feat: add is_nan expression & series method
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/is_nan_test.py
Labels: enhancement

#1710 docs: add spark-like in backend completeness
  utils/generate_backend_completeness.py
Labels: documentation

#1716 docs: update null handling page with `is_nan` reference
  docs/pandas_like_concepts/null_handling.md
Labels: documentation

#1706 fix: `DaskLazyFrame` and `ArrowDataFrame` `.with_row_index` column order
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/utils.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/expr_and_series/double_test.py
  tests/frame/double_test.py
  tests/frame/join_test.py
  tests/frame/pivot_test.py
  tests/frame/with_row_index_test.py
  tests/spark_like_test.py
  tests/utils.py
Labels: fix

#1700 docs: let `nw.LazyFrame` docstrings examples run on Polars and Dask only
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1718 fix: Catch cuDF warning for concat with empty elements, and ComputeError for non-float is_nan
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/is_nan_test.py
Labels: internal

#1676 fix: dask group by with kwargs
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  tests/group_by_test.py
Labels: fix, high priority

#1709 feat: Expressify `clip` arguments
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/clip_test.py
Labels: enhancement

#1717 feat: enable to cast to `Struct` dtype
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  tests/expr_and_series/cast_test.py
Labels: enhancement

#1719 chore: remove some lazy tests
  docs/backcompat.md
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/expr_and_series/arg_max_test.py
  tests/expr_and_series/arg_min_test.py
  tests/expr_and_series/arg_true_test.py
  tests/expr_and_series/drop_nulls_test.py
  tests/expr_and_series/ewm_test.py
  tests/expr_and_series/filter_test.py
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/head_test.py
  tests/expr_and_series/len_test.py
  tests/expr_and_series/map_batches_test.py
  tests/expr_and_series/mode_test.py
  tests/expr_and_series/rolling_mean_test.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/rolling_var_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/tail_test.py
  tests/expr_and_series/unique_test.py
  tests/expr_and_series/when_test.py
  tests/frame/filter_test.py
  tests/frame/with_columns_sequence_test.py
  tests/spark_like_test.py
Labels: internal

#1720 chore: simplify definitions of rhs expressions, bump dask minimum to 2024.10
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/typing.py
  pyproject.toml
  tests/frame/lit_test.py
  tests/selectors_test.py
Labels: fix

#1691 tests: remove unnecessary pytest filterwarnings
  pyproject.toml
  tests/spark_like_test.py
Labels: internal

#1727 feat: validate library minimum version in compliant objects
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_spark_like/dataframe.py
  narwhals/dependencies.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/expr_and_series/clip_test.py
Labels: enhancement

#1730 fix: nw.lit(date, dtype=nw.Date), loosen Dask minimum back to 2024.8
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  pyproject.toml
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/operators_test.py
  tests/frame/select_test.py
  tests/series_only/cast_test.py
  tests/tpch_q1_test.py
Labels: fix

#1731 chore: refactor root_names and output_names tracking
  narwhals/_dask/expr.py
  narwhals/_expression_parsing.py
  narwhals/_spark_like/expr.py
  pyproject.toml
Labels: internal

#1732 fix: fix broken link from warning
  narwhals/_pandas_like/group_by.py
  narwhals/_spark_like/group_by.py
Labels: fix

#1733 docs: `Expr` method' docstrings
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#1735 test: catch some cudf failures
  pyproject.toml
  tests/expr_and_series/clip_test.py
  tests/expr_and_series/lit_test.py
Labels: internal

#1738 release: Bump version to 1.21.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1740 docs: update api-completeness with `duckdb`
  docs/basics/dataframe_conversion.md
  utils/generate_backend_completeness.py
Labels: documentation

#1744 chore: increase PySpark min version to `3.5.0`
  .github/workflows/extremes.yml
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/utils.py
  pyproject.toml
Labels: dependencies

#1746 chore: filter old pyarrow/pandas warnings we cant do anything about
  tests/frame/to_arrow_test.py
  tests/frame/write_parquet_test.py
Labels: internal

#1342 feat: add `Series|Expr.rank`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/rank_test.py
Labels: enhancement

#1748 test: remove `cudf` from `tests/expr_and_series/replace_time_zone_test.py::test_replace_time_zone_none[cudf]`
  tests/expr_and_series/replace_time_zone_test.py
Labels: internal

#1751 fix: fix license classifier
  pyproject.toml
  tests/expr_and_series/rolling_mean_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/rolling_var_test.py
Labels: fix

#1752 release: Bump version to 1.21.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1759 feat: implement when/then/otherwise for DuckDB
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/utils.py
  tests/expr_and_series/when_test.py
  tpch/execute.py
Labels: enhancement

#1766 docs: fix `is_between` type hint in signature
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/is_between_test.py
  tests/spark_like_test.py
Labels: documentation

#1768 chore: dask nightly
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/translate.py
Labels: internal

#1767 feat: semi-join for duckdb
  narwhals/_duckdb/dataframe.py
  tests/frame/join_test.py
  tpch/execute.py
Labels: enhancement

#1773 feat: implement cross-join for duckdb
  .github/workflows/check_tpch_queries.yml
  .github/workflows/extremes.yml
  narwhals/_duckdb/dataframe.py
  tests/frame/join_test.py
  tests/utils.py
  tpch/execute.py
Labels: enhancement

#1708 feat: add missing dunder methods in `SparkLikeExpr` and `SparkLikeNamespace.lit`
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  tests/spark_like_test.py
Labels: enhancement

#1775 fix: duckdb join was failing if column names contained spaces
  narwhals/_duckdb/dataframe.py
  tests/frame/join_test.py
  tests/frame/sort_test.py
Labels: fix

#1781 feat: add `SparkLikeStrNamespace` methods
  narwhals/_spark_like/expr.py
  pyproject.toml
  tests/conftest.py
  tests/expr_and_series/str/contains_test.py
  tests/expr_and_series/str/head_test.py
  tests/expr_and_series/str/len_chars_test.py
  tests/expr_and_series/str/replace_test.py
  tests/expr_and_series/str/slice_test.py
  tests/expr_and_series/str/starts_with_ends_with_test.py
  tests/expr_and_series/str/strip_chars_test.py
  tests/expr_and_series/str/tail_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/utils.py
Labels: enhancement

#1779 feat: `SparkLikeNamespace` methods
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  tests/expr_and_series/any_horizontal_test.py
  tests/expr_and_series/concat_str_test.py
  tests/expr_and_series/is_null_test.py
  tests/expr_and_series/len_test.py
  tests/expr_and_series/max_horizontal_test.py
  tests/expr_and_series/mean_horizontal_test.py
  tests/expr_and_series/min_horizontal_test.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/unary_test.py
  tests/frame/concat_test.py
  tests/group_by_test.py
Labels: enhancement

#1777 feat: implement anti-join, str.len_chars, and null_count for DuckDB
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/dataframe.py
  tests/expr_and_series/null_count_test.py
  tests/expr_and_series/str/len_chars_test.py
  tests/frame/join_test.py
Labels: enhancement

#1784 feat: duckdb replace_all with regex
  narwhals/_duckdb/expr.py
  tests/expr_and_series/str/replace_test.py
Labels: enhancement

#1788 docs: Restore API complentess page
  mkdocs.yml
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_cat.py
  narwhals/_arrow/expr_dt.py
  narwhals/_arrow/expr_list.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/expr_str.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_cat.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_list.py
  narwhals/_arrow/series_str.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/expr_name.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_str.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_cat.py
  narwhals/_pandas_like/expr_dt.py
  narwhals/_pandas_like/expr_list.py
  narwhals/_pandas_like/expr_name.py
  narwhals/_pandas_like/expr_str.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_cat.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/series_str.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_str.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  utils/generate_backend_completeness.py
Labels: documentation

#1785 fix: fix skew for duckdb with fewer than 3 elements
  narwhals/_duckdb/expr.py
  tests/expr_and_series/unary_test.py
Labels: fix

#1783 feat: add extra overload for concat for when it is not known statically whether inputs are eager or lazy
  docs/api-completeness/index.md
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/invalid_test.py
Labels: enhancement

#1795 feat: DuckDB `dt.weekday`
  narwhals/_duckdb/expr_dt.py
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: enhancement

#1796 feat: DuckDB `dt.ordinal_day`
  narwhals/_duckdb/expr_dt.py
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: enhancement

#1794 feat: DuckDB `dt.to_string`
  narwhals/_duckdb/expr_dt.py
  tests/expr_and_series/dt/to_string_test.py
Labels: enhancement

#1792 chore: factor out check_columns_exist
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/utils.py
  tests/utils_test.py
Labels: internal

#1798 feat: DuckDB `date`
  narwhals/_duckdb/expr_dt.py
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: enhancement

#1799 feat: improve error message on check_columns_exist
  narwhals/utils.py
  tests/utils_test.py
Labels: enhancement

#1800 fix: to_py_scalar was raising for decimals
  narwhals/translate.py
  tests/translate/to_py_scalar_test.py
Labels: fix

#1804 release: Bump version to 1.22.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1805 feat: add support for `SparkLikeNamespace.when`
  narwhals/_spark_like/namespace.py
  tests/expr_and_series/when_test.py
Labels: enhancement

#1803 feat: add `DataFrame` and `Series` `to_polars`
  docs/api-reference/dataframe.md
  docs/api-reference/series.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/dataframe.py
  narwhals/series.py
  tests/frame/to_polars_test.py
  tests/series_only/to_polars_test.py
  utils/check_api_reference.py
Labels: enhancement

#1810 patch: fix when-then double lit case
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_pandas_like/namespace.py
  tests/expr_and_series/when_test.py
Labels: fix

#1791 feat: deprecate Expr.head, Expr.tail, Expr.sort, Expr.gather_every, Expr.sample (but keep them in stable.v1)
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/head_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/sort_test.py
  tests/expr_and_series/tail_test.py
Labels: enhancement

#1814 fix: raise on shape mismatch in filter
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/dataframe.py
  tests/frame/filter_test.py
Labels: fix

#1817 ci: downstream test for formulaic
  .github/workflows/downstream_tests.yml
Labels: ci

#1816 feat: add `AnonymousExprError`
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/group_by.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_name.py
  narwhals/_dask/group_by.py
  narwhals/_duckdb/group_by.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_name.py
  narwhals/_pandas_like/group_by.py
  narwhals/_spark_like/group_by.py
  narwhals/exceptions.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  tests/group_by_test.py
Labels: enhancement

#1809 feat: pyspark and duckdb `Expr.name` namespace
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_name.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_name.py
  tests/conftest.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
Labels: enhancement

#1812 feat: add `SparkExpr.cast` for basic types
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  narwhals/exceptions.py
  tests/conftest.py
  tests/expr_and_series/cast_test.py
  tests/group_by_test.py
Labels: enhancement

#1806 feat: Disallow order-dependent expressions from being passed to nw.LazyFrame
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/utils.py
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/exceptions.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/functions.py
  narwhals/selectors.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/cum_count_test.py
  tests/expr_and_series/cum_max_test.py
  tests/expr_and_series/cum_min_test.py
  tests/expr_and_series/cum_prod_test.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/mode_test.py
  tests/expr_and_series/order_dependent_lazy_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/shift_test.py
  tests/frame/join_test.py
  tests/frame/sample_test.py
  tests/frame/schema_test.py
  tests/group_by_test.py
  tests/new_series_test.py
  tests/no_imports_test.py
  tests/series_only/alias_rename_test.py
  tests/tpch_q1_test.py
  tests/translate/from_native_test.py
  utils/check_api_reference.py
Labels: enhancement

#1824 chore: refactor pandas-like `narwhals_to_native_dtype`
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
Labels: internal

#1819 feat: pyspark group by `n_unique` and no aggregation
  narwhals/_spark_like/group_by.py
  tests/group_by_test.py
Labels: enhancement

#1808 feat: add `.over` method for `SparkLikeExpr`
  narwhals/_spark_like/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#1831 feat: add total duration methods for DuckDB
  narwhals/_duckdb/expr_dt.py
  tests/expr_and_series/dt/datetime_duration_test.py
Labels: enhancement

#1826 feat: add pyspark str namespace `to_datetime`
  narwhals/_spark_like/expr_str.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: enhancement

#1835 feat: add `Expr.dt` methods to `PySpark`
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  tests/expr_and_series/dt/datetime_attributes_test.py
Labels: enhancement

#1834 test: decouple pyspark constructor from pandas
  tests/conftest.py
  tests/expr_and_series/arg_max_test.py
  tests/expr_and_series/arg_min_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/double_selected_test.py
  tests/expr_and_series/double_test.py
  tests/expr_and_series/fill_null_test.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/max_test.py
  tests/expr_and_series/mean_test.py
  tests/expr_and_series/median_test.py
  tests/expr_and_series/min_test.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/nth_test.py
  tests/expr_and_series/null_count_test.py
  tests/expr_and_series/quantile_test.py
  tests/expr_and_series/std_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/expr_and_series/sum_test.py
  tests/expr_and_series/unary_test.py
  tests/expr_and_series/var_test.py
  tests/frame/add_test.py
  tests/frame/columns_test.py
  tests/frame/concat_test.py
  tests/frame/double_test.py
  tests/frame/drop_test.py
  tests/frame/filter_test.py
  tests/frame/head_test.py
  tests/frame/invalid_test.py
  tests/frame/is_duplicated_test.py
  tests/frame/is_empty_test.py
  tests/frame/is_unique_test.py
  tests/frame/item_test.py
  tests/frame/join_test.py
  tests/frame/reindex_test.py
  tests/frame/rename_test.py
  tests/frame/rows_test.py
  tests/frame/schema_test.py
  tests/frame/select_test.py
  tests/frame/sort_test.py
  tests/frame/tail_test.py
  tests/frame/to_arrow_test.py
  tests/frame/to_dict_test.py
  tests/frame/to_native_test.py
  tests/frame/to_numpy_test.py
  tests/frame/to_pandas_test.py
  tests/frame/to_polars_test.py
  tests/frame/unique_test.py
  tests/frame/with_columns_test.py
  tests/group_by_test.py
  tests/series_only/is_sorted_test.py
Labels: internal, tests, pyspark

#1833 fix: when/then/otherwise output name was not consistent across backends
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/when_test.py
Labels: fix

#1827 feat: Deprecate Expr.arg_true (but keep Series.arg_true, and keep both available in stable.v1)
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/arg_true_test.py
Labels: enhancement

#1830 chore: rename time zone tests
  narwhals/_spark_like/expr_dt.py
  tests/expr_and_series/dt/convert_time_zone_test.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: enhancement, pyspark

#1825 feat: add `is_nan` and `is_finite` for duckdb, `is_nan` for pyspark
  narwhals/_duckdb/expr.py
  narwhals/_spark_like/expr.py
  tests/expr_and_series/is_finite_test.py
  tests/expr_and_series/is_nan_test.py
Labels: enhancement

#1829 feat: remove `eager_or_interchange` from `from_native` in main namespace, switch Ibis' support from interchange to lazy in main namespace (but preserve status-quo in stable.v1)
  docs/backcompat.md
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/translate.py
  pyproject.toml
  tests/expr_and_series/dt/datetime_attributes_test.py
  tests/frame/join_test.py
  tests/ibis_test.py
  tests/stable_api_test.py
  tests/translate/from_native_test.py
Labels: enhancement

#1837 test: fixup test suite for cudf.pandas
  narwhals/_pandas_like/utils.py
  tests/utils.py
Labels: internal

#1838 chore: simplify imports
  .github/workflows/pytest.yml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_cat.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_list.py
  narwhals/_arrow/series_str.py
  narwhals/_arrow/utils.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr_str.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  tests/no_imports_test.py
Labels: internal

#1839 feat: deprecate `maintain_order` in `Expr.unique` and `LazyFrame.tail` (but keep around in `stable.v1`)
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/conftest.py
  tests/expr_and_series/unique_test.py
  tests/frame/tail_test.py
  tests/stable_api_test.py
Labels: enhancement

#1841 release: Bump version to 1.23.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1847 chore: simplify internal renaming in _pandas_like/series.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_list.py
Labels: internal

#1845 chore: validate expressions shape at narwhals/expr.py level
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/dataframe.py
  narwhals/functions.py
  tests/expr_and_series/when_test.py
  tests/frame/filter_test.py
Labels: internal

#1850 feat: add DuckDB `list.len` method
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_list.py
  narwhals/_duckdb/utils.py
  tests/conftest.py
Labels: enhancement

#1851 feat: add DuckDB `Struct` dtype
  narwhals/_duckdb/utils.py
  tests/expr_and_series/cast_test.py
Labels: enhancement

#1854 fix: raise on selectors addition
  narwhals/_arrow/selectors.py
  narwhals/_dask/selectors.py
  narwhals/_pandas_like/selectors.py
  narwhals/selectors.py
  tests/selectors_test.py
Labels: fix

#1858 feat: allow any ddof value for duckdb `var` and `std`
  narwhals/_duckdb/expr.py
  tests/expr_and_series/std_test.py
  tests/expr_and_series/var_test.py
  tests/group_by_test.py
Labels: enhancement, duckdb

#1857 patch: fix duckdb `narwhals_to_native_dtype` for `Int32` and `UInt32`
  narwhals/_duckdb/utils.py
  tests/expr_and_series/cast_test.py
Labels: fix, duckdb

#1856 chore: parse strings as columns names at narwhals-level
  docs/extending.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/typing.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/group_by.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/group_by.py
  narwhals/_polars/namespace.py
  narwhals/_polars/typing.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/typing.py
  narwhals/_spark_like/utils.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/group_by.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  tests/expr_and_series/clip_test.py
  tests/expr_and_series/concat_str_test.py
  tests/expr_and_series/is_between_test.py
  tests/frame/invalid_test.py
  tests/frame/select_test.py
Labels: internal

#1860 feat: add DuckDB `join_asof`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/join_test.py
Labels: enhancement, duckdb

#1862 test: skip Ibis tests if deps aren't installed, set defaults in `PandasLikeSeries.__array__` to fix cuDF is_in
  narwhals/_pandas_like/series.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/interchange_schema_test.py
  tests/frame/interchange_select_test.py
  tests/frame/interchange_to_arrow_test.py
  tests/frame/interchange_to_pandas_test.py
Labels: internal

#1867 feat: raise if expression changes length in `.over()`
  narwhals/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#1866 feat: completely refactor alias tracking and support `nw.all`, `nw.nth`, and selectors across the API
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_name.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_name.py
  narwhals/_duckdb/group_by.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_name.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  narwhals/exceptions.py
  narwhals/typing.py
  narwhals/utils.py
  tests/expr_and_series/n_unique_test.py
  tests/expr_and_series/name/keep_test.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/frame/select_test.py
  tests/group_by_test.py
  tests/stable_api_test.py
Labels: enhancement

#1869 fix: `nw.selectors.by_dtype(nw.Datetime)` was excluding tz-aware for Polars
  narwhals/_polars/namespace.py
  tests/selectors_test.py
Labels: fix

#1872 fix: address `&` / `|` operator errors for PySpark / chore: use F.lit in maybe_evaluate for pyspark, like we do for duckdb
  .github/workflows/downstream_tests.yml
  narwhals/_dask/group_by.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_name.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/series.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_spark_like/utils.py
  narwhals/typing.py
  tests/conftest.py
  tests/expr_and_series/operators_test.py
Labels: internal, fix

#1870 fix: support various reductions in pyspark
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/utils.py
  pyproject.toml
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/reduction_test.py
  tests/stable_api_test.py
Labels: fix, pyspark

#1873 release: Bump version to 1.24.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1877 feat: support more scalar operations for duckdb, Increase width for ipython
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_list.py
  narwhals/_duckdb/expr_name.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_duckdb/utils.py
  narwhals/utils.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tpch/execute.py
Labels: enhancement

#1878 chore: remove unused `_depth` from `DuckDBExpr` and `SparkLikeExpr`
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_name.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
Labels: internal

#1879 chore: use positional-only arg in evaluate_into_exprs
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
Labels: internal

#1881 chore: add "typing :: typed" classifier to pyproject.toml
  pyproject.toml
Labels: internal

#1880 feat: move robust literal handling for PySpark
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_spark_like/utils.py
Labels: enhancement

#1883 feat: start (silently) adding support for SQLFrame
  .github/workflows/mkdocs.yml
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_name.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_spark_like/utils.py
  narwhals/dependencies.py
  narwhals/translate.py
  narwhals/utils.py
  pyproject.toml
  tests/conftest.py
Labels: enhancement

#1885 release: Bump version to 1.24.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#1904 docs(ecosystem.md): add `pointblank` to Used By section
  docs/ecosystem.md
Labels: documentation

#1905 docs: update selectors docstrings
  narwhals/_dask/selectors.py
  narwhals/_duckdb/selectors.py
  narwhals/_pandas_like/selectors.py
  narwhals/_spark_like/selectors.py
  narwhals/selectors.py
Labels: documentation, fix
