Repository narwhals-dev/narwhals, pull requests merged in 2025-03, with the labels that each got.

#2114 fix: Allow exprs in `.filter` constraints
  narwhals/dataframe.py
  tests/frame/filter_test.py
Labels: fix, high priority

#2115 chore(typing): Generic `CompliantDataFrame`
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_spark_like/dataframe.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal, typing

#2127 chore: simplify pandas-like over
  .github/workflows/check_tpch_queries.yml
  .github/workflows/downstream_tests.yml
  narwhals/_pandas_like/expr.py
Labels: internal

#2128 feat: Add support for pandas-like `.diff().over(group)`
  narwhals/_pandas_like/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#2122 feat: Adds `nw.exclude`
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/exclude_test.py
Labels: enhancement

#2131 docs: Add API example docs for Field dtype
  narwhals/dtypes.py
Labels: documentation

#2129 fix(typing): Include `Expr` in `fill_null` signature
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/expr.py
Labels: fix, typing

#2133 refactor: Simplify `ArrowGroupBy.__iter__`
  narwhals/_arrow/group_by.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
Labels: internal

#2064 refactor: Generic `CompliantSelector`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/selectors.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/selectors.py
  narwhals/_polars/dataframe.py
  narwhals/_selectors.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/selectors.py
  narwhals/typing.py
  narwhals/utils.py
Labels: api design, typing

#2134 refactor: allow callable in `CompliantExpr.from_column_names` to reuse for `CompliantNamespace.<all|col|exclude>`
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/utils.py
Labels: internal

#2140 refactor: Use `chain.from_iterable` more
  narwhals/_arrow/namespace.py
  narwhals/_expression_parsing.py
Labels: internal

#2138 feat: support anonymous expressions in `over` context for pandas-like, support `over` for multi-partitioned dask
  narwhals/_arrow/group_by.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  pyproject.toml
  tests/expr_and_series/over_test.py
  tests/expr_and_series/rank_test.py
Labels: enhancement

#2141 feat: support reversed cumulative expressions in `over` for pandas-like
  narwhals/_pandas_like/expr.py
  tests/expr_and_series/over_test.py
Labels: enhancement

#2143 fix: pass ddof down in std().over() for pandas-like
  narwhals/_pandas_like/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/over_test.py
Labels: fix

#2145 ci: get cuDF test suite green again
  tests/expr_and_series/over_test.py
  tests/expr_and_series/rank_test.py
  tests/frame/select_test.py
  utils/bump_version.py
Labels: internal

#2147 ci: fix doc build for `win32`
  utils/generate_zen_content.py
Labels: documentation, fix, build

#2153 docs: remove non-existent "args"
  narwhals/_expression_parsing.py
Labels: internal

#2151 docs: Add info in `nw.when` regarding chained statements
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: documentation

#2156 fix: pyarrow scatter was returning incorrect results when indices were not sorted
  narwhals/_arrow/series.py
  pyproject.toml
  tests/series_only/scatter_test.py
Labels: fix

#2157 release: Bump version to 1.29.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2161 ci: fix plotly requirement files in downstream tests
  .github/workflows/downstream_tests.yml
Labels: ci

#2118 ci: Add darts to downstream tests
  .github/workflows/downstream_tests.yml
  README.md
  docs/ecosystem.md
Labels: ci

#2159 fix(typing): Narrow `NativeSeries` Protocol
  narwhals/typing.py
  tests/translate/from_native_test.py
Labels: fix, typing

#2154 perf: simplify pandas scatter
  narwhals/_pandas_like/series.py
  tests/conftest.py
Labels: performance

#2164 fix!: align `Series.filter` param name with Polars
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/series.py
Labels: fix, breaking

#2166 fix: parse timezone-aware datetime strings as UTC consistently across backends
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/series_str.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/utils.py
  narwhals/expr_str.py
  narwhals/series_str.py
  tests/expr_and_series/str/to_datetime_test.py
Labels: bug: incorrect result, fix

#2152 chore(typing): `SparkLikeExpr` properties
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_str.py
Labels: internal, typing

#2130 refactor: adds `_Stores(Native|Compliant)`
  narwhals/_arrow/expr_cat.py
  narwhals/_arrow/expr_dt.py
  narwhals/_arrow/expr_list.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/expr_str.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_cat.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_list.py
  narwhals/_arrow/series_str.py
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal

#2132 feat: support `cum_sum` for lazy backends
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/typing.py
  narwhals/expr.py
  narwhals/typing.py
  narwhals/utils.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/over_test.py
  tests/series_only/scatter_test.py
Labels: enhancement

#2168 feat: add `rolling_sum` for sqlframe and pyspark
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/typing.py
  pyproject.toml
  tests/expr_and_series/rolling_sum_test.py
Labels: enhancement

#2163 docs: even more concise docstrings (#2068)
  narwhals/group_by.py
  narwhals/selectors.py
  narwhals/series_cat.py
  narwhals/series_dt.py
  narwhals/series_list.py
  narwhals/series_str.py
Labels: documentation

#2172 chore(typing): remove unused `pandas-stubs` ignores
  narwhals/utils.py
  tests/utils_test.py
Labels: internal, typing

#2173 docs(ruff): Improve config docs
  pyproject.toml
Labels: documentation, internal

#2146 feat: Added `struct` namespace with `field` method.
  docs/api-reference/expr_struct.md
  docs/api-reference/index.md
  docs/api-reference/series_struct.md
  mkdocs.yml
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_struct.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_struct.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_struct.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_struct.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/series_struct.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_struct.py
  narwhals/expr.py
  narwhals/expr_struct.py
  narwhals/series.py
  narwhals/series_struct.py
  narwhals/typing.py
  tests/expr_and_series/list/len_test.py
  tests/expr_and_series/struct_/__init__.py
  tests/expr_and_series/struct_/field_test.py
  utils/check_api_reference.py
  utils/generate_backend_completeness.py
Labels: enhancement

#2178 feat: support passing multiple arguments positionally to get_native_namespace
  narwhals/translate.py
  tests/translate/get_native_namespace_test.py
Labels: enhancement

#2181 test: fixup cudf failures
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/expr_and_series/struct_/field_test.py
Labels: internal

#2182 release: Bump version to 1.30.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2186 ci: unxfail sqlframe
  tests/expr_and_series/struct_/field_test.py
Labels: internal

#2187 chore(typing): Resolve `sqlframe>=3.24.0` errors
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/group_by.py
Labels: typing

#2149 refactor: adds `_compliant` sub-package
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/expr_cat.py
  narwhals/_arrow/expr_dt.py
  narwhals/_arrow/expr_list.py
  narwhals/_arrow/expr_name.py
  narwhals/_arrow/expr_str.py
  narwhals/_arrow/expr_struct.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/expr_cat.py
  narwhals/_pandas_like/expr_dt.py
  narwhals/_pandas_like/expr_list.py
  narwhals/_pandas_like/expr_name.py
  narwhals/_pandas_like/expr_str.py
  narwhals/_pandas_like/expr_struct.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/typing.py
  narwhals/utils.py
  pyproject.toml
Labels: internal, fix, typing

#2190 type: Use SQLFrame instead of PySpark to type `_spark_like` internally
  .github/workflows/pytest.yml
  .github/workflows/typing.yml
  CONTRIBUTING.md
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/expr_struct.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_spark_like/typing.py
  narwhals/_spark_like/utils.py
  narwhals/translate.py
  pyproject.toml
  tests/conftest.py
  tests/translate/from_native_test.py
  tests/utils.py
Labels: internal, typing

#2199 chore(ruff): add `format` to `builtins-ignorelist`
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/series_str.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_str.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/series_str.py
  narwhals/_spark_like/expr_str.py
  narwhals/expr_dt.py
  narwhals/expr_str.py
  narwhals/series_dt.py
  narwhals/series_str.py
  pyproject.toml
  tests/expr_and_series/str/to_datetime_test.py
Labels: internal

#2200 test: track and enforce sqlframe test coverage
  .github/workflows/pytest.yml
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/utils.py
  pyproject.toml
  tests/expr_and_series/cast_test.py
Labels: internal

#2204 chore: minor duckdb cleanup
  narwhals/_arrow/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/translate.py
Labels: internal

#2208 docs: add metalearners to used by/ecosystem
  README.md
  docs/ecosystem.md
Labels: documentation

#2176 fix: don't downcast `large_string` to `string` unnecessarily in `concat_str` for PyArrow
  narwhals/_arrow/group_by.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/concat_str_test.py
  tests/expr_and_series/lit_test.py
Labels: fix

#2206 feat!: remove require at least one expression be passed to lazyframe select and lazyframe.with_columns, remove lazyframe.clone
  docs/api-reference/lazyframe.md
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/expr_and_series/len_test.py
  tests/frame/clone_test.py
  tests/frame/select_test.py
  tests/frame/with_columns_test.py
Labels: enhancement, breaking

#2211 fix(typing): Match lazy `@overload` in `nw.from_native(...)`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/typing.py
  tests/frame/invalid_test.py
  tests/translate/from_native_test.py
Labels: fix, typing

#2202 chore(typing): Fill out `CompliantNamespace` protocol
  narwhals/_arrow/namespace.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/typing.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
Labels: internal, typing

#2215 chore: Deprecate `native_namespace` in favour of `backend` in `from_numpy`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/from_numpy_test.py
Labels: deprecation

#2216 chore: Deprecate `native_namespace` in favour of `backend` in `read_parquet`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_scan_test.py
Labels: deprecation

#2217 chore: Deprecate `native_namespace` in favour of `backend` in `scan_parquet`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_scan_test.py
Labels: deprecation

#2196 refactor: Add `CompliantSeries.from_numpy`
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_translate.py
  narwhals/dataframe.py
  narwhals/typing.py
Labels: api design, internal

#2218 chore: Deprecate `native_namespace` in favour of `backend` in `scan_csv`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_scan_test.py
Labels: deprecation

#2219 chore: Deprecate `native_namespace` in favour of `backend` in `from_arrow`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/from_pycapsule_test.py
Labels: deprecation

#2221 docs: replace remaining `native_namespace` refs
  docs/basics/dataframe_conversion.md
  narwhals/dataframe.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/new_series_test.py
  tpch/execute.py
Labels: documentation, deprecation

#2224 feat: Raise uniform error when passing Series of different lengths to `with_columns`
  narwhals/_arrow/utils.py
  narwhals/_pandas_like/utils.py
  tests/frame/with_columns_test.py
Labels: error reporting

#2223 chore: Spec `CompliantDataFrame`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/utils.py
Labels: internal, typing

#2228 test: Run TPCH with SQLFrame
  tpch/execute.py
Labels: tests

#2220 Implement `fill_null` for spark-like
  narwhals/_spark_like/expr.py
  tests/expr_and_series/fill_null_test.py
Labels: enhancement

#2113 enh: Adds support for `Time` datatype
  docs/api-reference/dtypes.md
  narwhals/__init__.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_ibis/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/stable/v1/dtypes.py
  narwhals/typing.py
  tests/dtypes_test.py
  tests/expr_and_series/cast_test.py
  tests/series_only/is_ordered_categorical_test.py
Labels: enhancement

#2231 patch: xfail `cast_test.py::test_cast_time` for cudf
  tests/expr_and_series/cast_test.py
Labels: fix

#2233 chore: pin typing dependnecies
  Makefile
  pyproject.toml
Labels: internal

#2234 release: Bump version to 1.31.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2247 feat!: remove `maintain_order` from `LazyFrame.unique`, as it was never supported
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  narwhals/_duckdb/dataframe.py
  narwhals/dataframe.py
  tests/frame/unique_test.py
Labels: enhancement, breaking

#2232 chore: Spec `CompliantLazyFrame`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  narwhals/utils.py
Labels: internal, typing

#2238 chore: move dev dependencies to `dependency-groups`
  .github/workflows/check_docs_build.yml
  .github/workflows/check_tpch_queries.yml
  .github/workflows/downstream_tests.yml
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
  .github/workflows/typing.yml
  CONTRIBUTING.md
  Makefile
  noxfile.py
  pyproject.toml
Labels: ci

#2250 test: Fix yet more tests to work without polars (pandas, pyarrow)
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/dt/ordinal_day_test.py
  tests/expr_and_series/dt/total_minutes_test.py
  tests/expr_and_series/rolling_var_test.py
  tests/frame/collect_test.py
  tests/from_dict_test.py
  tests/translate/from_native_test.py
Labels: tests

#2249 chore: Add `CompliantDataFrame.native`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/utils.py
Labels: internal

#2255 chore: downstream CI cleanup (`validoopsie` and `pointblank`) and re-order dependency groups
  .github/workflows/downstream_tests.yml
  pyproject.toml
Labels: ci

#2235 feat: Enable spark-like backends in `scan_parquet`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/read_scan_test.py
  tpch/execute.py
Labels: enhancement

#2251 chore(typing): add missing `_FullContext` to `CompliantDataFrame`
  narwhals/_compliant/dataframe.py
Labels: fix, typing

#2257 ci: skip Polars nightly if notebook is still running
  .github/workflows/extremes.yml
  tests/expr_and_series/cast_test.py
Labels: internal

#2259 doc: fix docs CI
  .github/workflows/mkdocs.yml
Labels: documentation

#2252 feat: Adds `CompliantGroupBy`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/group_by.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/group_by.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/group_by.py
Labels: api design, internal, typing

#2246 feat: track whether expressions are multi-output, unify error messages
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/selectors.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/utils.py
  narwhals/_expression_parsing.py
  narwhals/_spark_like/utils.py
  narwhals/exceptions.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/selectors.py
  tests/expr_and_series/clip_test.py
  tests/expr_and_series/double_selected_test.py
  tests/expr_and_series/is_between_test.py
  tests/expr_and_series/when_test.py
  tests/frame/invalid_test.py
  tests/frame/reindex_test.py
  utils/check_api_reference.py
Labels: enhancement, error reporting

#2262 chore: Add `CompliantExpr._with_metadata`
  narwhals/_arrow/expr.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
Labels: internal

#2263 feat: support window operations for DuckDB
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  Makefile
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
  narwhals/_spark_like/expr.py
  narwhals/dependencies.py
  pyproject.toml
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/reduction_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/str/to_datetime_test.py
  tests/expr_and_series/sum_horizontal_test.py
  tests/frame/select_test.py
  tests/stable_api_test.py
Labels: enhancement

#2265 feat: add `cum_max` for PySpark
  narwhals/_spark_like/expr.py
  tests/expr_and_series/cum_max_test.py
Labels: enhancement

#2269 fix: safety assertion was being thrown for Expr.is_last_distinct with over and _order_by by pandas and pyarrow
  narwhals/_arrow/expr.py
  narwhals/_pandas_like/expr.py
  tests/expr_and_series/is_last_distinct_test.py
Labels: fix

#2270 enh: Support `diff`, `shift`, `is_first_distinct`, `is_last_distinct` for PySpark, SQLFrame, and DuckDB
  narwhals/_compliant/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/typing.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/shift_test.py
Labels: enhancement

#2272 chore(typing): Move `DepthTracking*` typing
  narwhals/_compliant/group_by.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/typing.py
Labels: internal, typing

#2126 feat: Add support for full join
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  narwhals/utils.py
  tests/frame/join_test.py
Labels: enhancement

#2271 feat: make `order_by` in Expr.over public
  .github/workflows/mkdocs.yml
  docs/basics/order_dependence.md
  mkdocs.yml
  narwhals/expr.py
  pyproject.toml
  tests/expr_and_series/cum_max_test.py
  tests/expr_and_series/cum_min_test.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/over_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/shift_test.py
  tests/expression_parsing_test.py
Labels: documentation, enhancement

#2277 ci: skip test_join_duplicate_column_names on old polars
  tests/frame/join_test.py
Labels: internal

#2279 release: Bump version to 1.32.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2282 chore: always set `CompliantExpr._metadata`
  .github/workflows/extremes.yml
  .github/workflows/pytest.yml
  .github/workflows/typing.yml
  narwhals/_arrow/namespace.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/expr.py
  narwhals/group_by.py
Labels: internal

#2278 feat: Add `cum max` and `cum_min` for DuckDB
  narwhals/_duckdb/expr.py
  tests/expr_and_series/cum_max_test.py
  tests/expr_and_series/cum_min_test.py
Labels: enhancement, duckdb

#2286 feat: add `cum_count` and `cum_prod` to PySpark and DuckDB
  narwhals/_duckdb/expr.py
  narwhals/_spark_like/expr.py
  tests/expr_and_series/cum_count_test.py
  tests/expr_and_series/cum_prod_test.py
Labels: enhancement, pyspark, duckdb

#2287 fix: fixup polars join version check throwing unnecessary deprecation warning for outer join
  narwhals/_polars/dataframe.py
Labels: fix

#2290 chore: Update `._native_frame` refs
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
Labels: internal

#2288 feat: Add `DataFrame.clone` for `pyarrow`
  narwhals/_arrow/dataframe.py
  tests/frame/clone_test.py
Labels: enhancement, pyarrow

#2289 fix: use specialised duckdb functions for std_pop/std_samp/var_pop/var_samp
  narwhals/_duckdb/expr.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/over_test.py
  tests/frame/add_test.py
Labels: fix

#2292 ci: fixup for duckdb pre 1.3
  narwhals/dataframe.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/over_test.py
  tests/frame/add_test.py
Labels: internal

#2296 test: ensure `expected` data has every column of the`result` data
  CONTRIBUTING.md
  tests/expr_and_series/cum_count_test.py
  tests/expr_and_series/cum_max_test.py
  tests/expr_and_series/cum_min_test.py
  tests/expr_and_series/cum_prod_test.py
  tests/expr_and_series/cum_sum_test.py
  tests/expr_and_series/over_test.py
  tests/utils.py
Labels: tests

#2295 feat(sqlframe): Allow options in `scan_parquet` function
  narwhals/functions.py
  tests/read_scan_test.py
Labels: enhancement

#2293 chore: Update `._native_series` refs
  narwhals/_interchange/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/utils.py
Labels: internal

#2283 refactor: `*(Namespace|DataFrame).from_numpy`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/_polars/typing.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/from_numpy_test.py
Labels: internal

#2298 ci: Remove `sqlframe` pin from `--group typing`
  pyproject.toml
Labels: ci, fix

#2301 feat: Add `DuckDBExpr.is_unique()` method
  narwhals/_duckdb/expr.py
  tests/expr_and_series/is_duplicated_test.py
  tests/expr_and_series/is_unique_test.py
Labels: enhancement, duckdb

#2303 perf: Avoid unnecessary calls in `Expr.clip` method
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_duckdb/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_spark_like/expr.py
Labels: performance

#2300 feat: Allow spark-like backends in `scan_csv` function
  narwhals/functions.py
  tests/read_scan_test.py
Labels: enhancement, spark-like

#2280 fix: Expr.mode broadcasting
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/series.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/mode_test.py
Labels: fix

#2294 chore: Add `EagerSeries*Namespace` protocols
  narwhals/_arrow/utils.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_cat.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/series_str.py
  narwhals/_pandas_like/series_struct.py
  narwhals/_pandas_like/utils.py
  narwhals/utils.py
  utils/generate_backend_completeness.py
Labels: internal, typing

#2304 refactor: Add `CompliantDataFrame.from_dict`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_translate.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
Labels: internal

#2311 refactor: Add `LazyExprNameNamespace`
  narwhals/_compliant/expr.py
  narwhals/_compliant/typing.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_name.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_name.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_name.py
Labels: internal

#2309 docs: Expand contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#2314 feat: disallow `.over(order_by=...)` for non-order-dependent operations (as it signals a user error)
  .github/workflows/downstream_tests.yml
  narwhals/expr.py
  tests/expression_parsing_test.py
Labels: enhancement, error reporting

#2313 chore: Tidy up `PolarsExpr`
  narwhals/_polars/expr.py
Labels: internal

#2312 chore(typing): Resolve `_polars.utils` dtype ignores
  narwhals/_polars/utils.py
Labels: internal, typing

#2306 refactor: Add `CompliantDataFrame.from_arrow`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_translate.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/utils.py
  tests/from_pycapsule_test.py
Labels: internal, pyarrow

#2316 fix: change rank ExprKind to transform
  narwhals/_duckdb/expr.py
  narwhals/expr.py
  tests/expression_parsing_test.py
Labels: enhancement, error reporting

#2317 test: add test for shift->cum_sum
  tests/expr_and_series/cum_sum_test.py
Labels: tests

#2318 chore: use Python API more in DuckDB
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
Labels: internal

#2322 ci: fixup cudf test failures, support rolling_std/rolling_var/rolling_mean for pandas in grouped context
  narwhals/_compliant/expr.py
  narwhals/_pandas_like/expr.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_var_test.py
Labels: internal

#2323 release: Bump version to 1.33.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release
