Repository narwhals-dev/narwhals, pull requests merged in 2025-06, with the labels that each got.

#2628 docs: update example of `Series` constructor
  .github/workflows/check_tpch_queries.yml
  narwhals/series.py
Labels: documentation

#2630 chore: remove unnecessary `concat` in stable.v1
  narwhals/stable/v1/__init__.py
  tests/v1_test.py
Labels: internal

#2640 chore: remove some unnecessary `_impl` top-level functions
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/typing.py
  narwhals/typing.py
Labels: internal

#2637 api: remove support for dataframe interchange protocol from main namespace (but keep supported in `narwhals.stable.v1`
  narwhals/_duckdb/series.py
  narwhals/_ibis/series.py
  narwhals/_interchange/dataframe.py
  narwhals/_interchange/series.py
  narwhals/translate.py
  tests/frame/interchange_native_namespace_test.py
  tests/frame/interchange_schema_test.py
  tests/translate/from_native_test.py
Labels: breaking

#2641 feat: improve error messages for IO functions
  narwhals/functions.py
  tests/from_dict_test.py
  tests/from_numpy_test.py
  tests/new_series_test.py
Labels: enhancement, error reporting

#2648 release: Bump version to 1.41.1
  pyproject.toml
Labels: release

#2655 test: raise on nightlies `pandas.error.MergeError`
  tests/frame/join_test.py
Labels: ci, tests, pandas-like

#2656 enh: pushdown over in elementwise operations for spark-like and duckdb
  narwhals/_compliant/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/expr.py
  tests/expr_and_series/over_pushdown_test.py
Labels: enhancement, pyspark

#2659 release: Bump version to 1.42.0
  pyproject.toml
Labels: release

#2661 docs: fix `replace_all` typo in `replace_strict` docstring
  narwhals/expr.py
  narwhals/series.py
Labels: documentation

#2662 chore: refactor `EagerWhen._if_then_else`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_compliant/when_then.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
Labels: internal

#2665 enh: push down over for _horizontal expressions
  narwhals/_duckdb/namespace.py
  narwhals/_spark_like/namespace.py
  tests/expr_and_series/horizontal_broadcasts_test.py
Labels: enhancement

#2667 feat: add `Expr.exp` and `Series.exp`
  docs/api-reference/expr.md
  docs/api-reference/series.md
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  narwhals/series.py
  tests/expr_and_series/exp_test.py
Labels: enhancement

#2654 feat(typing): Add `IntoDType` alias
  docs/api-reference/typing.md
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/utils.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/namespace.py
  narwhals/_ibis/utils.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  narwhals/dtypes.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  tests/expr_and_series/cast_test.py
  tests/series_only/cast_test.py
  tests/v1_test.py
Labels: enhancement, dtypes, typing

#2663 feat: when-then broadcasting
  narwhals/_compliant/when_then.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/dependencies.py
  narwhals/functions.py
  tests/expr_and_series/when_test.py
Labels: enhancement

#2672 fix: align null ordering position for ibis
  narwhals/_ibis/expr.py
  narwhals/_spark_like/expr.py
  tests/expr_and_series/diff_test.py
  tests/expr_and_series/is_first_distinct_test.py
  tests/expr_and_series/is_last_distinct_test.py
  tests/expr_and_series/shift_test.py
Labels: fix

#2620 refactor: Simplify `Implementation.to_native_namespace`
  narwhals/_utils.py
  pyproject.toml
  tests/dependencies/imports_test.py
Labels: internal, spark-like

#2677 chore: Remove unused utility functions
  narwhals/_utils.py
  utils/check_api_reference.py
Labels: internal

#2674 test: Suppress `too_slow` on `test_rolling_var_hypothesis_polars`
  tests/expr_and_series/rolling_var_test.py
Labels: tests

#2681 depr: Deprecate `nw.get_level` from main namespace
  docs/backcompat.md
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/interchange_schema_test.py
  tests/stable_api_test.py
  tests/v1_test.py
Labels: deprecation

#2685 ci: xfail polars_lazy[gpu] to make CI green
  tests/expr_and_series/is_in_test.py
Labels: ci

#2689 refactor: Introduce `PolarsBaseFrame` parent class
  narwhals/_polars/dataframe.py
Labels: internal

#2696 fix: `narwhals.stable.v1.dependencies` was importing `narwhals.dependencies`
  narwhals/stable/v1/__init__.py
  tests/stable_v1_dependencies_test.py
Labels: fix

#2698 release: Bump version to 1.43.1
  pyproject.toml
Labels: release

#2701 ci: update plotly downstream tests
  .github/workflows/downstream_tests.yml
Labels: ci

#2598 feat: Add support for `Expr.str.zfill`
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/series_str.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr_str.py
  narwhals/_ibis/expr_str.py
  narwhals/_pandas_like/series_str.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_spark_like/expr_str.py
  narwhals/expr_str.py
  narwhals/series_str.py
  tests/expr_and_series/str/zfill_test.py
Labels: enhancement, pyspark, pyspark-connect

#2693 typing: restore NativeSeriesT to EagerDataFrame and EagerNamespace, avoid unnecessary broadcast in eager when/then/otherwise
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_compliant/when_then.py
  narwhals/_namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
Labels: internal, typing

#2700 fix: update tests for `cuDF` `25.08.00a`
  narwhals/_polars/utils.py
  tests/expr_and_series/is_in_test.py
  tests/expr_and_series/lit_test.py
  tests/utils.py
Labels: cudf

#2710 fix: raise NotImplementedError instead of returning it
  narwhals/_arrow/utils.py
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_utils.py
Labels: fix

#2702 test: refactor arithmetic floordiv and mod
  tests/expr_and_series/arithmetic_test.py
Labels: tests

#2727 release: Bump version to 1.44.0
  pyproject.toml
Labels: release

#2729 chore: use `window_expression` for DuckDB
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
Labels: internal

#2731 chore(typing): More `isinstance_or_issubclass` overloads
  narwhals/_utils.py
Labels: internal, typing

#2735 deps: Bump polars min version to 0.20.4
  .github/workflows/extremes.yml
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_utils.py
  noxfile.py
  pyproject.toml
  tests/expr_and_series/map_batches_test.py
  utils/generate_random_versions.py
Labels: dependencies, polars

#2714 chore(typing): Improving `_pandas_like.utils`
  narwhals/_dask/dataframe.py
  narwhals/_dask/utils.py
  narwhals/_namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
Labels: internal, typing, pandas-like

#2737 chore: Add `_constants` module
  narwhals/_arrow/series_dt.py
  narwhals/_constants.py
  narwhals/_dask/expr_dt.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/expr_dt.py
  narwhals/translate.py
Labels: internal

#2636 test: div by zero returns nan
  tests/expr_and_series/division_by_zero_test.py
Labels: tests

#2749 chore: Remove pandas-like specific `check_column_names_are_unique` util
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_utils.py
Labels: internal

#2744 chore: Split out, doc `is_dtype_numpy_nullable`
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/series_str.py
  narwhals/_pandas_like/utils.py
  tests/get_dtype_backend_test.py
Labels: internal, tests, pandas-like

#2754 ci: use try_divide in PySpark for division
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/division_by_zero_test.py
Labels: ci, pyspark

#2756 chore: Add `LazyExprNamespace`
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_list.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/expr_struct.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/expr_list.py
  narwhals/_ibis/expr_str.py
  narwhals/_ibis/expr_struct.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_list.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/expr_struct.py
Labels: internal, typing, pyspark, duckdb, dask, pyspark-connect, polars

#2747 feat: Add `Expr|Series.str.to_date`
  docs/api-reference/expr_str.md
  docs/api-reference/series_str.md
  narwhals/_arrow/series_str.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr_str.py
  narwhals/_duckdb/expr_str.py
  narwhals/_ibis/expr_str.py
  narwhals/_pandas_like/series_str.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr_str.py
  narwhals/expr_str.py
  narwhals/series_str.py
  tests/expr_and_series/str/to_date_test.py
  tests/expr_and_series/str/zfill_test.py
  tests/utils.py
Labels: enhancement, pyspark

#2760 test: Suppress `NotImplementedError` for `cuDF`
  tests/get_dtype_backend_test.py
Labels: fix, tests, cudf
