Repository narwhals-dev/narwhals, pull requests merged in 2025-04, with the labels that each got.

#2330 chore(typing): Fix `DTypes` typing
  narwhals/typing.py
  narwhals/utils.py
Labels: fix, typing

#2327 chore: simplify `PandasLikeDataFrame.with_columns`
  narwhals/_pandas_like/dataframe.py
Labels: internal

#2328 chore: Make `Polars(Expr|Series)` compliant
  narwhals/_compliant/expr.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
Labels: internal, typing

#2326 chore: Transition `selectors` away from `Protocol38`
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/typing.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
Labels: internal

#2315 chore: Add `Compliant*.from_native`
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/namespace.py
  narwhals/_translate.py
  narwhals/translate.py
  narwhals/utils.py
Labels: api design, internal, high priority

#2335 fix: unpivot was unnecessary failing for PySpark/SQLFrame when neither `on` nor `index` were passed
  narwhals/_spark_like/dataframe.py
  tests/frame/unpivot_test.py
Labels: fix

#2339 refactor(typing): Simplify `concat` signature
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/invalid_test.py
Labels: fix, typing

#2338 enh: support `unique(keep='none')` for pyspark/sqlframe
  narwhals/_duckdb/dataframe.py
  narwhals/_spark_like/dataframe.py
  tests/frame/unique_test.py
Labels: enhancement

#2336 chore: Use `_compliant.typing` aliases in more places
  narwhals/_arrow/expr.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/typing.py
  narwhals/_compliant/when_then.py
  narwhals/_dask/expr.py
  narwhals/_duckdb/expr.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/expr.py
  narwhals/_spark_like/expr.py
  narwhals/utils.py
Labels: documentation, internal, typing

#2333 feat(internal): Add docstring template
  docstring_template.mustache
Labels: documentation, developer tools, internal

#2353 docs: Use `separate_signature: true`
  mkdocs.yml
Labels: documentation

#2349 test(typing): Narrow `Constructor`, `ConstructorEager` aliases
  tests/conftest.py
  tests/series_only/hist_test.py
  tests/utils.py
Labels: fix, typing, tests

#2331 chore: use less sql for duckdb, do extra validation
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/utils.py
  narwhals/_spark_like/utils.py
Labels: internal

#2350 chore: bump `pyarrow-stubs==19.1`
  narwhals/_arrow/series.py
  narwhals/_arrow/series_dt.py
  narwhals/_pandas_like/series_dt.py
  pyproject.toml
Labels: internal, typing, pyarrow

#2347 fix(typing): Narrow `TypeVar` used in `Series`
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/typing.py
  tests/translate/from_native_test.py
Labels: fix, typing

#2354 release: Bump version to 1.34.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2355 chore(typing): Preserve containers in `cast_for_truediv`
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
Labels: internal, typing, pyarrow

#2365 release: Bump version to 1.34.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2352 feat(typing): Add `polars` literal aliases
  docs/api-reference/typing.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/dataframe.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
Labels: documentation, enhancement, typing

#2341 feat!: disallow `concat(..., how="horizontal")` for `LazyFrame`
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/frame/concat_test.py
  tests/series_only/hist_test.py
Labels: enhancement, breaking

#2374 Fix: Align ``Series.hist`` with new Polars behaviour
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  tests/series_only/hist_test.py
Labels: fix, breaking

#2375 test: use skip tests on old versions instead of xfailing, print slowest tests
  .github/workflows/pytest.yml
  .github/workflows/typing.yml
  narwhals/_arrow/series.py
  tests/expr_and_series/all_horizontal_test.py
  tests/expr_and_series/arithmetic_test.py
  tests/expr_and_series/binary_test.py
  tests/expr_and_series/cast_test.py
  tests/expr_and_series/cat/get_categories_test.py
  tests/expr_and_series/list/len_test.py
  tests/expr_and_series/nth_test.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_var_test.py
  tests/frame/explode_test.py
  tests/frame/join_test.py
  tests/frame/select_test.py
  tests/frame/with_columns_test.py
  tests/hypothesis/basic_arithmetic_test.py
  tests/selectors_test.py
  tests/series_only/hist_test.py
  tests/tpch_q1_test.py
Labels: internal, tests

#2319 feat: Add support for 'ordinal', 'max', 'average' in `DuckDBExpr.rank`
  narwhals/_duckdb/expr.py
  tests/expr_and_series/rank_test.py
Labels: enhancement, duckdb

#2370 chore!: use Python API more for DuckDB support
  .github/workflows/check_tpch_queries.yml
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/utils.py
  tests/frame/unique_test.py
Labels: internal, duckdb

#2368 refactor: Simplify `PandasLikeNamespace.concat`
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/typing.py
  narwhals/_pandas_like/utils.py
Labels: internal, pandas-like

#2378 feat: Remove "unstable" marking from rolling_* and ewm_mean
  narwhals/_compliant/expr.py
  narwhals/_compliant/series.py
  narwhals/expr.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/ewm_test.py
  tests/expr_and_series/rolling_mean_test.py
  tests/expr_and_series/rolling_std_test.py
  tests/expr_and_series/rolling_sum_test.py
  tests/expr_and_series/rolling_var_test.py
Labels: enhancement

#2379 chore: use nw_v1 / nw naming consistently in tests
  tests/expr_and_series/gather_every_test.py
  tests/expr_and_series/head_test.py
  tests/expr_and_series/sample_test.py
  tests/expr_and_series/sort_test.py
  tests/expr_and_series/tail_test.py
  tests/frame/gather_every_test.py
  tests/frame/join_test.py
  tests/frame/schema_test.py
Labels: internal, tests

#2382 fix: `DuckDBLazyFrame.rename` using python API
  narwhals/_duckdb/dataframe.py
  tests/frame/rename_test.py
Labels: fix

#2386 test: xfail cudf where necessary
  tests/expr_and_series/over_test.py
  tests/v1_test.py
Labels: internal

#2387 release: Bump version to 1.35.0
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2381 refactor: Simplify `(Arrow|PandasLike)Namespace.concat`
  narwhals/_arrow/namespace.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/namespace.py
  narwhals/_pandas_like/namespace.py
Labels: internal, pyarrow, pandas-like

#2356 fix(typing): Narrow `TypeVar`(s) used in `(Data|Lazy)Frame`
  narwhals/_arrow/dataframe.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/group_by.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  narwhals/typing.py
  tests/expr_and_series/cast_test.py
  tests/translate/from_native_test.py
Labels: fix, typing

#2362 feat(typing): Add `polars` python type aliases
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/when_then.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/expr.py
  narwhals/functions.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  tests/expr_and_series/lit_test.py
  tests/expr_and_series/when_test.py
Labels: enhancement, typing

#2390 chore: use `__getitem__` less internally
  narwhals/_arrow/expr.py
  narwhals/_arrow/series.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
Labels: internal

#2392 docs: Update installation guide to reflect use of `dependency-groups`
  CONTRIBUTING.md
Labels: documentation

#2371 chore: `@requires` for backend method constraints
  narwhals/_arrow/series.py
  narwhals/_duckdb/expr.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/utils.py
  tests/expr_and_series/nth_test.py
  tests/utils_test.py
Labels: error reporting, internal

#2395 fix: Use `np.generic` in `is_numpy_scalar`
  narwhals/dependencies.py
  tests/dependencies/is_numpy_scalar_test.py
Labels: fix

#2396 docs: add docstrings examples for Int128 and UInt128
  narwhals/dtypes.py
Labels: documentation

#2192 feat: let `nw.Enum` accept categories, map pandas ordered categorical to Enum (only in main namespace, not stable.v1)
  docs/backcompat.md
  narwhals/_dask/utils.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/stable/v1/_dtypes.py
  tests/dtypes_test.py
  tests/frame/schema_test.py
  tests/series_only/cast_test.py
  tests/v1_test.py
Labels: enhancement, dtypes

#2397 chore(typing): Remove `type` from `is_list_of` return
  narwhals/utils.py
Labels: internal

#2398 chore: use `pytest.skip` for dt tests which can never pass
  tests/expr_and_series/dt/convert_time_zone_test.py
  tests/expr_and_series/dt/datetime_duration_test.py
  tests/expr_and_series/dt/replace_time_zone_test.py
  tests/expr_and_series/dt/timestamp_test.py
Labels: internal

#2324 feat: Adds private `Namespace` class
  narwhals/_compliant/typing.py
  narwhals/_namespace.py
  narwhals/_spark_like/dataframe.py
  narwhals/functions.py
  narwhals/stable/v1/_namespace.py
  narwhals/translate.py
  narwhals/utils.py
  tests/namespace_test.py
Labels: enhancement, api design, internal, typing

#2406 chore: DuckDB dtype parsing using `.id` and `.children` properties
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/series.py
  narwhals/_duckdb/utils.py
Labels: internal, duckdb

#2401 feat: Add support for DuckDB Enum
  narwhals/_duckdb/utils.py
  tests/series_only/cast_test.py
  tests/v1_test.py
Labels: enhancement, duckdb

#2407 perf: cache `columns` property for lazyframe's
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_spark_like/dataframe.py
Labels: performance, internal

#2409 feat: Support for additional rank methods in spark-like
  narwhals/_spark_like/expr.py
  tests/expr_and_series/rank_test.py
Labels: enhancement, pyspark, spark-like

#2411 test: update tests so cudf is green
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/dt/replace_time_zone_test.py
Labels: internal

#2393 feat: Improve ``DataFrame.__getitem__`` consistency
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/dataframe.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  narwhals/typing.py
  narwhals/utils.py
  pyproject.toml
  tests/frame/getitem_test.py
  tests/hypothesis/getitem_test.py
  tests/series_only/getitem_test.py
Labels: enhancement

#2414 perf: Delay converting categories to tuple for Enum
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  tests/dtypes_test.py
  tests/stable_api_test.py
  utils/check_api_reference.py
Labels: performance

#2418 test: fixup test suite for cudf
  tests/frame/getitem_test.py
Labels: internal

#2428 ci: fix pointblank downstream test
  .github/workflows/downstream_tests.yml
Labels: ci

#2429 patch: Avoid pyspark no partition for window ops warning
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/utils.py
Labels: fix, pyspark

#2431 chore: Add `Version.dtypes`, remove `import_dtypes_module`
  .pre-commit-config.yaml
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_dt.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/selectors.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_ibis/dataframe.py
  narwhals/_interchange/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
  narwhals/utils.py
Labels: internal

#2433 perf: Add `pa.Table` rename fastpath for `>=17`
  narwhals/_arrow/dataframe.py
Labels: performance, internal, pyarrow

#2426 chore(typing): fix/ignore `utils`, `tpch` warnings
  tpch/__init__.py
  tpch/_typing.py
  tpch/execute.py
  tpch/queries/q1.py
  tpch/queries/q10.py
  tpch/queries/q11.py
  tpch/queries/q12.py
  tpch/queries/q13.py
  tpch/queries/q14.py
  tpch/queries/q15.py
  tpch/queries/q16.py
  tpch/queries/q17.py
  tpch/queries/q18.py
  tpch/queries/q19.py
  tpch/queries/q2.py
  tpch/queries/q20.py
  tpch/queries/q21.py
  tpch/queries/q22.py
  tpch/queries/q3.py
  tpch/queries/q4.py
  tpch/queries/q5.py
  tpch/queries/q6.py
  tpch/queries/q7.py
  tpch/queries/q8.py
  tpch/queries/q9.py
  utils/bump_version.py
  utils/check_api_reference.py
  utils/check_docstrings.py
Labels: internal, typing

#2437 chore: Use less confusing `dask` imports
  narwhals/_dask/expr_dt.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/utils.py
Labels: internal

#2436 chore(typing): Simplify some `__getitem__` annotations
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/series.py
  narwhals/_polars/dataframe.py
Labels: internal, typing

#2325 feat: Allow expressions as `group_by` keys
  .github/workflows/downstream_tests.yml
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/group_by.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/series.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/group_by.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/group_by.py
  narwhals/_expression_parsing.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/group_by.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/group_by.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/group_by.py
  narwhals/dataframe.py
  narwhals/group_by.py
  narwhals/utils.py
  tests/expr_and_series/reduction_test.py
  tests/frame/select_test.py
  tests/group_by_test.py
Labels: enhancement

#2427 docs: Remove inheritable docstrings
  narwhals/stable/v1/__init__.py
  narwhals/stable/v1/_dtypes.py
  narwhals/utils.py
  tests/stable_api_test.py
  tests/v1_test.py
Labels: documentation

#2440 tests: un-xfail polars group by expr streaming
  tests/group_by_test.py
Labels: tests

#2413 feat: Allow non-null strategy in `fill_null` for DuckDB and SparkLike
  .github/workflows/pytest-pyspark.yml
  narwhals/_duckdb/expr.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  tests/expr_and_series/fill_null_test.py
Labels: enhancement, duckdb, spark-like

#2441 chore: remove `setuptool<78` in CI
  .github/workflows/pytest-pyspark.yml
  .github/workflows/typing.yml
Labels: ci, pyspark

#2443 enh: Support `fill_null(strategy=...).over(order_by=...)` for pandas-like
  narwhals/_dask/expr.py
  narwhals/_pandas_like/expr.py
  tests/expr_and_series/fill_null_test.py
Labels: enhancement

#2449 chore(typing): fix `is_sized_multi_index_selector`
  narwhals/_arrow/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/dependencies.py
  narwhals/typing.py
  narwhals/utils.py
Labels: internal, typing

#2448 chore(typing): Rename, unleak `_arrow.typing` aliases
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/series.py
  narwhals/_arrow/typing.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/dependencies.py
  narwhals/series.py
Labels: internal, typing, pyarrow

#2445 test: Simplify `test_lazy_backend`
  tests/frame/lazy_test.py
Labels: tests

#2451 fix: Ensure Polars wrapped in Narwhals can be passed to Joblib
  narwhals/_polars/dataframe.py
  narwhals/_polars/series.py
  pyproject.toml
  tests/joblib_test.py
Labels: fix

#2453 fix: fix nw.Series repr for Polars
  narwhals/utils.py
  tests/repr_test.py
Labels: fix

#2454 release: Bump version to 1.37.1
  docs/installation.md
  narwhals/__init__.py
  pyproject.toml
Labels: release

#2421 perf: Optimize, generalize `_DelayedCategories` -> `_DeferredIterable`
  narwhals/_pandas_like/utils.py
  narwhals/_polars/utils.py
  narwhals/dtypes.py
  narwhals/utils.py
  tests/dtypes_test.py
  tests/utils_test.py
Labels: performance, internal
