Repository narwhals-dev/narwhals, pull requests merged in 2025-07, with the labels that each got.

#2767 ci: pin sqlglot, use different cache_suffixes for different jobs
  .github/workflows/downstream_tests.yml
  .github/workflows/extremes.yml
  .github/workflows/pytest-pyspark.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
  .github/workflows/typing.yml
Labels: internal

#2773 chore: Re-sync `_compliant` exports
  narwhals/_arrow/group_by.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/series.py
  narwhals/_compliant/typing.py
  narwhals/_compliant/window.py
  narwhals/_dask/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_dask/expr_str.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_list.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/expr_struct.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/expr_list.py
  narwhals/_ibis/expr_str.py
  narwhals/_ibis/expr_struct.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/utils.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_list.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/expr_struct.py
Labels: internal

#2764 refactor: Cache, reuse `Implementation._backend_version`
  docs/how_it_works.md
  narwhals/_arrow/dataframe.py
  narwhals/_arrow/expr.py
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_arrow/series.py
  narwhals/_arrow/series_str.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/namespace.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/series.py
  narwhals/_compliant/when_then.py
  narwhals/_dask/dataframe.py
  narwhals/_dask/expr.py
  narwhals/_dask/group_by.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_dask/utils.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/namespace.py
  narwhals/_ibis/selectors.py
  narwhals/_namespace.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/expr.py
  narwhals/_pandas_like/group_by.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_pandas_like/series.py
  narwhals/_pandas_like/series_list.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/dataframe.py
  narwhals/_polars/expr.py
  narwhals/_polars/namespace.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/functions.py
  narwhals/schema.py
  narwhals/series.py
  narwhals/translate.py
  pyproject.toml
  tests/dependencies/imports_test.py
  tests/frame/arrow_c_stream_test.py
Labels: performance, internal

#2780 fix: Respect session time zone when casting to `Datetime` for PySpark
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/utils.py
  tests/expr_and_series/cast_test.py
Labels: enhancement, pyspark

#2784 chore: use _with_elementwise more for DuckDB/spark-like
  narwhals/_duckdb/expr_dt.py
  narwhals/_duckdb/expr_list.py
  narwhals/_duckdb/expr_str.py
  narwhals/_duckdb/expr_struct.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/expr_str.py
  narwhals/_spark_like/expr_dt.py
  narwhals/_spark_like/expr_list.py
  narwhals/_spark_like/expr_str.py
  narwhals/_spark_like/expr_struct.py
  narwhals/expr.py
  narwhals/expr_cat.py
  narwhals/expr_dt.py
  narwhals/expr_list.py
  narwhals/expr_name.py
  narwhals/expr_str.py
  narwhals/expr_struct.py
Labels: internal

#2752 enh!: simplify exceptions, consistently raise InvalidOperationError instead of ShapeError/OrderDependentExprError/LengthChangingExprError
  narwhals/_expression_parsing.py
  narwhals/dataframe.py
  narwhals/exceptions.py
  narwhals/functions.py
  tests/expr_and_series/order_dependent_lazy_test.py
  tests/expr_and_series/unique_test.py
  tests/expr_and_series/when_test.py
  tests/frame/filter_test.py
  tests/frame/group_by_test.py
Labels: error reporting

#2787 chore: clean assorted
  tests/expr_and_series/str/to_datetime_test.py
  tests/expr_and_series/unary_test.py
  tests/frame/group_by_test.py
  tests/v1_test.py
  tpch/execute.py
  tpch/queries/q14.py
  tpch/queries/q9.py
Labels: internal

#2733 feat: Add `Expr.dt.offset_by()`
  docs/api-reference/expr_dt.md
  docs/api-reference/series_dt.md
  narwhals/_arrow/series_dt.py
  narwhals/_compliant/any_namespace.py
  narwhals/_compliant/expr.py
  narwhals/_dask/expr_dt.py
  narwhals/_duckdb/expr_dt.py
  narwhals/_duration.py
  narwhals/_ibis/expr_dt.py
  narwhals/_pandas_like/series_dt.py
  narwhals/_pandas_like/utils.py
  narwhals/_polars/expr.py
  narwhals/_spark_like/expr_dt.py
  narwhals/expr_dt.py
  narwhals/series_dt.py
  tests/expr_and_series/dt/offset_by_test.py
Labels: enhancement, pyspark, pyspark-connect

#2647 feat: Add `coalesce` for all backends
  docs/api-reference/narwhals.md
  narwhals/__init__.py
  narwhals/_arrow/namespace.py
  narwhals/_compliant/namespace.py
  narwhals/_dask/namespace.py
  narwhals/_duckdb/namespace.py
  narwhals/_ibis/namespace.py
  narwhals/_pandas_like/namespace.py
  narwhals/_polars/namespace.py
  narwhals/_spark_like/namespace.py
  narwhals/functions.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/coalesce_test.py
  tests/v1_test.py
Labels: enhancement

#2812 chore: invert version.V1 conditions
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_utils.py
Labels: internal

#2817 ci: unpin mypy in altair job
  .github/workflows/downstream_tests.yml
Labels: internal

#2821 Revert "ci: pin scipy"
  .github/workflows/downstream_tests.yml
Labels: ci

#2822 chore: more v1 test suite cleanups
  tests/dependencies/is_narwhals_dataframe_test.py
  tests/dependencies/is_narwhals_series_test.py
  tests/expr_and_series/order_dependent_lazy_test.py
  tests/series_only/gather_every_test.py
  tests/series_only/head_test.py
  tests/series_only/sort_test.py
  tests/series_only/tail_test.py
  tests/translate/from_native_test.py
  tests/v1_test.py
Labels: internal

#2824 docs: Remove `utils.Version` from API Reference
  docs/api-reference/utils.md
Labels: documentation

#2827 docs: Add `formulaic` to ecosystem list
  README.md
  docs/ecosystem.md
Labels: documentation

#2823 enh: support `offset_by` for cudf
  narwhals/_arrow/series_dt.py
  narwhals/_pandas_like/series_dt.py
  tests/expr_and_series/dt/offset_by_test.py
Labels: enhancement, cudf

#2680 chore: Simplify `PandasLikeGroupBy`
  narwhals/_pandas_like/group_by.py
  pyproject.toml
  tests/frame/group_by_test.py
Labels: internal, tests, pandas-like

#2828 chore: take `reset_index(inplace=True)` out of `_select_results`
  narwhals/_pandas_like/group_by.py
  tests/frame/group_by_test.py
Labels: internal

#2829 chore: Refactor `_apply_exprs_function` internal
  narwhals/_pandas_like/group_by.py
Labels: internal

#2830 perf: avoid redundant copies in `join` for pandas
  CONTRIBUTING.md
  docs/overhead.md
  narwhals/_pandas_like/dataframe.py
Labels: performance

#2831 Enh: Accept negative offsets in `Expr.dt.offset_by()`
  narwhals/_duration.py
  narwhals/_ibis/expr_dt.py
  narwhals/_ibis/utils.py
  tests/expr_and_series/dt/offset_by_test.py
Labels: enhancement

#2826 test: Use pytest-xdist in GHA
  .github/workflows/extremes.yml
  .github/workflows/pytest-pyspark.yml
  .github/workflows/pytest.yml
  .github/workflows/random_ci_pytest.yml
  pyproject.toml
Labels: ci, tests

#2834 enh: `EagerExpr._reuse_series_namespace` to support expressifiable kwargs
  narwhals/_compliant/expr.py
Labels: internal

#2493 fix: unify `ColumnNotFound` for `duckdb` and `pyspark`
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/utils.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/utils.py
  narwhals/exceptions.py
  tests/conftest.py
  tests/frame/drop_test.py
  tests/frame/filter_test.py
  tests/frame/select_test.py
  tests/frame/with_columns_test.py
  tests/utils.py
Labels: error reporting, pyspark, pyspark-connect

#2837 test(typing): Annotate `pytest_addoption`
  tests/conftest.py
Labels: typing, tests

#2841 fix: Fixup logic for new pandas str type
  narwhals/_pandas_like/utils.py
  tests/expr_and_series/str/contains_test.py
  tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
  tests/frame/interchange_to_pandas_test.py
  tests/no_imports_test.py
  tests/repr_test.py
Labels: fix

#2842 release: Bump version to 1.47.1
  pyproject.toml
Labels: release

#2846 perf, fix: avoid using `assign` for `Series.rank` in pandas, fix `Series.rank` for nameless pandas Series
  narwhals/_pandas_like/series.py
  tests/expr_and_series/rank_test.py
Labels: performance, fix

#2849 enh: issue a performance warning for `LazyFrame.schema`
  narwhals/_polars/dataframe.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/dtypes.py
  narwhals/exceptions.py
  tests/dtypes_test.py
  tests/expr_and_series/cast_test.py
  tests/frame/schema_test.py
  tests/v1_test.py
Labels: enhancement, pyspark

#2809 fix: Use `Distribution` for `show_versions`
  narwhals/functions.py
  tests/system_info_test.py
Labels: fix

#2854 fix: Various typos
  narwhals/_dask/expr.py
  narwhals/_spark_like/expr.py
  narwhals/expr.py
  tests/stable_v1_dependencies_test.py
Labels: fix

#2845 ci: bump `ruff==0.12.4`
  .pre-commit-config.yaml
  utils/import_check.py
Labels: ci, dependencies

#2857 tests: sqlframe fully passes `offset_by` test
  tests/expr_and_series/dt/offset_by_test.py
Labels: tests

#2855 ci: Add gt-extras to downstream tests
  .github/workflows/downstream_tests.yml
  README.md
  docs/ecosystem.md
Labels: documentation, ci

#2856 feat: Allow `all` and `any` in group by context
  narwhals/_arrow/group_by.py
  narwhals/_compliant/typing.py
  narwhals/_dask/group_by.py
  narwhals/_pandas_like/group_by.py
  tests/frame/group_by_test.py
Labels: enhancement, spark-like

#2853 chore: Factor out parts of lazy protocols into `narwhals._sql`
  narwhals/_arrow/namespace.py
  narwhals/_arrow/selectors.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/dataframe.py
  narwhals/_compliant/expr.py
  narwhals/_compliant/group_by.py
  narwhals/_compliant/selectors.py
  narwhals/_compliant/when_then.py
  narwhals/_dask/expr.py
  narwhals/_dask/namespace.py
  narwhals/_dask/selectors.py
  narwhals/_duckdb/dataframe.py
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/group_by.py
  narwhals/_duckdb/namespace.py
  narwhals/_duckdb/selectors.py
  narwhals/_duckdb/typing.py
  narwhals/_duckdb/utils.py
  narwhals/_ibis/dataframe.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/group_by.py
  narwhals/_ibis/namespace.py
  narwhals/_ibis/selectors.py
  narwhals/_pandas_like/namespace.py
  narwhals/_pandas_like/selectors.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/group_by.py
  narwhals/_spark_like/namespace.py
  narwhals/_spark_like/selectors.py
  narwhals/_sql/__init__.py
  narwhals/_sql/dataframe.py
  narwhals/_sql/expr.py
  narwhals/_sql/group_by.py
  narwhals/_sql/typing.py
  narwhals/_sql/when_then.py
Labels: internal

#2864 fix: `scatter` was raising unnecessarily for pyarrow
  narwhals/_arrow/series.py
  tests/series_only/scatter_test.py
Labels: fix

#2866 release: Bump version to 1.48.0
  pyproject.toml
Labels: release

#2868 chore: factor out exp() from SparkLike, DuckDB, and Ibis
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_sql/expr.py
Labels: internal

#2867 feat: add `sink parquet` for lazy backends
  docs/api-reference/lazyframe.md
  narwhals/_compliant/dataframe.py
  narwhals/_dask/dataframe.py
  narwhals/_duckdb/dataframe.py
  narwhals/_ibis/dataframe.py
  narwhals/_polars/dataframe.py
  narwhals/_spark_like/dataframe.py
  narwhals/dataframe.py
  tests/frame/sink_parquet_test.py
Labels: enhancement

#2878 ci: Use uv for nightly pandas
  .github/workflows/extremes.yml
Labels: ci

#2874 fix: Allow empty dict in `from_dict`
  narwhals/_arrow/dataframe.py
  narwhals/_pandas_like/dataframe.py
  narwhals/_pandas_like/utils.py
  narwhals/functions.py
  tests/from_dict_test.py
Labels: fix, pyarrow, pandas-like, polars

#2873 feat: Deprecate `Expr.arg_min` and `Expr.arg_max` from the main namespace
  docs/backcompat.md
  narwhals/_duckdb/expr.py
  narwhals/_expression_parsing.py
  narwhals/expr.py
  narwhals/stable/v1/__init__.py
  tests/expr_and_series/arg_min_test.py
  tests/expression_parsing_test.py
  tests/series_only/arg_max_test.py
  tests/series_only/arg_min_test.py
  tests/v1_test.py
Labels: enhancement

#2881 release: Bump version to 1.48.1
  pyproject.toml
Labels: release

#2889 fix: `.clip` should not treat 0 and None as same
  narwhals/_arrow/series.py
  narwhals/_pandas_like/series.py
  tests/expr_and_series/clip_test.py
Labels: fix, high priority, pyarrow, pandas-like

#2871 test: Modern Polars end-to-end tests
  tests/modern_polars/__init__.py
  tests/modern_polars/pivot_test.py
  tests/modern_polars/unpivot_test.py
Labels: internal

#2892 fix `get_column` typing for `stable.v1`
  narwhals/stable/v1/__init__.py
  tests/v1_test.py
Labels: fix

#2839 refactor: Simplify compliant `Series.hist`
  narwhals/_arrow/series.py
  narwhals/_arrow/utils.py
  narwhals/_compliant/__init__.py
  narwhals/_compliant/series.py
  narwhals/_pandas_like/series.py
  narwhals/_polars/series.py
  narwhals/_polars/utils.py
  narwhals/series.py
  narwhals/stable/v1/__init__.py
  tests/series_only/hist_test.py
Labels: internal, pyarrow, pandas-like, polars

#2885 feat: Add `DataFrame.from_dict`
  docs/api-reference/dataframe.md
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/conftest.py
  tests/frame/from_dict_test.py
  tests/v1_test.py
  utils/check_api_reference.py
Labels: enhancement

#2891 feat: Add `DataFrame.from_arrow`
  docs/api-reference/dataframe.md
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/frame/from_arrow_test.py
  tests/v1_test.py
Labels: enhancement

#2887 feat: Add `DataFrame.from_numpy`
  docs/api-reference/dataframe.md
  narwhals/dataframe.py
  narwhals/stable/v1/__init__.py
  tests/frame/from_numpy_test.py
  tests/v1_test.py
Labels: enhancement

#2898 feat!: Allow for chaining `.name` expressions, aligning with Polars' new aliasing behaviour
  narwhals/_compliant/expr.py
  narwhals/_dask/expr.py
  narwhals/_sql/expr.py
  narwhals/expr_name.py
  tests/expr_and_series/name/map_test.py
  tests/expr_and_series/name/prefix_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/expr_and_series/name/to_lowercase_test.py
  tests/expr_and_series/name/to_uppercase_test.py
  tests/selectors_test.py
  tests/series_only/is_ordered_categorical_test.py
Labels: enhancement, breaking

#2899 ci: fixup cudf tests
  narwhals/_dask/expr_dt.py
  tests/expr_and_series/division_by_zero_test.py
  tests/expr_and_series/dt/timestamp_test.py
  tests/expr_and_series/name/suffix_test.py
  tests/modern_polars/pivot_test.py
  tests/modern_polars/unpivot_test.py
Labels: internal

#2906 feat: Warn, instead of raising, in `is_*_dataframe` / `is_*_series` functions
  narwhals/_exceptions.py
  narwhals/_pandas_like/group_by.py
  narwhals/_spark_like/dataframe.py
  narwhals/_utils.py
  narwhals/dataframe.py
  narwhals/dependencies.py
  narwhals/stable/v1/__init__.py
  narwhals/translate.py
  tests/dependencies/is_native_dataframe_series_raise_test.py
  tests/translate/get_native_namespace_test.py
Labels: enhancement

#2910 ci: Run pyspark constructors via path
  .github/workflows/pytest-pyspark.yml
  narwhals/_expression_parsing.py
  narwhals/_spark_like/__init__.py
  narwhals/_sql/__init__.py
Labels: ci

#2876 chore: factor out sqrt from SparkLike, DuckDB, and Ibis
  narwhals/_duckdb/expr.py
  narwhals/_duckdb/namespace.py
  narwhals/_ibis/expr.py
  narwhals/_ibis/namespace.py
  narwhals/_spark_like/expr.py
  narwhals/_spark_like/namespace.py
  narwhals/_sql/expr.py
  narwhals/_sql/namespace.py
Labels: internal

#2915 chore: factor out log from SparkLike, DuckDB, and Ibis
  narwhals/_duckdb/expr.py
  narwhals/_ibis/expr.py
  narwhals/_spark_like/expr.py
  narwhals/_sql/expr.py
Labels: internal
